import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from generate_ebook import generate_ebook

OUT = os.path.dirname(__file__)
ACCENT = "#27AE60"
BG = "#F0FFF5"
SERIES = "The Career Reset Series"

DISCLAIMER = """This book is intended for educational and informational purposes only. Career outcomes depend on many individual factors including market conditions, geography, experience, and circumstances that cannot be accounted for in a general guide.

Nothing in this book constitutes professional career counseling, legal, or financial advice. For legal questions related to employment, consult a qualified employment attorney. For tax questions related to self-employment, consult a qualified tax professional.

The author and publisher make no guarantees regarding employment, income, or career outcomes from applying the concepts in this book."""

# ── Book 1 ────────────────────────────────────────────────────────────────────
b1 = {
    "title": "Burned Out and Starting Over",
    "subtitle": "How to Leave Quietly, Land Intentionally, and Not Make the Same Mistake Twice",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Burnout That Finally Makes You Move", "intro": "Burnout isn't weakness. It's the gap between what your job demands and what your job provides for too long.", "sections": [
            {"heading": "The Warning Signs You Missed", "body": ["Burnout doesn't arrive suddenly. It accumulates through a recognizable progression: early enthusiasm, gradual depletion, increasing cynicism, emotional distance, functional impairment, and eventual crisis or complete withdrawal.", "The cruel irony of burnout is that the symptoms — fatigue, difficulty concentrating, emotional flatness, reduced productivity — look like laziness and incompetence from the outside, right when you need support most.", "If you are reading this in the midst of burnout, know that the inability to just push through is not a personal failure. The system that produced your burnout was not sustainable. Changing it is not quitting. It's self-preservation with a longer time horizon."]},
            {"heading": "Diagnosing What Went Wrong", "body": ["Before moving to a new role, it's worth understanding specifically what produced the burnout. Christina Maslach's burnout research identifies six workplace factors most predictive of burnout: workload, control, reward, community, fairness, and values alignment.", "Rate your last role on each dimension. Then ask: which ones would a new role in the same field likely reproduce? The goal is not to run from burnout into the same structure wearing different branding."]},
        ], "callout": "The next role should solve for the actual problem — not just offer a change of scenery."},
        {"title": "Recovery as Strategy", "intro": "Rushing into the next job from the depths of burnout often reproduces the same conditions. Recovery is not delay — it is preparation.", "sections": [
            {"heading": "What Recovery Requires", "body": ["Genuine recovery from burnout requires: unstructured time (your nervous system needs to learn that urgency is optional), physical restoration (sleep, movement, time outdoors), social reconnection (burnout is isolating; rebuilding human contact is part of recovery), and gradual re-engagement with meaning (gentle activities that provide intrinsic satisfaction without performance pressure).", "If your financial situation permits any recovery time before the next role, use it. If it doesn't, manage your transition search so that recovery is happening in parallel — not just rushing to the next treadmill."]},
        ], "callout": "Rest is not delay. It's the investment that makes the next chapter sustainable."},
        {"title": "The Values Audit", "intro": "Most people don't know precisely what they value in work until it's absent.", "sections": [
            {"heading": "Discovering What You Actually Need", "body": ["Write down the three best periods in your working life — when you felt most engaged, most effective, most energized. Describe each in detail.", "Then extract the conditions. Was it the type of problem you were solving? The people you were working with? The autonomy you had? The recognition you received? The alignment with something you believed in? The learning rate?", "These conditions are your work values — and they should become non-negotiable criteria in your next search. Not every role will meet all of them, but the ones you keep compromising on are the ones that will erode you again."]},
        ], "callout": "The next role should be chosen by your values, not away from your pain."},
        {"title": "The Job Search Strategy", "intro": "Job searching is a project. Projects need strategy.", "sections": [
            {"heading": "Targeted Over Broadcast", "body": ["Broadcasting your resume to every open position is low-quality activity that feels productive. It rarely works — response rates for cold applications average under 3%.", "A targeted strategy: identify 20-30 specific companies where your skills and values fit. Research them. Build warm connections inside them. Apply when you have internal context or referral.", "Quality-of-match matters far more than volume. Ten targeted, well-prepared applications outperform 100 generic ones in virtually every search."]},
        ], "callout": "Job searching is a sales process. Target your prospects."},
        {"title": "The Career Pivot That's Actually Possible", "intro": "Career changes are possible at any age. The realistic ones build on existing assets, they don't abandon them.", "sections": [
            {"heading": "Transferable Skills as Capital", "body": ["Every professional role builds skills that transfer to multiple contexts. Project management, written communication, analysis, leadership, relationship management, technical knowledge — these move between industries more than most people realize.", "The successful career pivot is rarely 'I'm starting from zero in a completely unrelated field.' It's usually 'I'm applying my existing skills to a new domain, at the intersection of what I know and where I want to go.'", "Map your transferable skills honestly. Then research roles in your target field that are adjacent — not the senior roles that require years of specific experience, but the entry points that value what you're bringing."]},
        ], "callout": "You're not starting over. You're applying differently."},
        {"title": "Starting the New Chapter Well", "intro": "The first 90 days in a new role shape the rest of your time there. Invest in them strategically.", "sections": [
            {"heading": "The First 90 Days Framework", "body": ["Michael Watkins' research on executive transitions identifies the first 90 days as disproportionately formative — the impressions, relationships, and early wins you establish in this period anchor how you're perceived for years.", "Prioritize in this order: understand before acting (ask more questions than you answer in the first 30 days), build relationships (with your manager, peers, direct reports, and key stakeholders), identify early wins (visible results that demonstrate competence in the new context), and align on what success looks like (explicit conversation with your manager about expectations and priorities).", "Don't try to change everything in the first 90 days. Demonstrate that you understand before you innovate."]},
        ], "callout": "The first 90 days aren't about proving yourself. They're about understanding the terrain."},
    ]
}

# ── Book 2 ────────────────────────────────────────────────────────────────────
b2 = {
    "title": "The Introverted Professional",
    "subtitle": "How to Advance Without Pretending to Be Someone Else",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Introversion Is Not a Liability", "intro": "The professional world rewards extroversion loudly. But the research on what actually produces results is more complicated.", "sections": [
            {"heading": "What Introversion Actually Is", "body": ["Introversion is not shyness, not social anxiety, and not a lack of social skill. It is a preference for less stimulating environments and a tendency to restore energy through solitude rather than social interaction.", "The research on introverted leadership by Adam Grant and others finds that introverted leaders often produce better outcomes with proactive teams — because they listen more, they're less likely to dominate the best ideas out of the room, and they create space for others to contribute.", "Introversion is a way of processing, not a limitation. The goal is not to become an extrovert but to build a career that uses your actual strengths."]},
        ], "callout": "Build a career that uses your strengths, not one that requires you to override them constantly."},
        {"title": "Networking Without Small Talk", "intro": "Introverts don't hate connection. They hate performative small talk. There's a difference — and it opens a path.", "sections": [
            {"heading": "The Introvert's Networking Advantage", "body": ["Introverts are typically better at one-on-one conversation, at listening deeply, at asking genuine questions, and at following up on conversations they found meaningful. These are the foundations of genuine professional relationships — which are far more valuable than a large network of superficial connections.", "Strategy: instead of attending large networking events (high stimulation, low-quality interaction), invest in: direct one-on-one outreach for coffee or calls, small group gatherings around shared interests, online communities where written exchange is the medium, and building reputation through public work (writing, speaking, contributions to your field)."]},
        ], "callout": "Ten genuine relationships outperform 500 LinkedIn connections you barely know."},
        {"title": "Visibility Without Performance", "intro": "Career advancement requires visibility. Getting visible doesn't require becoming a different person.", "sections": [
            {"heading": "Strategic Visibility", "body": ["Visibility that plays to introvert strengths: writing (articles, thought leadership, documentation that demonstrates expertise), presenting on specific topics you know deeply (introvert-friendly because preparation is thorough and the content carries the interaction), being the person who synthesizes and communicates clearly (the meeting memo, the project update, the stakeholder summary).", "These contributions produce visibility over time without requiring you to be 'on' constantly. They let your work and thinking represent you rather than requiring your social performance to do so."]},
        ], "callout": "Let your work speak. Then let your voice follow."},
        {"title": "Meetings, Presentations, and Managing Up", "intro": "These are the three contexts where introverts most often feel disadvantaged. Each has specific strategies.", "sections": [
            {"heading": "Practical Tactics", "body": ["Meetings: prepare talking points and specific contributions before significant meetings. You don't need to dominate — you need to add value clearly. One well-prepared, well-timed comment often lands better than five improvised ones.", "Presentations: introvert advantage here is preparation. The most memorable presentations are usually the best-prepared ones. Use your inclination for thorough preparation as a competitive advantage.", "Managing up: one-on-one conversations with managers are often more effective for introverts than group settings. Request regular one-on-ones and use them well: come with a clear agenda, update on accomplishments specifically, and surface challenges proactively."]},
        ], "callout": "Preparation is the introvert's secret weapon in high-visibility situations."},
        {"title": "Protecting Your Energy at Work", "intro": "Managing energy, not just time, is the primary productivity strategy for introverts.", "sections": [
            {"heading": "Energy Management Principles", "body": ["Block protected solitary work time in your calendar — this is not optional or negotiable. Open-office environments and meeting-heavy cultures are particularly depleting; protecting time for focused work is a performance necessity, not a preference.", "Batch social and interactive work where possible: back-to-back meetings are less depleting than meetings scattered across the day. Use transition time between social interactions to decompress briefly.", "Communicate your working style as professional information, not apology: 'I do my best thinking with some preparation time — can you send the agenda in advance?' is professional, not weak."]},
        ], "callout": "Energy management is your competitive advantage. Build the systems for it."},
        {"title": "The Long Game for Introverted Careers", "intro": "Introvert strengths often compound over time in ways that extrovert strengths don't.", "sections": [
            {"heading": "What Time Builds", "body": ["Deep expertise: introverts tend to go deep rather than broad, which builds genuine mastery over time. Deep expertise is increasingly valuable as AI handles surface-level knowledge work.", "Trusted relationships: the fewer, deeper relationships introverts build tend to be more durable and more genuinely supportive than large superficial networks.", "Reputation for quality: the inclination toward thoroughness and preparation produces a professional reputation for reliability and quality that compounds over a career.", "The introvert who plays the long game — building expertise, genuine relationships, and a reputation for thoughtful quality — often ends up with the most sustainable and satisfying career."]},
        ], "callout": "Play the long game. Introvert strengths are long-game strengths."},
    ]
}

# ── Book 3 ────────────────────────────────────────────────────────────────────
b3 = {
    "title": "Negotiating at Every Career Stage",
    "subtitle": "From First Job to Executive Compensation",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Why Negotiation at Every Stage Matters", "intro": "Each salary decision compounds. The person who negotiates well early earns dramatically more over a career than the equally skilled person who doesn't.", "sections": [
            {"heading": "The Compounding Math", "body": ["A $5,000 salary negotiation win at age 25, compounded through raises and job changes that all anchor to that base, can represent $50,000-$150,000 in cumulative additional lifetime earnings — depending on field, tenure, and negotiation frequency.", "The same math runs in reverse: under-negotiating early creates a lower base from which all future negotiations grow. Many people discover in their 30s and 40s that they are significantly below market rate for their experience and contribution — and that getting back to market rate requires either risky job changes or multiple years of above-average raises.", "Negotiate every time. Even modestly. The math rewards consistency enormously."]},
        ], "callout": "Every negotiation compounds. Never skip one."},
        {"title": "First Jobs and Entry-Level Negotiations", "intro": "The pressure not to negotiate at the entry level is strong. The cost of giving in to that pressure is also strong.", "sections": [
            {"heading": "What Entry-Level Negotiators Fear", "body": ["The most common entry-level negotiation fear: the offer will be rescinded. This is extremely rare. Companies don't withdraw offers to qualified candidates because they asked a reasonable question about compensation. They may say no — they almost never walk away.", "Entry-level script: 'I'm very excited about this opportunity and I'd like to join the team. Based on my research for this role in this market, I was expecting something closer to [X]. Is there any flexibility there?'", "If they cannot move on salary, ask about: signing bonus, additional vacation days, remote work options, professional development budget, or start date flexibility. There is almost always something."]},
        ], "callout": "They expect you to ask. Not asking signals that you don't know the norm."},
        {"title": "Mid-Career Raise Negotiations", "intro": "The raise conversation is the most commonly avoided negotiation. It is also the most financially accessible one.", "sections": [
            {"heading": "The Business Case Method", "body": ["Build a document before the conversation: specific accomplishments from the past review period with quantitative impact where possible, market salary data for your role and experience level (Glassdoor, LinkedIn Salary, Payscale — three sources minimum), and a clear ask with a specific number.", "Request a formal meeting, not a hallway conversation. Give your manager advance notice of the topic so they can prepare. Come prepared with your document.", "If the answer is no, ask: 'What would need to be true for me to reach [X] by [specific time period]?' Get it in writing. This either produces a real development plan or reveals that the ceiling is structural, which is information you can use to decide whether to stay."]},
        ], "callout": "A documented business case for a raise shows you're managing your career, not begging for a favor."},
        {"title": "Negotiating Job Offers", "intro": "The moment between offer and acceptance is when you have maximum leverage. Use it.", "sections": [
            {"heading": "The Offer Negotiation Framework", "body": ["Always ask for time. 'I'm very excited about this. Can I have until [specific date — 3-5 business days from now] to review?' This is universally expected and provides time to research and prepare.", "Counter with specificity. 'Based on my research and experience, I was expecting [specific number]. Is there flexibility to get there?' Not a range — a number. Ranges anchor to the bottom.", "Total compensation frame. Salary is one element: base, bonus, equity, 401(k) match, benefits, PTO, remote flexibility, professional development, signing bonus. When base is immovable, other elements often are not.", "Express genuine enthusiasm throughout. You're not playing hardball — you're participating professionally in a mutual evaluation."]},
        ], "callout": "Enthusiasm plus preparation is the most effective negotiation combination."},
        {"title": "Executive Compensation", "intro": "Executive compensation is a different game — more complex, more custom, and with higher individual variance.", "sections": [
            {"heading": "The Components", "body": ["Senior-level compensation packages typically include: base salary (a smaller percentage of total than lower levels), annual bonus (often 20-50% of base, tied to company and individual performance), long-term incentive plans (equity vesting over 3-5 years, creating retention and alignment), and benefits (often more negotiable than at lower levels).", "Equity negotiation is the highest-value component at many companies. Understanding vesting schedules, cliff periods, strike prices, and dilution scenarios is important before accepting. At startups, this requires specific diligence — equity in a pre-revenue company has very different characteristics than equity in a public company.", "Executive negotiations benefit from professional support: an executive compensation attorney or an experienced recruiter familiar with the specific sector can significantly improve outcomes."]},
        ], "callout": "At the executive level, equity often matters more than base. Understand it completely."},
        {"title": "The Negotiation You Never Thought to Have", "intro": "Beyond compensation, many valuable career benefits are negotiable — and most people never ask.", "sections": [
            {"heading": "The Underused Negotiation Menu", "body": ["Remote work arrangements: particularly in the current environment, this is often negotiable even when it isn't offered. The value of remote work — in saved commute time, housing flexibility, reduced expense — can be equivalent to a significant salary adjustment.", "Title: a title upgrade can significantly improve your next negotiation, as it establishes your level in a new organization. Titles are often more flexible than salary.", "Learning and development: a professional development budget, conference attendance, tuition reimbursement, or coaching support are often available and rarely requested.", "Schedule flexibility: the ability to manage your time around your life is increasingly important and often available to strong performers who make the direct ask."]},
        ], "callout": "Everything that makes your job better than the competition is worth asking about."},
    ]
}

# ── Book 4 ────────────────────────────────────────────────────────────────────
b4 = {
    "title": "Remote Work Mastery",
    "subtitle": "Thrive, Advance, and Stay Visible When You're Not in the Room",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Remote Work Challenge Nobody Talks About Enough", "intro": "Remote work is better for most people's wellbeing. It's also harder for career advancement if you don't understand the visibility problem.", "sections": [
            {"heading": "The Proximity Bias", "body": ["Research on remote work consistently identifies proximity bias as a real and significant phenomenon: people who are physically present in an office are perceived as more engaged, more committed, and more leadership-ready than equally or more productive remote workers.", "This is irrational but predictable — 'out of sight, out of mind' operates at the neurological level. Managers who see people in the office unconsciously attribute presence to engagement.", "The solution is not to return to the office if you prefer not to. It's to manage your visibility deliberately so that remote work doesn't silently undermine your career trajectory."]},
        ], "callout": "Remote work doesn't harm your career. Invisible remote work does."},
        {"title": "Deliberate Visibility Strategies", "intro": "Visibility in a remote context must be intentional because it doesn't happen accidentally.", "sections": [
            {"heading": "The Visibility Stack", "body": ["Camera on in significant meetings: the ability to read your expressions, energy, and reactions builds the subconscious familiarity that proximity normally creates.", "Regular meaningful updates: a weekly 3-bullet progress update to your manager and key stakeholders keeps your work in their awareness without requiring their time. Consistent visibility is more effective than occasional bursts.", "Async contribution: written contributions to shared documents, detailed feedback in reviews, thoughtful comments in discussion threads — these create a presence trail that accumulates to a visible body of work.", "Proactive over-communication: what would be visible in-office (arriving early, staying late, a chance hallway interaction) must be replaced by deliberate communication signals."]},
        ], "callout": "In remote work, communication is presence. Communicate intentionally."},
        {"title": "Productivity and Focus Without the Office", "intro": "The office provides structure that many people don't realize they depend on. Remote work requires building your own.", "sections": [
            {"heading": "Designing Your Remote Work Environment", "body": ["Physical environment: a dedicated workspace — even a corner of a room that is specifically for work — reduces the psychological spillover between work and personal time. The brain learns to associate the space with work.", "Routine: the morning commute was mostly wasted time, but it also provided a transition ritual. Build an equivalent: a walk, a specific playlist, a consistent start sequence that signals 'work is beginning.'", "The shutdown ritual is equally important: a defined point where work ends, a habit that marks the transition (closing the laptop, writing tomorrow's top priorities, a short walk). Without it, remote work bleeds into personal time indefinitely."]},
        ], "callout": "Your environment and your rituals are your remote work infrastructure."},
        {"title": "Remote Relationships and Trust Building", "intro": "Relationships built in-person are easier to maintain remotely than to build remotely. The investment in remote relationship-building is higher.", "sections": [
            {"heading": "Deliberate Relationship Investment", "body": ["Schedule informal one-on-ones with colleagues — not for work deliverables, just for connection. What you'd bump into in the kitchen, you have to schedule when distributed.", "Invest in face-to-face when you can: company offsites, team gatherings, individual visits to headquarters are higher ROI than most remote workers realize. The trust built in person extends significantly through remote periods.", "Over-invest in the relationships that most affect your career: your manager, your skip-level, your most important cross-functional partners. These relationships require intentional maintenance at a distance."]},
        ], "callout": "Remote relationships require deliberate investment. Schedule it."},
        {"title": "Managing Up When Your Manager Is Remote", "intro": "When your manager is distributed, managing the relationship requires more explicit communication and alignment.", "sections": [
            {"heading": "The Remote Manager Relationship", "body": ["Establish clear communication norms early: how often will you meet, what channel for what kind of communication, what level of autonomy vs. check-in is expected?", "Make your work and priorities visible without requiring them to ask. A weekly update (3 accomplishments, 3 priorities for next week, 1 flag or question) takes 5 minutes to write and costs your manager nothing to stay aligned.", "Explicitly ask about your performance and trajectory on a regular cadence — once a quarter minimum. Remote managers often forget to deliver feedback they'd have given informally in person. Create the context for that conversation."]},
        ], "callout": "Managing up remotely requires making the invisible visible."},
        {"title": "Remote Career Advancement", "intro": "Getting promoted in a remote context requires a different playbook than in-office advancement.", "sections": [
            {"heading": "The Remote Advancement Framework", "body": ["Document everything: in-office, accomplishments and contributions are often visible by osmosis. Remote, you must make them explicit. Keep a running 'brag document' — a private log of wins, contributions, positive feedback, and metrics.", "Create your own sponsorship: find senior people who see your work and are willing to advocate for you in conversations you're not in. This requires deliberate relationship investment and demonstrated competence in their awareness.", "Raise your visibility above your immediate team: presentations to senior stakeholders, written contributions that reach broader audiences, cross-functional projects — anything that makes you known to decision-makers beyond your immediate manager.", "Have the direct conversation: 'I want to grow into [next role]. What do I need to demonstrate, and over what timeframe, to be considered?' This conversation often doesn't happen unless you initiate it."]},
        ], "callout": "Remote promotion happens for people who make themselves impossible to overlook."},
    ]
}

# ── Book 5 ────────────────────────────────────────────────────────────────────
b5 = {
    "title": "The Career in Your 40s",
    "subtitle": "Why It's Not Too Late for a Reinvention and How to Pull It Off",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The 40s Career Reckoning", "intro": "The 40s is when many people realize the career they built is not the one they want. That's not a crisis — it's a data point.", "sections": [
            {"heading": "Why the 40s Produce Career Questions", "body": ["The 40s often bring together several forces simultaneously: enough career experience to see what a particular path looks like 20 years ahead (and whether you want that), enough life experience to know what you actually value versus what you thought you valued, often reduced obligations from the intense early parenting phase, and a growing awareness of time that motivates both urgency and honesty.", "These are productive forces for reinvention. The person who asks 'is this really what I want for the next 25 years?' in their 40s still has a full professional lifetime ahead of them."]},
        ], "callout": "40 is not too late. It is precisely the right time to ask the question."},
        {"title": "The Assets You're Underestimating", "intro": "Professionals in their 40s have career assets that younger workers don't — and often undervalue.", "sections": [
            {"heading": "What Experience Actually Builds", "body": ["Judgment: the ability to distinguish what matters from what doesn't, what's a real crisis from what just feels like one, what a good outcome looks like versus a mediocre one — this takes years to develop and cannot be acquired through information alone.", "Relationships: a network built over 15-20 years includes people who have become genuinely influential in their fields. These relationships are among the most valuable professional assets that exist.", "Credibility: a track record of competence is more persuasive to most employers and clients than a degree or credential. Demonstrated results are not replicable by someone with potential.", "Pattern recognition: the ability to recognize dynamics and situations from experience produces faster, better decisions than analytical frameworks alone."]},
        ], "callout": "Your experience is your competitive advantage, not your liability."},
        {"title": "Ageism Is Real — and Navigable", "intro": "Age discrimination in hiring is illegal but common. Understanding where it shows up most allows you to route around it.", "sections": [
            {"heading": "Where Ageism Concentrates", "body": ["Ageism in hiring concentrates in: highly competitive volume-hiring tech companies, entry-level or mid-level roles where companies expect many years of future tenure, startups hiring primarily young workforces, and industries with strong 'culture fit' language that often codes for demographic conformity.", "It is less prevalent in: senior roles, consulting and advisory contexts, industries that value specific deep expertise, roles with immediate deliverables rather than cultural assimilation, self-employment and consulting, and organizations with more experienced leadership.", "Strategy: target contexts where your experience is an explicit advantage, not a suspected liability."]},
            {"heading": "Practical Navigation", "body": ["Resume: drop dates from degrees if they'd reveal age. List only the last 15 years of experience (enough for any legitimate evaluation). Update your formatting to a modern template.", "LinkedIn: current photo, modern presentation, skills that reflect current market demand (not tools from 15 years ago), recent activity that demonstrates current engagement.", "Demonstrate current relevance: whatever is newest and most in-demand in your field, have clear proficiency — whether that's AI tools, current platforms, recent methodologies, or current frameworks."]},
        ], "callout": "Navigate around ageism. Don't argue with it."},
        {"title": "The Reinvention Plan", "intro": "Career reinvention in your 40s is real — but it's better done as an evolution than a cliff jump.", "sections": [
            {"heading": "The Gradual Pivot", "body": ["The most successful mid-career reinventions are incremental: one skill, one project, one relationship, one role at a time, moving toward the new direction while maintaining the income and credibility of the existing path.", "Very few people can afford to simply stop their career, retrain from scratch, and start again at an entry level in a new field. The more practical path: identify how existing expertise maps to the new domain, find the adjacent roles that value both old and new, and build credibility in the new direction through side projects, consulting, volunteering, or education."]},
        ], "callout": "Reinvention is a direction, not a date."},
        {"title": "Starting a Business in Your 40s", "intro": "The data on entrepreneurial success skews toward experience. The 40s may be the best decade to start.", "sections": [
            {"heading": "Why Experience Matters in Business", "body": ["Research by Pierre Azoulay and colleagues at the MIT Sloan School of Management found that the average age of a successful startup founder is 45 — not 25. Older founders have higher success rates precisely because they have the domain expertise, professional networks, judgment, and financial resources that younger founders typically lack.", "The business that uses your existing expertise is not a lesser ambition than a completely novel startup. Consulting, coaching, advisory, or service businesses built on 15-20 years of specific domain knowledge often have clear market fit, established credibility with potential clients, and minimal initial capital requirements."]},
        ], "callout": "The 40s are statistically the most successful decade to start a business."},
        {"title": "The 25-Year Sprint", "intro": "The professionals who thrive in the 40s and beyond are those who are investing in their long game, not managing their decline.", "sections": [
            {"heading": "Long-Horizon Thinking", "body": ["A 45-year-old professional has a 25-year professional runway ahead of them — more time than they spent building their entire career to that point. Thinking about career decisions with this horizon changes what's worth investing in.", "Skills that compound over decades: deep expertise, genuine relationships, public credibility and reputation, clarity about what you uniquely offer. These are worth building even if they take years to pay off.", "The mistake to avoid: coasting on existing expertise because the effort of growth feels disproportionate to the remaining time. The remaining time is long. Keep growing."]},
        ], "callout": "You have 25 years left. Invest accordingly."},
    ]
}

# ── Book 6 ────────────────────────────────────────────────────────────────────
b6 = {
    "title": "Building a Personal Brand That Actually Works",
    "subtitle": "How to Become Known for What You're Best At",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Personal Brand Actually Means", "intro": "Personal brand is what people think of when they think of you professionally. You're building it whether you intend to or not.", "sections": [
            {"heading": "The Intentionality Argument", "body": ["Every professional interaction, every piece of work you produce, every written communication — all of this forms an impression in others' minds. That accumulated impression is your personal brand, whether you've explicitly crafted it or not.", "The question is not whether you have a personal brand. It's whether it accurately reflects your actual strengths and values, and whether it's building toward the reputation you want.", "The risk of not managing your brand intentionally: others define it for you, often based on incomplete information or your role in a single context. The person who is 'the one who fixes things when they break' at one company needs to be much more than that in the broader market."]},
        ], "callout": "Your reputation precedes you. Build the one you want."},
        {"title": "Defining Your Positioning", "intro": "Effective personal branding starts with clarity about what you offer that others don't — or don't offer as well.", "sections": [
            {"heading": "The Positioning Statement", "body": ["'I help [specific audience] accomplish [specific outcome] through [specific approach or expertise].'", "This structure forces the specificity that makes a personal brand useful. Vague positioning — 'I'm a great leader' or 'I'm passionate about marketing' — is undefended and unremarkable.", "Examples of strong positioning: 'I help B2B SaaS companies reduce customer churn through behavioral analytics and onboarding redesign.' 'I help family-owned businesses navigate leadership succession without destroying the relationships that built the company.'", "The positioning statement is not your elevator pitch — it's your internal compass. It guides what content to create, what opportunities to pursue, and what to say no to."]},
        ], "callout": "Specific positioning is defensible. Generic positioning is invisible."},
        {"title": "Content and Thought Leadership", "intro": "Written, spoken, or visual content that demonstrates your expertise is the primary mechanism for building a public professional reputation.", "sections": [
            {"heading": "The Content Minimum Viable Approach", "body": ["You don't need to be everywhere. You need to be visible and consistent somewhere.", "Choose one medium (written, video, audio), one platform (LinkedIn for most B2B professionals, YouTube for video creators, a podcast for audio), and one cadence you can sustain (weekly is ideal; monthly is better than nothing).", "The content that builds reputation is not generic advice that anyone could give — it's specific perspective drawn from your specific experience. The counterintuitive observation. The nuance that most content in your field misses. The case study from your specific domain."]},
        ], "callout": "Specificity and consistency are the only two things that matter in content."},
        {"title": "The LinkedIn Strategy That Works", "intro": "LinkedIn is the primary platform for professional reputation management. Most people use it passively. The active approach is dramatically more effective.", "sections": [
            {"heading": "The Active LinkedIn Approach", "body": ["Profile optimization: headline that describes your value proposition, not just your current title. About section that tells a professional story. Skills and experiences that reflect where you're going, not just where you've been.", "Content creation: one substantive post per week. Not viral bait — specific professional insight drawn from your experience and expertise.", "Engagement: thoughtful comments on content by people in your target audience or target industries. This builds visibility with specific communities faster than posting alone.", "Outreach: personalized connection requests with a specific reason for connecting. Not 'I'd like to add you to my network' — 'I read your piece on X and wanted to connect because I work in a related area and found your point about Y particularly useful.'"]},
        ], "callout": "LinkedIn is a professional publishing platform. Treat it that way."},
        {"title": "Speaking, Writing, and Credibility Building", "intro": "External credibility-building activities carry weight that internal performance alone cannot build.", "sections": [
            {"heading": "Earned Authority Signals", "body": ["Publishing: a book, a significant article in a respected publication, a byline in an industry journal — these carry credibility disproportionate to their content because they signal external validation.", "Speaking: conference presentations, podcast appearances, webinars — reaching audiences beyond your immediate organization builds recognition and positioning.", "Awards and recognition: industry awards, lists, and recognitions are worth pursuing not for ego but for the search visibility and credibility they provide. Apply systematically for relevant industry recognition.", "All of these require investment. They also produce compounding returns — each external credential builds the case for the next opportunity."]},
        ], "callout": "External validation amplifies internal reputation. Pursue it strategically."},
        {"title": "Protecting and Evolving Your Brand", "intro": "A personal brand is a living thing that needs maintenance and adaptation.", "sections": [
            {"heading": "Ongoing Brand Management", "body": ["Audit your digital presence quarterly: Google your name, review your LinkedIn, check that your profile accurately reflects your current positioning.", "Every 1-2 years, reassess your positioning: is this still where my expertise and the market intersect? Has my focus evolved? Are there new capabilities I should be known for?", "Protect the brand you've built: every public communication, every professional interaction either confirms or undermines your positioning. Consistency matters over years, not just weeks.", "The most powerful personal brand is built on genuine expertise, authentic perspective, and consistent demonstration over time. These are slow to build and very hard to fake at scale — which is exactly what makes them valuable."]},
        ], "callout": "Authentic expertise, consistently demonstrated, is the only personal brand that compounds."},
    ]
}

# ── Book 7 ────────────────────────────────────────────────────────────────────
b7 = {
    "title": "Difficult Conversations at Work",
    "subtitle": "How to Say Hard Things Without Making Everything Harder",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Why We Avoid the Conversations We Most Need to Have", "intro": "The avoided conversation doesn't disappear. It waits — and usually grows while it waits.", "sections": [
            {"heading": "The Cost of Avoidance", "body": ["Research on organizational communication consistently finds that the issues causing the most damage are usually the ones nobody is talking about — performance problems left unaddressed, conflicts allowed to fester, feedback withheld until exit interviews.", "The professional cost of conversation avoidance: problems that stay unresolved, relationships that erode without either party understanding why, trust that decreases because real concerns are never surfaced, and the accumulation of unspoken resentment that eventually explodes or simply causes quiet disengagement.", "Most difficult conversations are avoided because we predict a worse outcome than the evidence supports. The actual outcome of well-prepared, well-conducted difficult conversations is typically far better than the feared scenario."]},
        ], "callout": "The conversation you're avoiding is usually the one most worth having."},
        {"title": "Preparation Is Everything", "intro": "Difficult conversations succeed or fail before they start.", "sections": [
            {"heading": "The Pre-Conversation Work", "body": ["Clarify your purpose: what outcome are you trying to achieve? Not just 'this needs to be said' but what specifically would a good outcome look like? What would need to be different after this conversation?", "Check your interpretation: what story are you telling about the situation? Are you certain it's accurate? What information might you be missing? What might be contributing to the problem that has nothing to do with the person you're about to speak with?", "Prepare for their response: what are the most likely reactions? How will you respond to defensiveness, counter-attack, tears, dismissal? Having responses ready prevents being derailed by the emotional charge of the moment."]},
        ], "callout": "Every hour of preparation saves three hours of consequence management."},
        {"title": "The Conversation Structure That Works", "intro": "Effective difficult conversations follow a structure. Knowing it in advance lets you stay on course when emotions rise.", "sections": [
            {"heading": "The Framework", "body": ["Open with inquiry, not conclusion: 'I wanted to talk with you about X. I've noticed Y and I wanted to hear your perspective first' invites dialogue. 'We need to talk about the problem you're causing' closes it before it starts.", "Describe behaviors, not character: 'The last three deliverables were submitted after the deadline' is a factual observation about behavior. 'You're unreliable and don't care about the team' is a character attack. The first is discussable. The second is just damaging.", "Acknowledge their perspective: genuinely listening — not just waiting to respond — often reveals information that changes your understanding of the situation.", "Identify the path forward together: a collaborative solution is more likely to be implemented than a directive one. 'What do you think would help us get to X?' treats the other person as a capable adult with ideas about their own situation."]},
        ], "callout": "Inquiry before conclusion. Behavior before character. Always."},
        {"title": "Receiving Feedback and Criticism", "intro": "Receiving difficult feedback well is as important a professional skill as delivering it — and rarer.", "sections": [
            {"heading": "The Art of Hearing Hard Things", "body": ["The hardest part of receiving difficult feedback is the physiological response: the shame, defensiveness, or hurt that arises before you've even processed the content. This response is faster than thought and will drive your response if you don't manage it.", "The practical protocol: listen to completion without interrupting or defending. Pause before responding (even 10 seconds is significant). Ask clarifying questions before accepting or rejecting the feedback: 'Can you give me a specific example of what you mean by X?'", "Even if you disagree with the feedback, acknowledge its receipt: 'I appreciate you telling me this. I want to think about it.' This keeps the relationship and the information channel open."]},
        ], "callout": "The ability to hear hard feedback without shutting down is a leadership differentiator."},
        {"title": "Performance Conversations", "intro": "Performance conversations — both delivering and receiving — are among the highest-stakes professional communications.", "sections": [
            {"heading": "For Managers: The Kindness of Clarity", "body": ["The kindest thing a manager can do for an underperforming employee is be specific, early, and direct. Vague, delayed feedback allows problems to compound while the employee doesn't know they're in trouble.", "'Your communication style in cross-functional meetings is creating friction with the team' is specific and actionable. 'Sometimes people have concerns about your approach' is neither.", "Documented feedback, specific behavioral targets, clear timelines, and genuine support for improvement — this is fair, legal, and human. Hoping the problem resolves itself or waiting until it becomes a formal HR matter is not kind to anyone."]},
            {"heading": "For Employees: Owning the Conversation", "body": ["If you are receiving formal performance feedback, your primary objective is to understand specifically what needs to change and by when. Ask for: specific examples of the problematic behavior, specific metrics or behaviors that would indicate improvement, the timeline for reassessment, and any support available.", "Defensiveness in a performance conversation is rarely productive and often damages your standing. Ownership — acknowledgment of the issue, demonstrated understanding of what change is needed, and follow-through — is almost always the better path."]},
        ], "callout": "Specific, early feedback is a gift. Late, vague feedback is negligence."},
        {"title": "Navigating Conflict Between Peers", "intro": "Workplace conflict between peers is one of the most common and most poorly handled professional challenges.", "sections": [
            {"heading": "The Peer Conflict Protocol", "body": ["Peer conflicts that aren't addressed tend to escalate or go underground — the relationship becomes professionally transactional at best, actively corrosive at worst.", "Before involving management: make one direct, private attempt to address the conflict. 'I've noticed tension between us around X. I'd like to understand your perspective and see if we can work this out directly.'", "If direct conversation fails: HR consultation (for policy questions or serious conduct issues) or manager involvement (for persistent conflicts impacting team function) are appropriate escalations — not the first resort.", "After resolution: don't expect the relationship to immediately feel normal. Professional civility, maintained consistently over time, can rebuild working relationships even when personal closeness isn't possible."]},
        ], "callout": "Direct, private, early is the peer conflict hierarchy."},
    ]
}

# ── Book 8 ────────────────────────────────────────────────────────────────────
b8 = {
    "title": "Leadership Without Authority",
    "subtitle": "How to Lead, Influence, and Drive Results When You're Not the Boss",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Modern Work Reality", "intro": "Most valuable work in organizations happens across teams, functions, and reporting lines. None of it requires formal authority.", "sections": [
            {"heading": "Why Formal Authority Is Overrated", "body": ["Positional authority — the ability to direct people because you're higher in the hierarchy — is a blunt instrument. People comply with it, but compliance is not commitment, and compliance is not the same as the creative, discretionary effort that produces excellent outcomes.", "Influence — the ability to shape others' thinking and behavior without the threat of consequences — is more durable, more transferable, and more effective at producing the outcomes you actually want. You can lose a title. Influence, once built, follows you.", "The most effective organizational operators — the people who consistently get things done in complex environments — are almost always the ones with influence that exceeds their authority."]},
        ], "callout": "Authority gets compliance. Influence gets commitment."},
        {"title": "Trust as the Foundation of Influence", "intro": "Without trust, influence has no medium to travel through.", "sections": [
            {"heading": "Building Trust Without Position", "body": ["Trust is built through: consistently following through on commitments (reliability), demonstrating genuine competence in your domain (competence), showing genuine care for others' success rather than just your own (benevolence), and being honest even when honesty is uncomfortable (integrity).", "Each of these is within your control regardless of your role or level. Trust is built incrementally, in small consistent acts, over time. It cannot be demanded or fast-tracked.", "The most powerful trust-building behavior: doing what you say you will do, when you said you would, at the quality level you committed to. This sounds obvious. Most people don't do it consistently, which means those who do stand out enormously."]},
        ], "callout": "Trust is built in every small promise kept."},
        {"title": "Stakeholder Mapping and Alignment", "intro": "Projects that fail at the organizational level almost always fail because of stakeholder dynamics, not technical quality.", "sections": [
            {"heading": "The Alignment Work", "body": ["Before any significant cross-functional initiative, map the stakeholders: who is affected by this? Who has influence over the outcome? Who needs to say yes? Who could block it?", "For each key stakeholder: what is their goal? What are they worried about? What's in it for them to support this, and what's the cost if they do? What's the argument they would need to hear to get their buy-in?", "The meeting before the meeting: most decisions in organizations are made before the decision meeting — in hallway conversations, one-on-ones, and individual stakeholder conversations. Winning those conversations is the real influence work."]},
        ], "callout": "The real decision happens before the decision meeting."},
        {"title": "Communication as Influence", "intro": "The most influential people in organizations are almost always the clearest communicators.", "sections": [
            {"heading": "The Clarity Advantage", "body": ["In environments of information overload, ambiguity, and competing priorities, the person who communicates with clarity and precision is immediately more influential — because people understand what they're saying and can act on it.", "The pyramid principle: lead with your conclusion, then support it. Don't build to your conclusion through context that people may stop reading before you get there. 'My recommendation is X because of A, B, and C' outperforms 'Let me walk you through the background that led to my recommendation...'", "Tailor communication to audience: the same information packaged differently for the executive who needs the summary and the technical team that needs the detail. Neither version is dishonest — both are appropriate."]},
        ], "callout": "Clarity is the most underinvested communication skill."},
        {"title": "Leading Upward", "intro": "Managing your relationship with your manager and senior stakeholders is leadership work — not political maneuvering.", "sections": [
            {"heading": "The Art of Managing Up", "body": ["Understand their goals: what does success look like for your manager and their stakeholders? When you understand what they're optimizing for, you can frame your work in terms of what they care about.", "Proactive over reactive: don't wait to be asked for updates on important work. Surface risks before they become crises. Come to discussions with proposed solutions, not just identified problems.", "Ask for what you need: most managers are not mind-readers. If you need clearer direction, more autonomy, additional resources, or different feedback — ask directly and specifically.", "The relationship with your manager is one of the highest-leverage professional investments you can make. It shapes your opportunities, your support, and your trajectory in an organization."]},
        ], "callout": "Managing your manager is a professional skill, not a political one."},
        {"title": "The Influence Portfolio", "intro": "Long-term organizational influence is built across multiple dimensions simultaneously.", "sections": [
            {"heading": "Compounding Your Influence", "body": ["Expertise: being the go-to person for something specific and valued creates a flow of opportunities, conversations, and relationship-building that other influence sources don't.", "Network: having genuine relationships across the organization gives you information, access, and allies that narrow networks don't provide.", "Track record: consistently producing results builds the credibility that earns you benefit of the doubt in future initiatives.", "Reputation for fairness: being known as someone who treats people well, acknowledges others' contributions, and behaves consistently whether or not they're being observed creates enormous organizational goodwill that translates into influence.", "The compounding effect: each dimension reinforces the others. Expertise builds reputation; reputation builds network; network provides opportunities to demonstrate expertise and build track record."]},
        ], "callout": "Influence is a portfolio, not a single attribute."},
    ]
}

# ── Book 9 ────────────────────────────────────────────────────────────────────
b9 = {
    "title": "The Consultant Mindset",
    "subtitle": "How to Think Like an Independent Expert and Get Paid Like One",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Why the Consultant Mindset Is Valuable Even If You Stay Employed", "intro": "Thinking like a consultant — regardless of employment status — changes how you show up and how you're valued.", "sections": [
            {"heading": "The Internal Consultant Advantage", "body": ["Employees think about their responsibilities. Consultants think about outcomes. The distinction matters enormously to the people who decide compensation, promotion, and interesting assignments.", "An internal consultant approach: you treat each engagement as a project with a specific client (internal stakeholder) who has a specific problem to solve. You deliver a defined outcome, communicate its value clearly, and continuously evaluate whether the time you're spending is producing results worth having.", "This mindset produces more visible impact, more useful relationships with senior stakeholders, and much more negotiating power — whether negotiating salary, role, or the decision to leave for consulting or another opportunity."]},
        ], "callout": "Outcome thinking is rarer and more valuable than responsibility thinking."},
        {"title": "Going Independent: The Honest Preparation", "intro": "Consulting is an attractive career model with real freedom and real challenges. Go in with clear eyes.", "sections": [
            {"heading": "What Independent Consulting Actually Requires", "body": ["Consulting income is lumpy: feast and famine cycles are normal, particularly in the first two years. A financial runway of at least 6-12 months of living expenses before transitioning significantly reduces the desperate acceptance of poor-fit clients.", "Business development is non-optional: approximately 25-40% of a consultant's working time goes to business development — finding, qualifying, and closing new clients. Many excellent practitioners significantly underestimate this before going independent.", "Consulting requires working alone: the social support, intellectual stimulation, and structure of organizational life disappear. Some people thrive; many find the isolation harder than expected.", "These are not reasons not to consult. They are the things to solve for before the transition, not after."]},
        ], "callout": "Consulting is best prepared for like a business launch, not escaped into like a vacation."},
        {"title": "Defining Your Consulting Niche", "intro": "The consultants who earn the most are not generalists. They are specific experts with clear positioning.", "sections": [
            {"heading": "The Niche Decision", "body": ["The fear of niching is the fear of missing clients. The reality: niching creates clients by making it obvious who you serve and why you're the right choice for them.", "Your niche is defined by: what you know deeply (domain expertise), who you serve specifically (industry, company size, role), and what problem you solve (the specific outcome clients pay for).", "A useful test: can you articulate your niche in one sentence that a potential client would immediately recognize as relevant to their situation? 'I help e-commerce companies reduce cart abandonment through checkout flow optimization' is a niche. 'I help companies improve their business' is a description."]},
        ], "callout": "The riches are in the niches."},
        {"title": "Pricing as Positioning", "intro": "Your price is a signal. Low prices signal low value. Value-based pricing signals expertise.", "sections": [
            {"heading": "From Hourly to Value-Based", "body": ["Hourly rates are intuitive but suboptimal: they cap earnings by time, reward inefficiency (more hours billed), and commoditize expertise by reducing it to an hourly exchange.", "Project-based pricing — a fixed fee for a defined deliverable — aligns incentives, allows you to earn more as you become more efficient, and communicates confidence in your ability to deliver outcomes.", "Value-based pricing — a fee based on the value created for the client rather than your time cost — is the highest-leverage pricing model and is appropriate once you have a track record of delivering specific measurable results.", "The right price is the one at which clients who are a good fit find it easy to say yes, and at which you are being compensated appropriately for the outcomes you create."]},
        ], "callout": "Price to your value, not your hours."},
        {"title": "Client Acquisition Without Cold Outreach", "intro": "The most sustainable consulting businesses are built on referrals and reputation, not cold prospecting.", "sections": [
            {"heading": "The Referral Engine", "body": ["Every satisfied client is a potential referral source — but most consultants don't create the conditions for referrals systematically.", "The referral conditions: clients who got remarkable results, clients who felt genuinely cared for throughout the engagement, clients who know what you're looking for next, and a consultant who makes it easy to refer (specific description of ideal clients, simple process for introduction).", "Request referrals explicitly: 'Do you know anyone else who is dealing with X type of problem who might benefit from working together?'", "Content marketing, speaking, and writing in your niche create inbound opportunities from people who encounter your thinking before they encounter you — often warmer leads than any cold outreach can produce."]},
        ], "callout": "The best client acquisition is the result of the last engagement done exceptionally well."},
        {"title": "The Sustainable Consulting Practice", "intro": "Consulting freedom is real. Consulting burnout is also real. Designing for sustainability from the start is the difference.", "sections": [
            {"heading": "Designing for Longevity", "body": ["Set a maximum number of simultaneous clients — most solo consultants do their best work with 2-4 active clients. More than that degrades quality and attention.", "Price for quality over quantity: fewer, higher-paying clients at deeper engagement is more sustainable and more intellectually satisfying than many thin relationships.", "Build in recovery time: the consulting model should include space for learning, thinking, and personal restoration — not just billing. The consultant who is always billable is depleting the asset that produces the billings.", "The consulting practice that lasts is one designed around the life you want to live, not just the revenue you want to generate."]},
        ], "callout": "The consulting practice should serve your life. Not consume it."},
    ]
}

# ── Book 10 ───────────────────────────────────────────────────────────────────
b10 = {
    "title": "Work-Life Integration",
    "subtitle": "Why 'Balance' Is the Wrong Frame — and What Actually Works",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Balance Myth", "intro": "Work-life balance implies two things in opposition, with a scale between them. Life doesn't work that way.", "sections": [
            {"heading": "Why the Metaphor Fails", "body": ["The balance metaphor implies that more of one means less of the other — that a good work day comes at the cost of a good personal day. This framing produces unnecessary guilt: whenever you're working, you feel you should be present for family; whenever you're present for family, you feel you should be working.", "The integration frame is more accurate: work and personal life are parts of a single life, and the goal is to design that whole life in a way that feels coherent, sustainable, and aligned with what matters to you.", "Integration doesn't mean work and life are always harmonious. It means you're making conscious choices about where your time goes and why — not just reacting to competing demands."]},
        ], "callout": "You don't need balance between two lives. You need a single life that works."},
        {"title": "Energy Management Over Time Management", "intro": "You can't create more time. You can create more energy — which is the real scarcity.", "sections": [
            {"heading": "The Four Dimensions of Energy", "body": ["Tony Schwartz's energy management model identifies four dimensions: physical (sleep, exercise, nutrition, recovery), emotional (quality of relationships, sense of meaning, ability to regulate feelings), mental (focus, cognitive recovery, variety of cognitive tasks), and spiritual (clarity about values and purpose).", "Burnout is energy depletion across multiple dimensions simultaneously — not just physical exhaustion. Recovery requires restoration across multiple dimensions.", "The question to ask is not 'how do I get more done in less time?' It's 'what am I doing that depletes my energy disproportionately to its value, and what am I not doing that would restore it?'"]},
        ], "callout": "Energy is the real scarce resource. Manage it deliberately."},
        {"title": "Boundaries Around Time", "intro": "Without explicit boundaries around time, work expands to fill all available space.", "sections": [
            {"heading": "The Protected Time Principle", "body": ["Block time in your calendar for what matters — relationships, recovery, creative thinking, health — before work demands fill it. Not after. Before.", "This is not selfishness. It is resource management. You cannot produce excellent work in a life with no recovery time. You cannot maintain important relationships without protecting time for them. The calendar is a values document — make it reflect yours.", "Communicate limits professionally: 'I'm not available on evenings and weekends except in genuine emergencies' is a professional statement, not a personal one. Most organizations respect it. Some don't — and that is useful information about the organization."]},
        ], "callout": "The calendar reflects your values whether you design it that way or not."},
        {"title": "The Role of Meaning in Sustainability", "intro": "Work that is meaningless drains energy at a rate that no recovery practice can compensate for.", "sections": [
            {"heading": "Finding and Creating Meaning", "body": ["Research by Amy Wrzesniewski and Jane Dutton on 'job crafting' shows that people at all levels in all kinds of jobs can proactively redesign their work to be more meaningful — by adjusting which tasks they prioritize, how they relate to their work's impact, and the relationships they cultivate in their work context.", "The three sources of work meaning most consistently identified in research: craft (the intrinsic pleasure of doing something well), contribution (believing your work matters to something larger than yourself), and connection (genuine relationships with people you work with or serve).", "You don't need a perfect job to find meaning. You need a job in which these three dimensions are accessible in some form."]},
        ], "callout": "Meaning is not found. It's created — through craft, contribution, and connection."},
        {"title": "Technology Boundaries and Digital Wellbeing", "intro": "The smartphone made work-life integration harder by making work available at every moment.", "sections": [
            {"heading": "Managing the Always-On Default", "body": ["The default setting of modern professional life is constant availability. The research on this default is unambiguous: constant connectivity increases cortisol, reduces cognitive performance on complex tasks, degrades sleep quality, and undermines relationship quality.", "Specific boundaries with documented benefit: no work email/apps in the 60 minutes before bed and after waking, phone-free meals (especially with family), designated device-free periods during the day.", "The professional who sets these limits and communicates them clearly is not less committed to their work. They are more effective at it — and they model a sustainable way of working that high-performing teams increasingly need to function without burning out."]},
        ], "callout": "Constant availability is not professionalism. It's a failure of design."},
        {"title": "Designing a Life That Works", "intro": "Work-life integration is ultimately a design problem. You're the architect.", "sections": [
            {"heading": "The Design Principles", "body": ["Start with what matters: what do you most want your daily life to feel like? What must be present for you to feel that you lived well? Build the career and work structures around those answers — not the other way around.", "Iterate rather than optimize: don't try to design the perfect life arrangement once. Design a version that's better than today, test it for 90 days, assess honestly, and adjust.", "Give yourself permission to want different things at different life stages. The priorities of a 35-year-old parent with young children are legitimately different from those of a 50-year-old whose children are grown. Update your design accordingly.", "The life that works is the one that you consciously designed, that you can honestly say reflects your values, and that provides enough restoration that you can sustain it for decades rather than just months."]},
        ], "callout": "You are the architect of your own life. Design it deliberately."},
    ]
}

books = [b1, b2, b3, b4, b5, b6, b7, b8, b9, b10]
filenames = [
    "01 - Burned Out and Starting Over.pdf",
    "02 - The Introverted Professional.pdf",
    "03 - Negotiating at Every Career Stage.pdf",
    "04 - Remote Work Mastery.pdf",
    "05 - The Career in Your 40s.pdf",
    "06 - Building a Personal Brand That Actually Works.pdf",
    "07 - Difficult Conversations at Work.pdf",
    "08 - Leadership Without Authority.pdf",
    "09 - The Consultant Mindset.pdf",
    "10 - Work-Life Integration.pdf",
]

for book, fname in zip(books, filenames):
    generate_ebook(os.path.join(OUT, fname), book)

print("SERIES 8 DONE")
