import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from generate_ebook import generate_ebook

OUT = os.path.dirname(__file__)
ACCENT = "#16A085"
BG = "#F0FFFE"
SERIES = "The Calm Parent Series"

DISCLAIMER = """This book is intended for educational and informational purposes only. Parenting involves highly individual circumstances, and what works for one child and family may not work for another.

Nothing in this book constitutes medical, psychological, or professional parenting advice. For children with diagnosed developmental, behavioral, or mental health conditions, please consult qualified professionals.

The author and publisher do not claim any specific parenting outcomes from the practices described. Always trust your knowledge of your own child and consult professionals when in doubt."""

# ── Book 1 ────────────────────────────────────────────────────────────────────
b1 = {
    "title": "The Regulated Parent",
    "subtitle": "How Your Nervous System Shapes Your Child's",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Your Nervous System Is Your Child's Classroom", "intro": "Before you teach your child anything, your nervous system is already teaching theirs.", "sections": [
            {"heading": "The Co-Regulation Research", "body": ["Decades of developmental neuroscience, from Allan Schore's work on right-brain development to Daniel Siegel's interpersonal neurobiology, converge on a fundamental truth: children's nervous systems regulate through connection with their caregivers' nervous systems. Before children can self-regulate, they need to co-regulate — borrowing the parent's calm state to organize their own.", "When a child is distressed, the most effective intervention is a calm, present parent. Not because calm commands calm, but because the connected nervous system literally transmits regulatory signals through eye contact, tone of voice, touch, and proximity.", "The implication is uncomfortable and important: you cannot consistently give your child nervous system regulation that you don't have yourself."]},
            {"heading": "The Trigger Behind the Trigger", "body": ["Most parental overreactions — the disproportionate yelling, the outsized frustration, the moment you said something you immediately regretted — are not about what the child just did. They are about what the child's behavior activated in the parent's own nervous system history.", "The child who won't listen activates the parent who never felt heard. The child's tantrum activates the parent who wasn't allowed to have feelings. The child's demands activate the parent who learned that being needed is a burden.", "Understanding this is not self-blame. It's the beginning of a different kind of parenting."]},
        ], "callout": "You can't pour regulation from an empty nervous system."},
        {"title": "Identifying Your Triggers", "intro": "You cannot interrupt what you haven't identified.", "sections": [
            {"heading": "The Trigger Mapping Exercise", "body": ["Write down the last five times you reacted to your child in a way you later regretted. For each: what specifically happened? What did you feel in your body just before you reacted? What does this remind you of from your own childhood?", "The patterns that emerge are your personal trigger map. They are not character indictments. They are the places where your nervous system learned to respond with alarm — and which your child's behavior is now inadvertently activating.", "Knowing your triggers doesn't eliminate them. But it creates the millisecond of recognition that allows choice rather than just reaction."]},
        ], "callout": "Your triggers are old wounds in parenting clothes."},
        {"title": "The Parental Pause", "intro": "The single most useful parenting intervention exists in the moment between trigger and response.", "sections": [
            {"heading": "Building the Pause", "body": ["The pause is the gap between what your child does and what you do. It can be as brief as two breaths — long enough to shift from reactive to responsive.", "Physical signals that you need a pause: jaw tightening, shoulders rising, voice getting louder, brain going narrow. These are the body's preparation-for-attack signals — useful for tigers, not for parenting.", "In the pause: take two slow breaths. Ask: 'What does my child need right now?' Not what they deserve, not what will teach them a lesson — what do they need? The answer to that question is almost always different from what reactive parenting delivers."]},
        ], "callout": "Two breaths between trigger and response can change everything."},
        {"title": "Repair: The Most Underused Parenting Tool", "intro": "You will lose your patience. You will say something you regret. How you repair is more important than whether you were perfect.", "sections": [
            {"heading": "Why Repair Matters So Much", "body": ["Research on parent-child interaction quality shows that the rupture-repair cycle — the pattern of disrupted connection followed by intentional reconnection — is actually central to secure attachment development. Children don't need perfect parents. They need parents who repair.", "A genuine repair with a child teaches multiple things simultaneously: that relationships survive mistakes, that adults can take accountability, that the child's feelings about the incident matter, and that the connection is more important than the conflict.", "A parental repair: 'I lost my temper earlier and said things I shouldn't have. That wasn't okay. I'm sorry. You didn't deserve that.'"]},
        ], "callout": "Repair is not weakness. It's modeling the most important relationship skill."},
        {"title": "Your Own Needs Are Not Optional", "intro": "The oxygen mask principle is not a metaphor. It's a parenting strategy.", "sections": [
            {"heading": "Meeting Your Needs Without Guilt", "body": ["The parent who never rests, never plays, never has time for their own needs, never experiences genuine restoration — this parent cannot sustain genuine presence with their children.", "Meeting your own needs is not selfishness. It is the maintenance of the primary resource your children require. A depleted parent provides depleted parenting. An occasionally rested, genuinely-tended-to parent shows up differently.", "Identify one daily practice that genuinely restores you — and protect it. Not as a reward when everything else is done. As an infrastructure requirement for the kind of parent you want to be."]},
        ], "callout": "Your needs matter because your children need you whole."},
        {"title": "Intergenerational Patterns and Breaking Them", "intro": "The most powerful parenting gift you can give your children might be the work you do on yourself.", "sections": [
            {"heading": "Breaking the Chain", "body": ["Research by Mary Main and others shows that the strongest predictor of a child's attachment security is not what the parent experienced in their own childhood, but whether the parent has made sense of what they experienced.", "You do not have to have had a perfect childhood to parent well. You have to have reflected on your childhood, understood its impact, and developed an honest narrative about it — including its hard parts.", "This work is not always comfortable. It is some of the most important parenting work available. Personal therapy, reflective journaling, and honest conversations with partners about childhood experiences all contribute to the narrative processing that secures the next generation."]},
        ], "callout": "Breaking intergenerational patterns doesn't require a perfect past. It requires an honest one."},
    ]
}

# ── Book 2 ────────────────────────────────────────────────────────────────────
b2 = {
    "title": "Raising Emotionally Intelligent Kids",
    "subtitle": "How to Teach Feelings Before They Become Problems",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Emotion Coaching: The Research", "intro": "John Gottman's research on emotion coaching produced one of the most actionable findings in parenting science.", "sections": [
            {"heading": "The Findings", "body": ["Gottman's longitudinal research on family emotion dynamics found that children whose parents practiced 'emotion coaching' — recognizing emotional moments as opportunities for connection and teaching — had dramatically better outcomes: higher academic performance, fewer behavioral problems, stronger friendships, and better physical health over time.", "Emotion-coached children weren't children who felt only positive emotions. They were children who had learned that all emotions are valid information, that they can be experienced and expressed without catastrophe, and that trusted adults will help them navigate the complex ones."]},
        ], "callout": "Emotion coaching is the highest-ROI parenting practice available."},
        {"title": "The Five Steps of Emotion Coaching", "intro": "Gottman's emotion coaching approach translates directly into specific parent behaviors.", "sections": [
            {"heading": "The Steps in Practice", "body": ["Step 1 — Become aware of your child's emotions: notice what they're feeling, even when they can't say it. Step 2 — Recognize the emotional moment as an opportunity: not a problem to solve or a crisis to contain, but a chance to connect. Step 3 — Listen empathetically: get down to their level, make eye contact, reflect back what you're observing ('It looks like you're feeling really frustrated'). Step 4 — Help your child name the feeling: expand their emotional vocabulary beyond 'sad' and 'mad.' Step 5 — Set limits while problem-solving: all feelings are okay; not all behaviors are. 'It makes sense that you're angry. Hitting is not okay. What else could you do when you feel that angry?'"]},
        ], "callout": "The emotion coaching framework works for kids because it works for humans."},
        {"title": "Building Emotional Vocabulary", "intro": "Children can only work with the emotions they can name.", "sections": [
            {"heading": "The Vocabulary Investment", "body": ["Research by Lisa Feldman Barrett shows that the more differentiated our emotional vocabulary, the better we regulate emotions — because we can identify what we're experiencing precisely enough to address it specifically.", "Building emotional vocabulary in children: use emotion words in daily conversation beyond 'happy,' 'sad,' 'angry,' and 'scared.' Introduce words like frustrated, disappointed, embarrassed, jealous, proud, anxious, lonely, content, curious. Read books with rich emotional content. Talk about characters' feelings.", "The investment pays dividends in adolescence — children with larger emotional vocabularies handle the intensely emotional adolescent period with more nuance and less crisis."]},
        ], "callout": "You can't manage what you can't name."},
        {"title": "Validating Feelings Without Validating Every Behavior", "intro": "The critical distinction: all feelings are okay; all behaviors are not.", "sections": [
            {"heading": "The Validation Formula", "body": ["Validation is not agreement. 'I understand why you're angry' does not mean 'you were right to hit your brother.' These are completely separate statements.", "Validation communicates: your feeling makes sense, you are not wrong for having it, I can understand your inner experience. Behavior limits communicate: this specific action is not acceptable and here is what is.", "Children who receive validation for their feelings are actually more responsive to behavioral limits — because the validation removes the defensive charge that makes children dig in."]},
        ], "callout": "Validate the feeling. Limit the behavior. Never confuse the two."},
        {"title": "When Your Child Won't Talk to You", "intro": "The goal of emotional attunement in early childhood is to maintain access to your child through adolescence.", "sections": [
            {"heading": "The Long Game", "body": ["Children who have experienced their parents as emotionally available — who have been met with curiosity rather than judgment when they bring difficult feelings — are significantly more likely to continue bringing difficult feelings as adolescents.", "The investment in emotion coaching in the early years is, in part, an investment in the relationship quality that will matter most when the stakes are high: when they're navigating peer pressure, relationship decisions, mental health challenges.", "The teen who goes to a parent instead of only to peers does so because they have evidence from years of experience that the parent can be a safe emotional landing place."]},
        ], "callout": "Early emotional attunement is an investment in adolescent access."},
        {"title": "Helping Kids With Anxiety", "intro": "Childhood anxiety is common, manageable, and significantly influenced by the parental response to it.", "sections": [
            {"heading": "The Parental Response That Helps vs. Hurts", "body": ["Accommodation — repeatedly removing anxiety-provoking situations to relieve the child's distress — provides short-term relief and long-term anxiety reinforcement. The anxious child needs gradual supported engagement with feared situations, not protection from them.", "Helpful responses: acknowledging the anxiety without amplifying it ('I can see this feels scary. You've handled scary things before'), coaching the child through anxiety rather than removing it, expressing confidence in the child's ability to cope ('You can do hard things').", "For significant childhood anxiety, CBT-based treatment (specifically, the SPACE program) has strong evidence for both the child and the parent component of treatment."]},
        ], "callout": "Help your child through anxiety, not around it."},
    ]
}

# ── Book 3 ────────────────────────────────────────────────────────────────────
b3 = {
    "title": "Screens, Social Media, and the Developing Brain",
    "subtitle": "What the Research Actually Says — and What to Do About It",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Research Is More Complicated Than the Headlines", "intro": "Screen time debates generate more heat than light. Here's what the evidence actually shows.", "sections": [
            {"heading": "The Nuanced Picture", "body": ["Not all screen time is equivalent. Video chatting with grandparents, interactive educational content, collaborative gaming with friends, and passive social media consumption have different impacts and shouldn't be grouped under a single 'screen time' label.", "The research showing harm from high social media use in adolescents — particularly girls — is substantial and growing. Jean Twenge and Jonathan Haidt's work identifies the period from approximately 2012 (smartphone ubiquity) onward as coinciding with dramatic increases in adolescent anxiety, depression, and loneliness, with social media use as a primary contributing factor.", "The research on under-5 screen exposure shows interference with language development when content replaces face-to-face interaction. Above age 5, the impact is far more context-dependent."]},
        ], "callout": "The research matters. So does the specifics of what your child is watching and why."},
        {"title": "The Social Media Adolescent Problem", "intro": "The evidence on social media and adolescent mental health is strong enough to warrant serious parent attention.", "sections": [
            {"heading": "What the Research Shows", "body": ["Haidt and Twenge's analysis across multiple datasets finds: heavy social media use (more than 2-3 hours per day) is associated with significantly higher rates of depression and anxiety in adolescents, particularly girls. The mechanisms include: social comparison on curated content, cyberbullying, sleep disruption, displacement of face-to-face interaction, and dopaminergic manipulation by engagement-maximizing algorithms.", "Delays in smartphone access correlate with better mental health outcomes. Multiple independent studies find that adolescents who receive smartphones later (age 16 vs. 12) have better wellbeing outcomes.", "This is not absolute — some adolescents use social media well, particularly for community-building around marginalized identities. But the average effect is clearly negative at high doses."]},
        ], "callout": "Later smartphone access correlates with better adolescent mental health outcomes."},
        {"title": "Having the Conversation With Your Child", "intro": "Screen and social media rules work better when they're explained than when they're imposed.", "sections": [
            {"heading": "The Transparency Approach", "body": ["Share the research with your child in age-appropriate terms. 'I want to share what I've been reading about social media and teenage brains, because I think you deserve to understand why I'm making certain decisions about this.'", "Children and adolescents who understand the reasoning behind limits are more likely to internalize them — and to make better self-regulatory decisions when parents aren't present.", "Include them in designing the rules where appropriate. 'Here's what I know about the research. Here are my concerns. What do you think would work for our family?'"]},
        ], "callout": "Transparency builds buy-in that mandates cannot."},
        {"title": "Practical Screen Frameworks for Different Ages", "intro": "Age-appropriate guidance for a genuinely difficult parenting challenge.", "sections": [
            {"heading": "The Age Breakdown", "body": ["Under 2: video calling with family yes; other screen use not recommended. 2-5: less than 1 hour per day of high-quality content with parent co-viewing where possible. 6-12: consistent limits, device-free meals and bedrooms, no social media. 12-15: limited social media access if any, open device monitoring, ongoing conversation about online experience. 16+: graduated autonomy with continued conversation, clear family agreements about overnight device locations.", "The bedroom-at-night rule has particularly strong evidence: devices charging outside the bedroom improve sleep quality and reduce total daily screen exposure simultaneously."]},
        ], "callout": "No devices in bedrooms at night. This rule has the clearest evidence base."},
        {"title": "Modeling the Relationship You Want Your Child to Have", "intro": "Children learn their relationship with screens primarily from watching yours.", "sections": [
            {"heading": "The Parent Modeling Question", "body": ["If you are on your phone during dinner, during conversations with your child, first thing in the morning and last thing at night — you are modeling the relationship with devices that you will later try to regulate in your child. With limited success.", "The conversations about screen use are more credible, and the rules are more sustainable, when they apply to the whole family. This requires parents to genuinely examine their own screen use — not just their children's."]},
        ], "callout": "Your relationship with your phone is the first screen education your child receives."},
        {"title": "When Screens Become a Mental Health Issue", "intro": "Some children and adolescents develop problematic relationships with gaming or social media that go beyond normal use.", "sections": [
            {"heading": "Recognizing the Line", "body": ["Indicators of problematic use: significant impairment in other life areas (school, relationships, sleep, physical health), continued use despite stated desire to cut back, using screens as the primary coping mechanism for all difficult emotions, significant distress when access is restricted.", "For gaming specifically: internet gaming disorder is a recognized condition with evidence-based treatments. CBT for internet gaming disorder has demonstrated effectiveness.", "Professional evaluation is appropriate when screen use is significantly impairing functioning and doesn't respond to family-level interventions."]},
        ], "callout": "When screens are the only coping tool, more is needed than a screen time rule."},
    ]
}

# ── Book 4 ────────────────────────────────────────────────────────────────────
b4 = {
    "title": "Discipline That Doesn't Break the Relationship",
    "subtitle": "Effective Boundaries Without Shame or Fear",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Discipline Actually Is", "intro": "The word 'discipline' comes from the Latin word for teaching. It is not synonymous with punishment.", "sections": [
            {"heading": "The Teaching Frame", "body": ["Most effective discipline is instruction in how to behave, not punishment for having behaved wrong. Children's brains are not fully equipped for self-regulation, impulse control, or perspective-taking until well into their 20s — because the prefrontal cortex isn't fully developed until then.", "When a child melts down, acts out, or makes a poor choice, the most useful frame is: what skill are they missing that this behavior is revealing? What do I need to teach — not punish — here?", "This doesn't eliminate consequences. It changes their purpose from retaliation to education."]},
        ], "callout": "Every behavioral problem is a missing skill waiting to be taught."},
        {"title": "The Authoritative Approach", "intro": "Decades of parenting research identify authoritative parenting — high warmth, high structure — as producing the best outcomes.", "sections": [
            {"heading": "The Research Consensus", "body": ["Diana Baumrind's foundational parenting style research, replicated across multiple cultures and decades, consistently finds that the combination of warmth and structure — authoritative parenting — produces children with better academic outcomes, fewer behavioral problems, higher self-esteem, and greater emotional competence than either strict authoritarian or permissive parenting.", "The key combination: clear expectations (I need you to do X), explained reasoning ('because Y'), natural consequences for not meeting them, and maintained relationship warmth throughout. All of these together, not just the first one."]},
        ], "callout": "Warmth without structure is permissive. Structure without warmth is authoritarian. Both work less well."},
        {"title": "Natural and Logical Consequences", "intro": "Consequences that are connected to the behavior teach. Consequences that aren't don't teach — they just punish.", "sections": [
            {"heading": "The Distinction", "body": ["Natural consequences: the natural result of the choice. You leave your bike in the rain; it gets rusty. You don't finish homework; you deal with the teacher. When natural consequences are safe and instructive, allowing them is valuable teaching.", "Logical consequences: connected to the behavior and reasonably proportionate. You don't clean your room; no friends over this weekend (your space, your choice about how it looks and who sees it). You break a toy in anger; it isn't replaced immediately.", "Unconnected consequences — 'you left your bike in the rain so no screen time this week' — teach only that adults have arbitrary power. They don't build the connection between choice and outcome that natural and logical consequences build."]},
        ], "callout": "Connected consequences teach. Arbitrary consequences only demonstrate power."},
        {"title": "Time-In Instead of Time-Out", "intro": "The research on time-out is more ambiguous than its widespread adoption suggests.", "sections": [
            {"heading": "What Works Better", "body": ["Traditional time-out sends a dysregulated child away from the adult who is the primary regulatory resource available to them. For some children, this works; for others, it amplifies dysregulation and shame.", "'Time-in' is an alternative: sit with the dysregulated child, regulate together, and address the behavior after regulation. 'I can see you're really upset. Let's take some breaths together. When you're ready, I want to talk about what happened.'", "The goal of any response to difficult behavior is: (1) restore regulation, (2) maintain the relationship, (3) address the behavior. The order matters."]},
        ], "callout": "Regulate, then connect, then correct."},
        {"title": "When Children Push Every Limit", "intro": "Some children are genuinely more challenging to parent. Understanding why makes the work more sustainable.", "sections": [
            {"heading": "Temperament and Fit", "body": ["Research on temperament identifies some children as constitutionally more intense, more persistent, more sensitive, or more active — traits that are heritable and not produced by parenting failures. These children require more skilled, more patient, more creative parenting than temperamentally easy children.", "Parent-child temperamental fit matters: a high-intensity child with a high-intensity parent can be a particularly challenging combination. Understanding where the friction comes from reduces the personalization of it.", "Ross Greene's Collaborative Problem Solving approach — treating behavioral challenges as lagging skills to be solved collaboratively with the child — has strong evidence for children who are particularly difficult to parent through conventional approaches."]},
        ], "callout": "Challenging children are not badly parented children. They're children who need more skilled parenting."},
        {"title": "Consistency, Predictability, and Why They Matter", "intro": "The most important thing about consequences and rules is not their severity. It's their consistency.", "sections": [
            {"heading": "The Predictability Principle", "body": ["Children's nervous systems need predictability to develop secure functioning. When consequences are inconsistent — sometimes enforced, sometimes not; sometimes severe, sometimes ignored — children develop heightened vigilance that is exhausting and behaviorally dysregulating.", "The rule that is enforced calmly and consistently every time trains the behavior. The rule that is enforced when you're in a bad mood and ignored when you're tired trains nothing except anxiety about your mood.", "This is one of the hardest things in parenting: consistency across exhaustion, illness, bad days, and competing demands. No parent achieves it perfectly. But the aspiration toward consistency is worth holding."]},
        ], "callout": "Consistency matters more than severity. Every time beats sometimes, every time."},
    ]
}

# ── Book 5 ────────────────────────────────────────────────────────────────────
b5 = {
    "title": "Raising Kids Who Can Fail",
    "subtitle": "Building Resilience in a World That Makes It Too Easy to Avoid Hard Things",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Helicopter Parent Problem", "intro": "The generation of parents most committed to their children's wellbeing is producing the generation with the least resilience. The connection is not coincidental.", "sections": [
            {"heading": "The Research on Overprotection", "body": ["Jonathan Haidt and Greg Lukianoff's work, along with developmental psychologist Wendy Grolnick's research on parental control, finds consistent evidence: children who are over-scaffolded — whose parents consistently intervene before difficulty, remove obstacles before they're encountered, and prevent failure — develop lower tolerance for frustration, reduced problem-solving ability, and impaired capacity for autonomous functioning.", "This is not an argument for parental indifference. The protective instincts driving helicopter parenting are entirely loving. The problem is that protection from difficulty prevents the difficulty-mediated development that produces resilience."]},
        ], "callout": "Children develop resilience through difficulty, not through its absence."},
        {"title": "The Appropriate Challenge", "intro": "Not all difficulty is beneficial. The productive zone requires calibration.", "sections": [
            {"heading": "Finding the Edge", "body": ["Psychologist Lev Vygotsky's concept of the zone of proximal development is useful here: learning and growth happen in the zone that is just beyond current capacity but not so far beyond it that the child is overwhelmed. Too easy produces boredom; too hard produces shutdown; the edge produces growth.", "This applies to emotional as well as intellectual challenges. A child who is allowed to experience age-appropriate frustration, disappointment, boredom, and conflict — in a context where support is available but rescue is not automatic — develops the neural architecture for regulation, problem-solving, and recovery."]},
        ], "callout": "The productive challenge is one step beyond current capacity — with support available but not automatic."},
        {"title": "The Growth Mindset and How to Actually Build It", "intro": "Carol Dweck's research on growth mindset has been widely popularized and widely misapplied.", "sections": [
            {"heading": "What Growth Mindset Actually Requires", "body": ["Dweck's research shows that children praised for effort ('you worked really hard at that') develop more resilient learning approaches than children praised for ability ('you're so smart'). Ability praise, when things get hard, produces the belief that difficulty means you're not actually smart — leading to avoidance.", "But growth mindset isn't just about praise language. It's about modeling genuine engagement with difficulty, talking about mistakes and what you learned from them, celebrating process alongside outcome, and treating failure as information rather than verdict.", "The parent who says 'what matters is trying' but visibly panics when their child fails is teaching growth mindset words and a fixed mindset."]},
        ], "callout": "Growth mindset requires modeling, not just language."},
        {"title": "Boredom as a Gift", "intro": "Boredom has become something parents are expected to solve. It is actually something children need to tolerate.", "sections": [
            {"heading": "Why Boredom Matters", "body": ["Boredom is the state from which self-generated play, creativity, and internal motivation emerge. Children who are never allowed to be bored — whose schedules are filled, whose devices are always available — lose the capacity to generate their own engagement.", "Tolerating boredom is a skill that requires practice. It feels uncomfortable before it becomes creative. The parent who immediately resolves children's boredom is preventing the uncomfortable incubation that precedes imagination.", "Age-appropriate unstructured time — specifically without screens — is one of the most developmentally valuable things you can give your child. Not despite the complaint, but through the complaint."]},
        ], "callout": "Boredom is not a problem to solve. It's a state to tolerate until creativity emerges."},
        {"title": "Failure Recovery as a Teachable Moment", "intro": "The quality of the failure recovery is where resilience is built.", "sections": [
            {"heading": "The Failure Conversation", "body": ["After a genuine failure — academic, social, athletic — the most valuable parent response: sit with the disappointment first (don't rush to silver linings), acknowledge what actually happened, then move to curious inquiry: 'What do you think went wrong? What would you do differently? What's one thing you could try?'", "The parent who can tolerate their child's disappointment without fixing it immediately is teaching emotional resilience. The parent who needs the child to feel better immediately is managing their own discomfort, not building the child's capacity."]},
        ], "callout": "Tolerate your child's disappointment. It's where resilience grows."},
        {"title": "The Responsible Risk", "intro": "Risk is not the enemy of safety. Appropriate risk is the development of it.", "sections": [
            {"heading": "Risky Play and Its Benefits", "body": ["Research on risky play — climbing trees, rough-and-tumble play, building sites, fire, heights — finds that children who engage in age-appropriate physical risk develop better physical coordination, risk assessment skills, and emotional regulation than those whose physical experiences are consistently sanitized.", "The playground equipment that got progressively safer over the past 30 years coincides with rising childhood injury rates in other contexts — children who never learned to assess their own physical limits have worse injury outcomes in novel situations.", "This is not an argument for recklessness. It's an argument for calibrated risk — experience with appropriate challenge, in contexts where the consequence of failure is survivable."]},
        ], "callout": "Risk teaches risk assessment. Sheltering teaches neither."},
    ]
}

# ── Book 6 ────────────────────────────────────────────────────────────────────
b6 = {
    "title": "Parenting the Anxious Child",
    "subtitle": "Calm Strategies for the Child Who Worries Too Much",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Anxiety in Children Is Common and Treatable", "intro": "Anxiety disorders are the most common childhood mental health condition. They also have some of the most effective treatments.", "sections": [{"heading": "The Prevalence and the Path", "body": ["Approximately 10-20% of children and adolescents experience clinically significant anxiety at some point in development. Left untreated, childhood anxiety strongly predicts adult anxiety, depression, and substance use problems. Treated effectively, children with anxiety develop resilience that serves them throughout their lives.", "The evidence-based treatment for childhood anxiety is CBT-based exposure — a graduated process of engaging with feared situations with support, rather than avoiding them. This approach has strong evidence, produces lasting results, and is the standard recommendation."]}], "callout": "Childhood anxiety responds extremely well to the right treatment."},
        {"title": "The Parent's Role in Anxiety Treatment", "intro": "Parents are the most powerful factor in whether childhood anxiety improves or worsens.", "sections": [{"heading": "Accommodation vs. Support", "body": ["The most common parental response to an anxious child — removing the feared situation, reassuring extensively, accommodating avoidance — is driven by love and makes anxiety worse. Accommodation reinforces the message that the feared situation is dangerous and the child cannot cope.", "The SPACE program (Supportive Parenting for Anxious Childhood Emotions), developed at Yale, addresses parental accommodation directly and has demonstrated that treating parents' accommodating behavior produces significant improvement in childhood anxiety — sometimes without treating the child directly."]}], "callout": "Reducing accommodation is one of the most powerful things a parent can do for an anxious child."},
        {"title": "The Anxious Child at School", "intro": "School is often both the primary anxiety trigger and the primary avoidance target for anxious children.", "sections": [{"heading": "School Refusal", "body": ["School refusal — refusing to attend or having significant difficulty attending school due to emotional distress — is one of the most challenging presentations of childhood anxiety, requiring coordinated approach between parents, school, and mental health providers.", "The principle is consistent with anxiety treatment generally: graduated reengagement, not prolonged avoidance. Extended absence from school reinforces anxiety and creates additional social and academic deficits that compound the original problem."]}], "callout": "School refusal requires early, consistent intervention. Avoidance makes it worse."},
        {"title": "What Anxious Kids Need to Hear", "intro": "The words matter as much as the actions.", "sections": [{"heading": "Helpful vs. Unhelpful Responses", "body": ["Unhelpful: 'Don't worry' (dismisses), 'Nothing is going to happen' (promises you can't keep), 'That's silly to be scared of' (shames).", "Helpful: 'I can see this feels really scary for you' (validates), 'I know you can handle this' (communicates confidence), 'Let's take a breath together' (co-regulates), 'You've done hard things before' (builds on evidence of coping)."]}], "callout": "Validation and confidence communicate: your feeling is real AND you can handle it."},
        {"title": "Handling Reassurance Seeking", "intro": "Excessive reassurance seeking is both a symptom of anxiety and a maintaining factor.", "sections": [{"heading": "Breaking the Reassurance Loop", "body": ["Reassurance provides momentary relief and long-term reinforcement of the anxiety. Each reassurance confirms that the danger required managing and that the child couldn't tolerate the uncertainty without help.", "Gradual reassurance fading — reducing the amount and frequency of reassurance given while maintaining warmth — is part of effective anxiety treatment. This requires consultation with a professional to implement well, as it can temporarily increase distress before decreasing it."]}], "callout": "Less reassurance, maintained warmth — the counterintuitive path to less anxious children."},
        {"title": "When to Get Professional Help", "intro": "Some anxiety is beyond parent management alone.", "sections": [{"heading": "The Indicators", "body": ["Seek professional evaluation when: anxiety is significantly impairing functioning in more than one area (school, friendships, family), it has been persistent for more than a few months, the child is experiencing physical symptoms (stomach aches, headaches, sleep disturbance), or parental management strategies are not producing improvement.", "Evidence-based treatment (CBT-based exposure) delivered by a trained child therapist has the best outcomes. Look specifically for therapists trained in exposure-based treatment, not just general talk therapy for childhood anxiety."]}], "callout": "When anxiety impairs function in multiple areas, professional support is not optional."},
    ]
}

# ── Books 7-10 ────────────────────────────────────────────────────────────────
b7 = {
    "title": "Talking to Kids About Hard Topics",
    "subtitle": "Death, Divorce, Race, Sex, and Everything Else You've Been Avoiding",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG, "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Why Parents Avoid Hard Conversations", "intro": "Avoidance is not protection. It's information curation with unintended consequences.", "sections": [{"heading": "The Cost of Silence", "body": ["Children who don't receive honest, age-appropriate information from parents about difficult topics don't remain uninformed — they gather information from peers, media, and imagination, which is frequently less accurate, less nuanced, and less compassionate than what a thoughtful parent would provide.", "The relationship built through hard conversations is one of the most valuable things you can give your child. The parent who can be approached about anything provides a safety net that has genuine life-altering consequences in adolescence."]}], "callout": "Your silence doesn't protect your child. It just controls who they talk to instead."},
        {"title": "Death and Loss", "intro": "Children encounter death, often early. How they're helped to understand and grieve it shapes their relationship with loss for life.", "sections": [{"heading": "Honest, Age-Appropriate Conversations", "body": ["Use actual language: 'died' rather than 'passed away' or 'went to sleep.' Euphemisms confuse young children and create anxiety about sleep or travel.", "Allow children to grieve in their way, which often includes play and apparent normalcy between episodes of sadness. Children's grief is not linear.", "Include children in age-appropriate aspects of mourning. Exclusion from rituals to 'protect' them often produces more distress than inclusion."]}], "callout": "Children handle death better with honest information and inclusion than with protection."},
        {"title": "Divorce and Family Change", "intro": "How parents handle separation shapes children's experience of it far more than the separation itself.", "sections": [{"heading": "What Children Need to Know and Not Know", "body": ["Children need to know: this is not their fault (stated explicitly and repeatedly), both parents still love them, their life will continue in recognizable ways, and they will be taken care of.", "Children do not need to know: the details of the relationship's failure, one parent's grievances against the other, financial details that create anxiety, or information that puts them in a loyalty bind."]}], "callout": "Children's wellbeing after divorce is primarily determined by the co-parenting relationship."},
        {"title": "Race, Identity, and Belonging", "intro": "Race-related conversations are necessary in all families — and are conducted very differently across family demographics.", "sections": [{"heading": "The Research Across Racial Groups", "body": ["Research is clear that 'color-blind' approaches — 'I don't see race,' 'we're all the same' — do not protect children from encountering racial bias. They remove information that children of color specifically need to navigate a world that does see race.", "For white families: racial socialization includes helping children see racial inequity, understand their own racial position, and develop anti-racist values. For families of color: racial socialization includes both pride in cultural heritage and preparation for racial bias — both protect children's wellbeing."]}], "callout": "Color-blindness is not neutrality. It's an abdication."},
        {"title": "Sex and Relationships Education", "intro": "Parents who don't talk about sex and relationships cede that education to their children's peers and pornography.", "sections": [{"heading": "The Ongoing Conversation", "body": ["Sex education from parents is most effective when it's ongoing and age-appropriate from early childhood — not a single 'talk' at adolescence. Toddlers learn correct anatomical names. Elementary-age children learn about body autonomy and consent. Pre-teens learn about puberty and relationships. Teenagers receive frank information about sex, contraception, healthy relationships.", "The research is clear: children whose parents have open conversations about sex delay sexual debut, have fewer partners, use contraception more consistently, and report healthier relationship attitudes."]}], "callout": "The ongoing conversation always beats the single 'talk.'"},
        {"title": "Mental Health Conversations", "intro": "Children need a framework for understanding their mental health before they need it as a crisis resource.", "sections": [{"heading": "Building the Framework Early", "body": ["Talk about mental health as part of overall health: 'just like some people need glasses for their eyes, some people need extra support for their brain and feelings.' Normalize help-seeking as a sign of strength, not weakness.", "When children show signs of struggling — sustained mood change, social withdrawal, school decline, sleep changes — name it: 'I've noticed you seem sad lately. Can you tell me about it?' Don't wait for them to come to you."]}], "callout": "Mental health literacy is a protective factor. Build it early."},
    ]
}

b8 = {
    "title": "The Teenage Brain",
    "subtitle": "Understanding Adolescence So You Can Actually Survive It",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG, "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Is Actually Happening in the Teenage Brain", "intro": "Adolescent behavior that looks irrational often makes complete sense given the neuroscience.", "sections": [{"heading": "The Developmental Picture", "body": ["The prefrontal cortex — the brain region responsible for planning, impulse control, risk assessment, and understanding long-term consequences — is not fully developed until the mid-20s. Adolescents are making decisions with an immature prefrontal cortex, which explains impulsivity, poor risk assessment, and the apparent inability to apply consequences to future planning.", "Simultaneously, the reward circuits are in overdrive: dopamine sensitivity peaks in adolescence, making rewards more rewarding, peers more important than at any other life stage, and risk-taking more compelling.", "This is not defect — it's design. The adolescent brain is optimized for independence-seeking, peer bonding, and exploration of identity."]}], "callout": "The adolescent isn't trying to drive you crazy. Their brain is doing exactly what brains do at this stage."},
        {"title": "Identity Formation: What Your Teenager Actually Needs", "intro": "Adolescence is the developmental period for identity formation. The process requires both autonomy and connection.", "sections": [{"heading": "The Dual Task", "body": ["Erik Erikson described adolescence as the stage of identity versus role confusion. The developmental task is to explore and commit to an identity — including values, relationships, vocation, and worldview — that is genuinely the adolescent's own rather than a copy of the parents'.", "This is why adolescents push away from parents. Not because they don't love them, but because differentiation — the development of a separate self — requires psychological distance from the primary attachment figures.", "The parent who can tolerate this pulling-away while keeping the door open produces a teenager who often pulls back toward the relationship when the identity work is sufficiently done."]}], "callout": "Pulling away is developmental. Keep the door open."},
        {"title": "Keeping the Connection Through Conflict", "intro": "Parent-adolescent conflict is developmentally normal. The relationship quality through conflict determines whether you have access when it matters.", "sections": [{"heading": "The Connection Strategy", "body": ["Stay interested in what interests them. Ask about their world without interrogating. Show up for things that matter to them even when they don't match your interests. Maintain rituals of connection that are low-stakes (the drive to school, family dinner, a shared TV show).", "Pick your battles with genuine discernment. The adolescent who is fought over everything develops no ability to distinguish between the parent's important concerns and the parent's preferences. Reserve the real conflicts for the real risks."]}], "callout": "Maintained connection through minor conflict is access capital for major crises."},
        {"title": "Risk-Taking and How to Address It", "intro": "Some adolescent risk-taking is normal. Some is genuinely dangerous. The response depends on which.", "sections": [{"heading": "The Calibration", "body": ["Normal adolescent risk: experimenting with identity (fashion, music, peer groups), some rule-testing, minor boundary violations. Respond with clear communication of values and expectations, not catastrophe.", "Concerning risk: substance use beyond occasional experimentation, significant self-harm, unsafe sexual behavior, severe risk-taking. Respond with professional involvement, maintained relationship, clear communication about concern.", "The most valuable asset in a teenager's risk navigation: knowing they can come to a parent with a crisis without the relationship being destroyed by the disclosure."]}], "callout": "The teenager who knows you can handle the truth will tell you the truth."},
        {"title": "Mental Health in Adolescence", "intro": "Adolescence is the developmental period when most mental health conditions first emerge.", "sections": [{"heading": "Early Recognition and Response", "body": ["Depression, anxiety disorders, eating disorders, early psychosis, and substance use disorders all most commonly emerge in adolescence. Early identification and treatment produces dramatically better long-term outcomes than delayed intervention.", "Warning signs that warrant professional evaluation: persistent mood change lasting more than two weeks, significant social withdrawal, dramatic changes in eating or sleeping, self-harm, suicidal ideation, or psychotic symptoms (hearing things, paranoia).", "Mental health support for adolescents works. Sustained avoidance of treatment for serious adolescent mental health conditions produces worse adult outcomes."]}], "callout": "Early intervention for adolescent mental health problems is one of the highest-ROI investments in your child's life."},
        {"title": "The Launch Preparation", "intro": "The ultimate goal of parenting is to produce a functional adult who doesn't need you to function.", "sections": [{"heading": "Preparing for Independence", "body": ["Adolescence is the scaffolded runway to independence. Gradually and progressively extending autonomy — with increased responsibility attached — is how parents prepare teenagers for adult life.", "By 18, ideally: they can cook simple meals, manage basic finances, navigate basic healthcare, handle conflict directly, ask for help when they need it, and be alone without crisis. These are skills that require practice, not just information.", "The launched adult who calls because they want to, not because they need to, is the signal that the parenting project succeeded."]}], "callout": "Independence is the goal. Prepare your child for it deliberately."},
    ]
}

b9 = {
    "title": "Single Parenting With Intention",
    "subtitle": "Raising Children Well When You're the Only Parent in the Room",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG, "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Single Parent's Unique Challenge", "intro": "Single parenting is genuinely harder than partnered parenting. Acknowledging that is not complaint — it's the honest starting point.", "sections": [{"heading": "The Reality", "body": ["Single parents do the emotional, logistical, financial, and practical work of two-parent households with one person's time, energy, and income. The physical and emotional depletion this produces is real and has real consequences for parenting quality — not because single parents love their children less, but because sustained depletion affects everyone's capacity to be present and regulated."]}], "callout": "Single parenting is harder. It's also doable. Both things are true."},
        {"title": "Building Your Village", "intro": "Humans were not designed to raise children in nuclear family isolation. Building community is not weakness — it's wisdom.", "sections": [{"heading": "The Support Architecture", "body": ["Identify and explicitly ask for help from: family, close friends, neighbors, faith communities, parent groups, school communities. Most people who would help are waiting to be asked.", "Reciprocal arrangements with other parents (you take mine on Tuesday, I take yours on Thursday) build community while solving practical problems.", "Professional support — therapy for the parent — is not a luxury for single parents. It is infrastructure."]}], "callout": "Asking for help is the most practical thing you can do for your children."},
        {"title": "The Co-Parenting Relationship", "intro": "For divorced or separated parents, the co-parenting relationship is one of the most significant factors in children's outcomes.", "sections": [{"heading": "The Parallel Parenting Option", "body": ["Cooperative co-parenting — where parents communicate openly and flexibly — is ideal for children. It requires both parents to be willing and relatively functional in their communication.", "Parallel parenting — where parents disengage from each other and parent independently during their respective time — is the appropriate structure when the co-parenting relationship is high-conflict. Reducing contact between the parents reduces the children's exposure to conflict.", "Children need both parents to speak respectfully about the other parent. The parent who weaponizes the child against the other parent causes direct psychological harm."]}], "callout": "Your children's wellbeing requires you to manage your feelings about their other parent."},
        {"title": "Managing Your Own Wellbeing", "intro": "Your wellbeing is the most important factor in your children's wellbeing. Not the only one — but the most important one.", "sections": [{"heading": "The Non-Negotiable Self-Care", "body": ["Sleep: inadequate sleep impairs every parenting capacity. Sleep when the children sleep if necessary. Ask for coverage if that's what it takes. No parenting function is unaffected by severe sleep deprivation.", "Social connection: isolation is one of the most common and damaging experiences of single parenting. Maintaining adult friendships is not an indulgence — it is maintenance of the emotional resource your children need.", "Mental health support: therapy for single parents, particularly those managing trauma from the circumstances that produced single parenthood, has demonstrable benefits for children."]}], "callout": "Your overhead of self-care is parenting infrastructure."},
        {"title": "Money Management as a Single Parent", "intro": "Financial stress is both more common in single-parent households and more directly harmful to children's development.", "sections": [{"heading": "Financial Priority and Support", "body": ["Child support and government assistance programs exist specifically because society has recognized the disproportionate financial burden of single parenting. Use them. They are not charity — they are resources to which you and your children are entitled.", "Financial education for children from single-parent households can be genuinely useful: age-appropriate transparency about finances ('this is how much we have each month and this is how we decide what to spend it on') produces financially literate children without burdening them with adult anxiety."]}], "callout": "Use every resource available. That is good parenting, not defeat."},
        {"title": "What Single Parenting Can Teach", "intro": "Single-parent families produce competent, empathetic, resourceful children when they're parented with intention.", "sections": [{"heading": "The Gifts", "body": ["Children from well-functioning single-parent homes often develop unusual competence: they learn to be more autonomous earlier, they develop practical skills sooner, they often have stronger relationships with the single parent than children in two-parent households where one parent is largely absent.", "They also often develop deep empathy — they've seen a parent manage difficulty, love them anyway, ask for help, and keep going. That modeling is profound.", "You don't need to be two parents. You need to be a present, regulated, loving one."]}], "callout": "One fully present parent is profoundly sufficient."},
    ]
}

b10 = {
    "title": "Mindful Parenting",
    "subtitle": "How to Be Present With Your Children in a World Designed to Pull You Away",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG, "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Presence Actually Means", "intro": "Being in the room is not the same as being present. Your children know the difference.", "sections": [{"heading": "The Quality of Attention", "body": ["Research by developmental psychologist Ed Tronick, particularly his Still Face Experiment, demonstrates with heartbreaking clarity that even brief parental emotional unavailability produces distress, escalation, and behavioral disorganization in infants and young children.", "Your children are not measuring the hours you spend with them. They are measuring the quality of your attention within those hours. Twenty minutes of genuine, phone-free, fully present connection is more developmentally valuable than two hours of physical proximity with split attention."]}], "callout": "Quality of attention matters more than quantity of time."},
        {"title": "Mindfulness for Parents: The Practice", "intro": "Mindfulness as a parenting practice is not about perfection. It's about noticing when you've drifted and returning.", "sections": [{"heading": "The Five-Breath Practice", "body": ["Before entering your home at the end of a work day, sit in the car for three to five slow breaths. Intention-set: 'I am transitioning from work to family. The problems of work are on pause. My children deserve my presence.'", "When you notice you've mentally drifted during interaction with your child (reviewing your to-do list while they tell you about school), gently return. Just notice and return. There's no penalty for having drifted. The practice is in the noticing and returning."]}], "callout": "Mindfulness in parenting is noticing that you've drifted and coming back. That's it."},
        {"title": "The Phone as Presence Thief", "intro": "Every time you choose the phone over your child, your child receives a message about their importance.", "sections": [{"heading": "The Specific Practices That Help", "body": ["Define phone-free zones: all meals, all transitions (first 20 minutes after school or work), all bedtimes. Not because phones are evil but because these are high-value connection windows that deserve protection.", "Communicate the choice explicitly when you do choose the phone: 'I need to check this quickly and then I'm all yours' is better than silent availability that your child competes with.", "Model the relationship with technology you want your children to have. This is the single most important media education you can provide."]}], "callout": "The dinner table is a sacred space. Protect it."},
        {"title": "Rituals and the Architecture of Connection", "intro": "Small daily rituals create the steady texture of connection that children carry into adulthood.", "sections": [{"heading": "The Underrated Power of Small Rituals", "body": ["The goodnight conversation that happened every night for fifteen years. The Saturday morning breakfast that was just yours and theirs. The ten-minute drive that always turned into real talk. These accumulate into the foundation of relationship.", "You don't need to plan grand experiences. You need to show up consistently for small ones — and then be fully present while you're there.", "Rituals survive the turbulence of difficult developmental stages because they are predictable. The teenager who argues with everything still expects the Saturday morning pancakes — and still gets something from them."]}], "callout": "Small consistent rituals outlast any single grand experience."},
        {"title": "Forgiving Yourself for the Imperfect Days", "intro": "Guilt about parenting failures produces worse parenting, not better.", "sections": [{"heading": "The Self-Compassion Argument for Parents", "body": ["Parents who can apply self-compassion after a bad parenting moment — 'I lost my patience and that wasn't okay; I'll repair it and do better' — recover and repair more quickly than parents who spiral into shame.", "Shame produces: defensiveness (it wasn't really that bad), avoidance (I can't face my child after that), and rigidity (I have to be perfect from now on to make up for it). None of these help your children.", "The parent who can say 'I got that wrong and I'm sorry' — genuinely, specifically, without excessive self-flagellation — is modeling emotional accountability that will serve their child for life."]}], "callout": "The good-enough parent who repairs is better than the perfect parent no child has ever had."},
        {"title": "The Long View on Parenting", "intro": "You will not remember most of this. Neither will they. What will last is how they felt.", "sections": [{"heading": "The Deposit That Matters", "body": ["Daniel Kahneman's distinction between experiencing self and remembering self suggests that most of daily parenting experience is not explicitly remembered — but it is felt, and it deposits into the implicit relational knowledge that children carry into their adult lives and their own parenting.", "What your children will carry: the felt sense of whether they were fundamentally welcome in the world, whether they could bring their full selves to the relationship with you, whether they were loved consistently rather than conditionally, whether the world was fundamentally safe.", "You don't have to be perfect. You have to be enough, consistently enough, with enough repair when you fall short. That is genuinely within reach."]}], "callout": "Children don't remember most of their childhood. They feel it. Make the feeling worth having."},
    ]
}

books = [b1, b2, b3, b4, b5, b6, b7, b8, b9, b10]
filenames = [
    "01 - The Regulated Parent.pdf",
    "02 - Raising Emotionally Intelligent Kids.pdf",
    "03 - Screens Social Media and the Developing Brain.pdf",
    "04 - Discipline That Doesn't Break the Relationship.pdf",
    "05 - Raising Kids Who Can Fail.pdf",
    "06 - Parenting the Anxious Child.pdf",
    "07 - Talking to Kids About Hard Topics.pdf",
    "08 - The Teenage Brain.pdf",
    "09 - Single Parenting With Intention.pdf",
    "10 - Mindful Parenting.pdf",
]

for book, fname in zip(books, filenames):
    generate_ebook(os.path.join(OUT, fname), book)

print("SERIES 10 DONE")
print("ALL 100 EBOOKS COMPLETE")
