import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from generate_ebook import generate_ebook

OUT = os.path.dirname(__file__)
ACCENT = "#E84393"
BG = "#FFF0F8"
SERIES = "The Relationship Reset Series"

DISCLAIMER = """This book is intended for educational and informational purposes only. It does not constitute couples therapy, individual therapy, legal advice, or any form of professional clinical service.

Relationship challenges can range from ordinary interpersonal friction to serious safety concerns. If you or someone you know is in a relationship involving abuse, coercion, or threats to safety, please contact appropriate professional resources immediately.

For ongoing relationship difficulties, the guidance of a licensed couples or individual therapist is strongly recommended. Nothing in this book replaces professional therapeutic support."""

# ── Book 1 ────────────────────────────────────────────────────────────────────
b1 = {
    "title": "Attachment Styles and Why You Love the Way You Do",
    "subtitle": "Understanding Your Relational Blueprint",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Blueprint You Didn't Know You Had", "intro": "How you attach to people in adulthood was largely shaped before you could speak.", "sections": [
            {"heading": "Attachment Theory: The Core Idea", "body": ["John Bowlby's attachment theory proposes that early experiences with primary caregivers create internal working models — mental blueprints about whether relationships are safe, whether needs will be met, whether you are worthy of love. These blueprints operate largely outside conscious awareness.", "Mary Ainsworth's research identified three primary attachment patterns in children that Mary Main and others later extended to adult attachment: secure, anxious (also called anxious-preoccupied), avoidant (dismissive-avoidant), and disorganized (fearful-avoidant).", "These aren't rigid categories — they're tendencies along dimensions of anxiety (how worried you are about relationships) and avoidance (how much you pull away from intimacy). Most people lean primarily toward one style, with contextual variation."]},
            {"heading": "What Each Style Looks Like", "body": ["Secure: comfortable with closeness and independence, able to ask for help and give it, not destabilized by conflict or temporary distance. Approximately 50-60% of adults.", "Anxious: preoccupied with relationships, hypervigilant to signs of rejection or abandonment, heightened emotional reactivity to relationship stress, tendency to seek reassurance frequently.", "Avoidant: values self-sufficiency, uncomfortable with emotional closeness or dependence, tendency to withdraw when relationships feel too intense, often intellectualizes feelings.", "Disorganized (fearful-avoidant): wants connection but fears it, often related to early experiences of caregivers who were also threatening. Simultaneous approach and avoidance in relationships."]},
        ], "callout": "Your attachment style is not a life sentence. It's a starting point."},
        {"title": "How Attachment Shows Up in Adult Relationships", "intro": "Understanding your attachment style in theory is useful. Recognizing it in real time is transformative.", "sections": [
            {"heading": "The Anxious-Avoidant Dynamic", "body": ["The most commonly written-about attachment pairing is anxious + avoidant — and it's particularly sticky because each person's behavior activates the other's attachment system in a self-reinforcing loop.", "The anxious partner, feeling disconnected, pursues more connection. The avoidant partner, feeling overwhelmed, withdraws. The withdrawal intensifies the anxious partner's pursuit. The pursuit intensifies the avoidant withdrawal. Both feel unseen and misunderstood.", "Understanding that this pattern is driven by attachment systems — not malice, not lack of love, not fundamental incompatibility — makes it possible to interrupt. Both partners need to understand their own contribution to the loop."]},
        ], "callout": "The most frequent relationship argument is usually attachment systems talking to each other."},
        {"title": "Earned Security: Changing Your Attachment Pattern", "intro": "Secure attachment in adulthood is possible even if it wasn't your starting point.", "sections": [
            {"heading": "How Attachment Changes", "body": ["Attachment patterns are not fixed. Research on 'earned security' shows that adults with insecure attachment histories can develop secure attachment through: consistently positive relationship experiences (with partners, friends, or therapists), explicit understanding of their own patterns, and deliberate practice of new relational behaviors.", "The key mechanisms: experiences of being genuinely seen and accurately responded to (corrective relational experiences), understanding the origin of your patterns rather than just reacting from them, and gradually building tolerance for closeness or autonomy (depending on your direction)."]},
        ], "callout": "Secure attachment can be earned at any age through new relational experiences."},
        {"title": "Communicating Across Attachment Differences", "intro": "Partners rarely have identical attachment styles. Communication strategies that work for one style often don't work for the other.", "sections": [
            {"heading": "The Translation Layer", "body": ["For anxious partners communicating with avoidants: more explicit needs statements rather than testing behaviors. 'I need reassurance that we're okay' is receivable. Increasing emotional intensity until the avoidant responds is not — it accelerates their withdrawal.", "For avoidant partners communicating with anxious: voluntary closeness and proactive connection-offering reduces the anxious partner's need to pursue. Brief reassurance ('I need some space tonight but we're good') prevents the anxious partner from filling the silence with worst-case scenarios.", "The work: each partner learns their pattern, communicates it explicitly, and adapts their approach to reach the other rather than triggering their attachment system."]},
        ], "callout": "Effective intimacy requires speaking in the other person's attachment language."},
        {"title": "Healing Attachment Wounds in Relationships", "intro": "Intimate relationships are where attachment wounds are most activated — and where they can be most powerfully healed.", "sections": [
            {"heading": "The Healing Relationship", "body": ["Research by Sue Johnson (Emotionally Focused Therapy) shows that the primary attachment bond in adult romantic relationships is the primary site for healing early attachment injuries. The relationship itself is the therapeutic context when both partners can move toward security.", "This requires: each partner understanding their own attachment patterns, both partners being willing to see their role in the cycle, the development of repair behaviors after conflict or disconnection, and the gradual accumulation of experiences of being genuinely seen and met.", "This work is profound and not always accessible without therapeutic support. Couples therapy oriented around attachment (EFT or similar) is among the most evidence-supported interventions for relationship distress."]},
        ], "callout": "Relationships are where the wound lives. They can also be where it heals."},
        {"title": "Secure Relationships: What They Actually Look Like", "intro": "Security in relationships is not the absence of conflict. It's a quality of trust that can hold conflict.", "sections": [
            {"heading": "The Hallmarks of Secure Functioning", "body": ["Repair: the ability to come back together after conflict, to acknowledge impact, and to restore the connection without extended punishment or withdrawal.", "Honest vulnerability: the ability to express genuine needs and fears without the expectation that this vulnerability will be used against you.", "Supported autonomy: each partner can pursue their own interests, friendships, and development without the other feeling threatened — because the primary connection is secure enough to hold space.", "Consistent responsiveness: the sense of being reliably available to each other — not perfectly, but consistently enough that the underlying trust is maintained through imperfection.", "Security is not a permanent state. It's maintained through consistent acts of care, repair, and genuine responsiveness over time."]},
        ], "callout": "Security isn't a feeling. It's a practice."},
    ]
}

# ── Book 2 ────────────────────────────────────────────────────────────────────
b2 = {
    "title": "Communication That Actually Connects",
    "subtitle": "The Relationship Skills That Nobody Teaches You",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Why Smart People Have Poor Communication in Relationships", "intro": "Communication skill in professional contexts does not automatically transfer to intimate ones.", "sections": [
            {"heading": "The Intimacy Communication Gap", "body": ["The communication skills that work at work — persuasion, argumentation, efficiency, hierarchy awareness — often actively sabotage intimate relationships. Arguing to win, prioritizing being understood over understanding, emotional efficiency — these are effective at work and damaging at home.", "Intimate communication requires different skills: radical listening, vulnerability, emotional attunement, repair after rupture. These are not taught in school, rarely modeled in media, and almost never explicitly addressed in professional development."]},
        ], "callout": "Your best professional communication skills might be your worst relationship tools."},
        {"title": "Listening as a Relational Act", "intro": "The quality of listening in a relationship predicts its quality more reliably than almost anything else.", "sections": [
            {"heading": "What Real Listening Requires", "body": ["Listening that creates connection is not the same as hearing the words. It requires: suspending your own frame of reference temporarily, attending to what the person is actually experiencing rather than what you'd experience in their situation, reflecting understanding back so the person feels genuinely received, and tolerating the discomfort of your own reaction without immediately surfacing it.", "The most common listening failures: listening to respond (formulating your answer while they're still speaking), listening to evaluate (deciding whether their feeling is reasonable), listening to fix (identifying the solution before they finish the problem), and defensive listening (filtering for anything that might be criticism).", "Ask yourself after your next significant conversation: did I understand them better at the end than at the beginning? If not, you were probably not listening."]},
        ], "callout": "Listening is the most intimate thing you can do for another person."},
        {"title": "The Four Communication Blockers", "intro": "Marshall Rosenberg's work on nonviolent communication identifies four patterns that predictably shut down genuine communication.", "sections": [
            {"heading": "Diagnosis, Evaluation, Comparison, and Demands", "body": ["Diagnosis and judgment: 'You're being irrational' or 'You're too sensitive' makes the other person defend their reality rather than explore it with you.", "Evaluation: attributing behavior to character rather than feelings and needs. 'You're selfish' produces defensiveness. 'I felt overlooked when X happened' opens dialogue.", "Comparison: 'Other people don't have this problem' or 'My ex never made an issue of this' is designed to shame. It produces hurt, not change.", "Demands: 'You need to...' or 'You have to...' removes the other person's autonomy. Requests — 'Would you be willing to...?' — preserve it.", "All four patterns share a common feature: they prioritize the speaker's position over the listener's experience, which closes rather than opens the relational space."]},
        ], "callout": "Communication that defends closes relationships. Communication that inquires opens them."},
        {"title": "Expressing Needs Without Blame", "intro": "Needs are legitimate. How you express them determines whether they get met.", "sections": [
            {"heading": "The NVC Formula", "body": ["Marshall Rosenberg's nonviolent communication formula: Observation (what actually happened, without evaluation), Feeling (how you feel about it), Need (the underlying value or need), Request (a specific, actionable, positive request).", "'When you came home and went straight to your phone without saying anything to me (observation), I felt lonely and disconnected (feeling). I really value our connection after work days (need). Would you be willing to spend the first 10 minutes just with me when you get home? (request)'", "Compare to the more typical version: 'You always ignore me when you get home. You don't care about our relationship at all.' Same trigger, radically different response from the other person."]},
        ], "callout": "Observation + Feeling + Need + Request is the structure that gets heard."},
        {"title": "Conflict as Information", "intro": "Couples who never fight are not necessarily healthier than couples who do. They might just be avoiding more.", "sections": [
            {"heading": "The Purpose of Relational Conflict", "body": ["Conflict in relationships is not a sign that something has gone wrong. It's a sign that two different people with different needs, histories, and perspectives are negotiating a shared life.", "Gottman's research found that the content of the argument matters less than how it's conducted. Couples who maintain a 5:1 ratio of positive to negative interactions — even during conflict — have dramatically better relationship outcomes than those who don't.", "The goal is not to win the argument or even to resolve it necessarily. The goal is to feel more understood, and to understand the other person better, as a result of having had it."]},
        ], "callout": "Conflict done well produces closeness, not just resolution."},
        {"title": "The Repair as Relationship Skill", "intro": "Repair after conflict is the single most important relationship maintenance behavior.", "sections": [
            {"heading": "What Repair Looks Like", "body": ["Repair attempts — any gesture, statement, or behavior that interrupts escalating conflict and moves toward reconnection — are the primary mechanism through which couples maintain their bond over time.", "Effective repairs: acknowledging the other person's experience before explaining your own ('I can see why that landed the way it did'), taking responsibility for your contribution without requiring the other person to do the same simultaneously, expressing genuine care for the relationship even in the middle of a fight, and humor that decreases tension without dismissing the issue.", "The couples who stay together happily long-term are not those who fight less. They're those who repair better — more quickly, more genuinely, more consistently."]},
        ], "callout": "The quality of the repair matters more than the frequency of the rupture."},
    ]
}

# ── Book 3 ────────────────────────────────────────────────────────────────────
b3 = {
    "title": "Recovering From Infidelity",
    "subtitle": "What It Takes to Heal — Whether You Stay or Go",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Aftermath of Betrayal", "intro": "Infidelity is one of the most acute traumas that occurs within intimate relationships. The response is appropriate to that severity.", "sections": [
            {"heading": "Why It Hits So Hard", "body": ["Infidelity violates the fundamental attachment bond: the safety and exclusivity that is the implicit or explicit contract of a committed relationship. When that contract is violated, the attachment system activates at its most extreme level — because the person the injured partner turns to for comfort and safety is simultaneously the source of danger.", "The response to infidelity often meets clinical criteria for trauma: intrusive thoughts, hypervigilance, emotional dysregulation, concentration difficulties, and profound disruption of the sense of self and world.", "Understanding this as a trauma response — not weakness or overreaction — is the starting point for both partners in navigating what comes next."]},
        ], "callout": "Betrayal trauma is real trauma. The response should be treated accordingly."},
        {"title": "The Immediate Aftermath", "intro": "The first weeks after discovery are not a time for major decisions. They are a time for stabilization.", "sections": [
            {"heading": "What Not to Do Immediately", "body": ["Do not make permanent decisions in the acute trauma phase. The person who is deciding whether to stay or leave 72 hours after discovery is not operating with their full cognitive and emotional capacity.", "Do not retaliate in ways that create their own damage — disclosing to children, mutual social attacks, impulsive financial moves. These create complications that outlast the immediate crisis.", "Do seek: personal therapeutic support for the injured partner, honest assessment of whether the immediate environment is physically safe (not all betrayal occurs in safe relationships), and space to feel the feelings before having to take action."]},
        ], "callout": "Stabilize before deciding. Decisions made in acute trauma are rarely the right decisions."},
        {"title": "For the Couple That Wants to Rebuild", "intro": "Rebuilding after infidelity is possible — but it requires a fundamentally different relationship than the one that existed before.", "sections": [
            {"heading": "The Requirements for Rebuilding", "body": ["Esther Perel and Janis Spring, among others who have written and researched infidelity recovery, identify consistent requirements for successful rebuilding: complete cessation of the affair, complete transparency (not the details of the affair necessarily, but transparency going forward), genuine accountability from the person who cheated, and genuine willingness from the injured partner to eventually move toward healing (not immediately — this is a long process).", "The new relationship is not the old relationship restored — it is a new relationship built on the honest examination of what was missing, what happened, and what both people want to build now.", "Professional couples therapy specifically oriented toward infidelity recovery is strongly recommended — this is genuinely not the territory for self-help alone."]},
        ], "callout": "Rebuilding after infidelity means building something new, not restoring what was."},
        {"title": "For the Individual Who Is Leaving", "intro": "Choosing to leave after infidelity is a legitimate response. The healing path is different but not easier.", "sections": [
            {"heading": "The Healing That Belongs to You", "body": ["Leaving ends the relationship. It does not end the betrayal trauma. The shock, hypervigilance, intrusive thoughts, and fractured sense of self belong to the experience, not just the relationship.", "The healing work after leaving: processing the trauma (therapeutic support, ideally with a trauma-informed therapist), rebuilding the narrative of your identity outside the relationship, and eventually — at your own pace — developing a relationship with trust that doesn't carry this injury into the next chapter.", "Do not rush the healing in order to begin a new relationship. The unprocessed betrayal trauma will arrive in the next relationship looking for resolution."]},
        ], "callout": "Leaving ends the situation. Healing ends the wound."},
        {"title": "Understanding Why Infidelity Happens", "intro": "Understanding is not the same as justifying. But it often changes what healing and prevention look like.", "sections": [
            {"heading": "The Range of Motivations", "body": ["Research by Perel and others identifies several categories of affair motivation that are worth distinguishing: affairs driven by opportunity and impulse (least reflective of relationship dissatisfaction), affairs driven by specific relationship deficits (loneliness, sexual incompatibility, lack of emotional intimacy), affairs driven by personal identity issues (a search for self rather than a rejection of partner), and serial infidelity (a pattern that usually reflects character structure rather than relationship circumstances).", "The category matters for rebuilding: a relationship that was not meeting genuine needs can potentially be changed to meet them. A relationship with a serial cheater faces a different challenge.", "Understanding motivation does not assign blame to the injured partner. Both partners contributed to whatever relational dynamic existed. Only one chose infidelity as a response."]},
        ], "callout": "Understanding why doesn't excuse it. It just makes the path forward clearer."},
        {"title": "The Long View on Healing", "intro": "Recovery from infidelity is typically measured in years, not weeks.", "sections": [
            {"heading": "The Timeline", "body": ["Research suggests that rebuilding trust after infidelity, when both partners are committed to the work, typically takes 2-5 years. Not 2-5 months. Not 2-5 weeks.", "Progress is not linear: there are genuine periods of improvement followed by unexpected resurgences of pain, particularly around anniversary dates, life events, or triggers that recall the original discovery.", "Both partners need ongoing support. The injured partner's ongoing pain is predictable and appropriate. The person who cheated needs support too — particularly if they are genuinely committed to changing behavior that led to the affair in the first place.", "Long-view healing produces something real: couples who fully navigate infidelity recovery often report that their post-recovery relationship is genuinely closer and more honest than what existed before. This is not a justification for infidelity. It is an acknowledgment that profound rupture, fully healed, can produce profound depth."]},
        ], "callout": "Healing infidelity takes years. The investment is proportional to what becomes possible."},
    ]
}

# ── Book 4 ────────────────────────────────────────────────────────────────────
b4 = {
    "title": "The Art of Healthy Conflict",
    "subtitle": "Turn Arguments Into Connection Instead of Destruction",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Conflict Is Really About", "intro": "The surface argument is rarely the actual argument.", "sections": [
            {"heading": "The Presenting vs. The Real", "body": ["The argument about who forgot to take out the garbage is almost never about the garbage. It's about feeling unseen, unappreciated, like the other person doesn't care. The argument about money is often about security, control, values, or power in the relationship.", "One of the most useful questions during or after conflict: 'What is this really about for me?' The answer is almost always a deeper need — for respect, for security, for partnership, for acknowledgment.", "Addressing the presenting argument (the garbage) without addressing the underlying need (I want to feel like we're in this together) produces a temporary resolution that leaves the actual complaint intact to recur under different packaging."]},
        ], "callout": "The argument you're having is almost never the argument you need to have."},
        {"title": "Physiological Flooding and How to Manage It", "intro": "When the body floods with stress hormones, productive conversation becomes physiologically impossible.", "sections": [
            {"heading": "The Biology of Escalation", "body": ["Gottman's research identified physiological flooding — heart rate exceeding 100 bpm, elevated cortisol and adrenaline — as the state in which conflict becomes destructive. When flooded, people cannot listen effectively, cannot access empathy, and revert to defensive or attacking behaviors.", "The intervention is simple and difficult: when you are flooded, stop the conversation. Not forever — but for at least 20-30 minutes, which is the minimum time for stress hormones to metabolize. Agree on a return time. Do genuinely calming activity in the interim.", "Many people resist this because stopping a conversation mid-conflict feels like losing or abandoning. It is actually the most constructive move available when flooded."]},
        ], "callout": "You cannot have a productive argument when you're flooded. Stop before you escalate."},
        {"title": "The Perpetual Problems", "intro": "Research finds that 69% of relationship conflict is about perpetual problems — issues that are never fully resolved because they reflect fundamental personality or value differences.", "sections": [
            {"heading": "Living With Unresolvable Differences", "body": ["Perpetual problems are not failures. They are the friction generated by two different people with different histories, values, and preferences trying to share a life.", "The goal with perpetual problems is not resolution — it is dialogue. The couples who handle perpetual problems well have ongoing conversations about them that produce mutual understanding and tolerance, even without agreement.", "The dangerous version of a perpetual problem is gridlock: the conversation becomes so loaded with hurt and resentment that it can no longer be had openly. Getting out of gridlock requires understanding why each person holds their position — the dreams, fears, and history underneath the position — rather than just arguing the position itself."]},
        ], "callout": "69% of relationship conflicts are never fully resolved. Learn to dialogue, not just argue."},
        {"title": "When to Fight and When to Let It Go", "intro": "Not every disagreement deserves a full-scale conversation. The ability to let things go is as important as the ability to raise things.", "sections": [
            {"heading": "The Discernment", "body": ["Ask before raising an issue: Is this something that will matter in 5 years? Is this a pattern (worth addressing) or a one-time event (possibly worth letting go)? Is raising this going to improve the relationship or just relieve my current frustration?", "Every couple has limited relational currency for difficult conversations. Spending it on small irritants depletes the reserves needed for important issues.", "The flip side: consistently letting things go because conflict feels too risky builds resentment and eventually produces the explosive version of the conversation you avoided. Some things need to be raised. The skill is discernment about which."]},
        ], "callout": "Not every feeling needs to be shared. Not every issue needs to be raised. Discernment is love."},
        {"title": "Repair in Real Time", "intro": "The moment the conversation starts going wrong is the moment the repair skill is most needed.", "sections": [
            {"heading": "Real-Time Interruption Strategies", "body": ["Gottman identified repair attempts — statements or behaviors that interrupt escalating negative cycles — as among the most powerful predictors of relationship health. Couples who make and receive repair attempts have dramatically better outcomes.", "Effective mid-conflict repairs: 'I'm feeling defensive. Can we slow down?' 'I think I'm not hearing you right — can you say that again?' 'I care about us and I want to understand your side.' Even: 'Can we take a break?'", "The critical element: repair attempts must be received. Both partners need to be willing to recognize and accept the other's attempts to de-escalate, even when they're still hurt. Refusing repair attempts is one of the most damaging things you can do in conflict."]},
        ], "callout": "The bid to de-escalate is always worth accepting, even when you're still hurt."},
        {"title": "After the Fight", "intro": "The conversation after the fight is often more important than the fight itself.", "sections": [
            {"heading": "The Debrief", "body": ["After a significant conflict, a debrief conversation — when both partners are calm — can be transformative. Not 'who was right' but: What triggered me? What did I need that I didn't ask for clearly? What did I do that made things harder? What do I want us to do differently next time?", "This conversation builds the shared knowledge about each other that allows conflict to become a refinement process rather than a repeated trauma.", "Express gratitude for the repair: 'I'm glad we talked.' 'I'm glad we figured that out.' 'I love you even when we argue.' These small statements after conflict reinforce the fundamental safety of the relationship."]},
        ], "callout": "What you do after the fight shapes the relationship more than the fight itself."},
    ]
}

# ── Books 5-10 (more concise to stay efficient) ───────────────────────────────
b5 = {
    "title": "Loving Someone With Anxiety",
    "subtitle": "How to Support Your Partner Without Losing Yourself",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG, "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Anxiety Looks Like in a Relationship", "intro": "Anxiety in a partner is not always obvious, especially in its early stages.", "sections": [{"heading": "The Many Faces of Relationship Anxiety", "body": ["Anxiety in relationships can present as excessive reassurance-seeking, avoidance of certain activities or situations, irritability, hypervigilance about perceived slights, difficulty making decisions, patterns of checking and verifying, or withdrawal and catastrophizing.", "From the outside, these behaviors can feel controlling, distant, or exhausting — particularly if you don't understand their source. Understanding that these are anxiety responses, not character flaws or deliberate behaviors, changes the relational dynamic significantly."]}], "callout": "Anxiety looks different from the inside and the outside."},
        {"title": "Supporting Without Enabling", "intro": "There is a meaningful difference between supporting someone with anxiety and enabling the anxiety itself.", "sections": [{"heading": "The Distinction", "body": ["Accommodation — adjusting your own behavior to prevent your partner's anxiety — provides short-term relief and long-term reinforcement. The anxiety grows to fill the protected space.", "Support that helps: being present without rescuing, encouraging engagement with feared situations, validating the feeling without validating the feared prediction, and maintaining the expectation that your partner can cope.", "This requires ongoing calibration. It's not cold; it's genuinely supportive in a deeper sense."]}], "callout": "The most loving thing is often the hardest thing: not rescuing."},
        {"title": "Your Needs in This Relationship", "intro": "Partners of anxious people often lose track of their own needs in the process of managing the relationship.", "sections": [{"heading": "Self-Preservation as Partnership", "body": ["You cannot sustain support indefinitely from an empty tank. Your needs — for spontaneity, for calm, for reciprocity, for predictability — are legitimate and deserve space in the relationship.", "Regular check-ins with yourself: what am I feeling? What do I need that I'm not getting? What am I suppressing to manage their anxiety? These are questions that matter."]}], "callout": "A relationship where only one person's needs matter isn't partnership."},
        {"title": "Communication Strategies That Help", "intro": "How you communicate about anxiety with an anxious partner significantly affects the outcome.", "sections": [{"heading": "What Works", "body": ["Curiosity over correction: 'What's driving this for you?' rather than 'You're overthinking it.' 'What would help right now?' rather than 'You need to relax.'", "Timing: don't try to have important conversations when anxiety is peaking. Wait for a calm moment.", "Consistent reassurance in low-stakes ways: regular expressions of love and commitment reduce the reassurance-seeking need in high-stakes moments."]}], "callout": "Curiosity and consistency are the most helpful communication tools."},
        {"title": "Encouraging Professional Support", "intro": "There's a point where the partner's support is not sufficient and professional help is necessary.", "sections": [{"heading": "How to Raise It", "body": ["'I love you and I want to support you, and I think a therapist could offer tools I simply can't' is a framing that leads with care rather than rejection.", "Normalize therapy as what it is: professional support for real challenges. Not weakness. Not failure.", "Offer practical support: research options together, offer to help schedule, be genuinely positive about the process."]}], "callout": "Encouraging therapy is an act of love, not an admission of defeat."},
        {"title": "When Anxiety Strains the Relationship", "intro": "Sustained anxiety in a relationship does create strain. Acknowledging it is the first step.", "sections": [{"heading": "The Honest Conversation", "body": ["Couples therapy offers a space where both the anxiety and the relational strain it creates can be addressed simultaneously — which individual therapy for one partner cannot provide.", "If you find yourself increasingly resentful, avoidant, or despairing about the relationship, these are signals worth taking seriously — not as reasons to leave, but as information that the current dynamic needs to change."]}], "callout": "Strain in the relationship is information, not verdict."},
    ]
}

b6 = {
    "title": "Rebuilding Trust",
    "subtitle": "How Trust Is Broken, How It's Repaired, and What It Costs to Skip Either Step",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG, "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Trust Actually Is", "intro": "Trust is not a feeling. It's a conclusion drawn from evidence.", "sections": [{"heading": "The Components of Trust", "body": ["Brené Brown's research identifies the anatomy of trust as BRAVING: Boundaries (you respect mine and ask about yours), Reliability (you do what you say), Accountability (you own your mistakes), Vault (you don't share information that's not yours), Integrity (you choose courage over comfort), Non-judgment (you can ask for support without judgment), Generosity (you extend the most generous interpretation possible).", "Trust erodes not always through dramatic events but through accumulated small violations: commitments not kept, information shared carelessly, accountability avoided, boundaries repeatedly ignored."]}], "callout": "Trust is built in small acts. It erodes the same way."},
        {"title": "After Trust Is Broken", "intro": "The path to rebuilt trust is specific and sequential.", "sections": [{"heading": "The Repair Sequence", "body": ["Acknowledgment: the person who broke trust must specifically acknowledge what they did and its impact, without minimizing, deflecting, or rushing to explanation.", "Accountability: genuine responsibility. Not 'I'm sorry you feel that way' — 'I did X and it caused Y and that was wrong.'", "Behavior change: trust is rebuilt through sustained behavior that demonstrates change, not through apology. Apology is the beginning. Behavior is the proof."]}], "callout": "Apology without behavior change is manipulation."},
        {"title": "The Role of the Injured Party", "intro": "Rebuilding trust requires something from both people.", "sections": [{"heading": "What Healing Asks of the Injured Person", "body": ["Rebuilding trust requires the injured person to: communicate clearly what they need to see in order to begin extending trust again, allow the evidence of changed behavior to update their assessment over time, and distinguish between appropriate vigilance and punitive indefinite suspension of trust.", "Neither person can control the timeline. Both contribute to it."]}], "callout": "Trust rebuilding is a two-person project with an uncertain timeline."},
        {"title": "Trust in the Age of Technology", "intro": "Digital access has created new forms of both trust violation and surveillance that relationships are still learning to navigate.", "sections": [{"heading": "The Transparency Conversation", "body": ["Open phone policies, location sharing, shared passwords — these are tools that mean different things in different relationships and at different stages. What matters is explicit agreement rather than assumption.", "Surveillance without agreement is not transparency — it's monitoring. The difference is consent and purpose."]}], "callout": "Transparency is an agreement. Surveillance is a symptom."},
        {"title": "Self-Trust as Foundation", "intro": "Trust in others is hard to maintain when trust in yourself has been eroded.", "sections": [{"heading": "Rebuilding Self-Trust", "body": ["Betrayal often damages the injured person's trust in their own perception. 'How did I not see this?' 'What does it mean that I trusted them?'", "Self-trust is rebuilt through: trusting your own perceptions rather than accepting others' reframes of them, following through on your own commitments to yourself, and learning from the experience without using it as evidence of permanent naive gullibility."]}], "callout": "Trust in yourself is the prerequisite for healthy trust in others."},
        {"title": "When Trust Cannot Be Rebuilt", "intro": "Some trust violations produce damage that genuinely cannot be repaired in a particular relationship.", "sections": [{"heading": "Recognizing the Limit", "body": ["Some indicators that trust cannot be rebuilt: repeated violations of the same type, absence of genuine accountability (persistent blame of the injured party), unwillingness to take the steps the injured party has identified as necessary, and sustained intuitive sense from the injured party that the change is performative rather than genuine.", "Ending a relationship because trust cannot be repaired is a legitimate and sometimes necessary decision. It is not failure."]}], "callout": "Sometimes the most honest answer to 'can we rebuild?' is no."},
    ]
}

b7 = {
    "title": "Intimacy After Trauma",
    "subtitle": "Reclaiming Connection After Your Body Said No",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG, "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "How Trauma Affects Intimacy", "intro": "Trauma changes the body's relationship with safety — which is also the body's relationship with intimacy.", "sections": [{"heading": "The Body's Memory", "body": ["Trauma, particularly sexual or relational trauma, is stored in the body's threat-response system. Intimacy — which involves proximity, touch, vulnerability, and the lowering of defenses — is among the most reliable triggers for those stored responses.", "This is not metaphor. Physical intimacy with a safe partner can produce fear, dissociation, rage, or emotional shutdown that has nothing to do with the current partner and everything to do with what the nervous system learned in a previous unsafe context."]}], "callout": "Your body's response to intimacy is informed by its entire history."},
        {"title": "Creating Safety First", "intro": "Rebuilding capacity for intimacy after trauma begins with safety, not with intimacy itself.", "sections": [{"heading": "The Foundation Before the Building", "body": ["Nervous system safety — the body's experience of being genuinely un-threatened — is the prerequisite for intimacy after trauma. Safety is built through: consistent, predictable partner behavior, explicit negotiation of boundaries, the ability to stop any intimate activity at any point without consequence, and gradual exposure to connection that never exceeds what feels safe."]}], "callout": "Safety first. Intimacy follows safety, not the other way around."},
        {"title": "Communication About History", "intro": "How and whether to share trauma history with a partner is a deeply personal and consequential decision.", "sections": [{"heading": "The Disclosure Question", "body": ["You are not obligated to share your trauma history with a partner, particularly early in a relationship. You are responsible for communicating current needs and limits.", "'I'm working through some things and I need [specific accommodation or behavior]' communicates need without requiring full history.", "As trust deepens, fuller sharing may feel right and may be received in ways that are profoundly healing — or not, if the partner is not capable of receiving it well. Timing and recipient selection matter enormously."]}], "callout": "You own your story. Share it on your terms."},
        {"title": "Partners of Trauma Survivors", "intro": "Loving someone with trauma history requires specific knowledge and specific practices.", "sections": [{"heading": "What Helps and What Doesn't", "body": ["Helpful: consistent patience, following the survivor's lead about pace and limits, educating yourself about trauma responses, maintaining your own support and processing outside the relationship.", "Unhelpful: taking trauma responses personally, pressuring for intimacy beyond the survivor's current capacity, interpreting caution as rejection, or making the survivor responsible for managing your frustration about the situation."]}], "callout": "Following the survivor's lead is the most important thing a partner can do."},
        {"title": "Somatic Approaches to Healing Intimacy", "intro": "Trauma in the body responds to body-based approaches that purely cognitive work cannot fully reach.", "sections": [{"heading": "The Body-Based Path", "body": ["Somatic therapies — including somatic experiencing, EMDR, and sensorimotor psychotherapy — address trauma at the nervous system level where it lives.", "Body-based self-care practices that support trauma healing: breathwork that builds tolerance for sensation, gentle movement that builds body awareness and safety, gradual and consensual touch experiences that build new associations."]}], "callout": "Trauma lives in the body. Healing reaches into the body too."},
        {"title": "Reclaiming Your Erotic Self", "intro": "Trauma does not have to permanently determine your relationship with your own body or your sexuality.", "sections": [{"heading": "The Long Path Back", "body": ["Reclaiming sexuality after trauma is not a single event. It is a gradual, non-linear process of building new associations, expanding the window of what feels safe, and developing a relationship with your own body that is yours.", "Professional support from a therapist with specific training in trauma and sexuality is often essential for this work. The work is possible. For many survivors, it becomes one of the most profound acts of self-reclamation they undertake."]}], "callout": "Your sexuality belongs to you — and it can be reclaimed."},
    ]
}

b8 = {
    "title": "Parenting as Partners",
    "subtitle": "How to Stay Connected When a Child Changes Everything",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG, "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Having a Child Actually Does to a Relationship", "intro": "The research is surprisingly consistent, and it's not what most expectant parents want to hear.", "sections": [{"heading": "The Data", "body": ["John Gottman's research found that 67% of couples experience a significant decline in relationship satisfaction in the first three years after a child's birth. The primary drivers: reduced time for connection, asymmetric labor distribution, exhaustion, and the loss of the couple identity in the parent identity.", "This is not inevitable. Couples who discuss expectations explicitly before birth, who continue to invest in their relationship after birth, and who address labor distribution fairly tend to fare significantly better."]}], "callout": "Having a child is a relationship stress test. Pass it with preparation, not hope."},
        {"title": "Division of Labor Without Resentment", "intro": "The domestic labor conversation is the most common source of relationship deterioration in new parenthood.", "sections": [{"heading": "The Equitable Distribution Conversation", "body": ["The goal is not equal hours — it's perceived fairness, which requires explicit discussion rather than assumption.", "Write down everything that needs to happen. All of it. Then have an honest conversation about what each person is doing, what the ideal distribution would be given your circumstances, and what the gaps are.", "This conversation is uncomfortable and essential. The resentment that accumulates from invisible labor imbalance is one of the most corrosive forces in new-parent relationships."]}], "callout": "Make the invisible visible. Then negotiate it fairly."},
        {"title": "Keeping the Couple Alive in the Parents", "intro": "The couple that disappears into parenting often resurfaces when children leave — as strangers.", "sections": [{"heading": "The Investment Requirement", "body": ["Relationship maintenance after children requires intentional investment: regular protected couple time (even 20 minutes without screens counts), physical affection that isn't about sex (sustained affection buffers relationship against the demands of new parenthood), and deliberate conversation that isn't about logistics or the children.", "None of this is easy when you're exhausted. All of it is necessary."]}], "callout": "The relationship that survives early parenthood is one that was tended, not one that survived by accident."},
        {"title": "Different Parenting Styles: When You Disagree", "intro": "Different parenting approaches between partners are normal. Unresolved differences create problems for both the couple and the children.", "sections": [{"heading": "Finding Common Ground", "body": ["Children need consistency between parents at least on the core fundamentals: safety, consequences for serious behavior, values. Everything else is negotiable.", "The productive conversation: what do each of you most want your child to learn? What were your own childhoods like, and what do you want to replicate and what do you want to correct? What are the non-negotiables for each of you?", "Present a united front to children in the moment, even if you disagree. Resolve disagreements in private."]}], "callout": "Children need consistency between parents. Get it by talking before it matters."},
        {"title": "Sex After Children", "intro": "The decline in sexual frequency after children is extremely common and extremely distressing for many couples.", "sections": [{"heading": "The Reality and the Path", "body": ["Physical exhaustion, touched-out-ness (particularly for breastfeeding parents), changed body image, hormonal shifts, and the loss of privacy and spontaneity all contribute to reduced sexual frequency and desire in new and early parenthood.", "The path is not forcing sex. It's maintaining affection, maintaining the emotional intimacy that is the context for physical intimacy, and explicitly discussing what each person needs — rather than allowing silent distance to become the new normal."]}], "callout": "Affection and emotional connection are the preconditions for physical intimacy. Protect them first."},
        {"title": "Growing Together Through Parenting", "intro": "Parenting, done as partners, can be one of the most profound shared experiences of a relationship.", "sections": [{"heading": "The Partnership Opportunity", "body": ["The couples who grow through parenting rather than growing apart share some common patterns: they talk about the experience of parenting explicitly, they appreciate each other's contributions, they maintain humor about the absurdity of it, and they maintain genuine curiosity about who the other person is becoming through the experience.", "Children change their parents. The parents who maintain genuine relationship with each other also maintain genuine relationship with the people they're each becoming."]}], "callout": "You grow through parenting. Grow together if you can."},
    ]
}

b9 = {
    "title": "Dating After 35",
    "subtitle": "What Changes, What Stays the Same, and How to Find Someone Real",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG, "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Actual Differences", "intro": "Dating in your late 30s, 40s, and beyond is different from early-20s dating in specific, addressable ways.", "sections": [{"heading": "What's Different", "body": ["More self-knowledge: you know more about what you need, what you won't tolerate, and who you are. This is a major advantage that younger daters don't have.", "More history: you may have been married, have children, have been through significant loss or disappointment. This is not baggage — it's context.", "Less flexibility with time: established lives, responsibilities, and routines mean that fitting a new relationship into existing life requires more deliberate effort than it did when everything was fluid.", "Higher stakes: at this stage, most people are not casually dating — they're looking for a genuine long-term partner, which raises both the intentionality and the stakes."]}], "callout": "Experience is an advantage. Treat it that way."},
        {"title": "Online Dating as a Tool, Not a Life", "intro": "Online dating is a mechanism for meeting people. It's not a replacement for judgment, presence, or genuine chemistry.", "sections": [{"heading": "Using It Well", "body": ["Profile authenticity: the profile that attracts the right people is the honest one. Photos that accurately represent how you look, bio that reflects who you actually are. The mismatch between profile and reality wastes everyone's time.", "Get to in-person quickly: the extended app conversation that never becomes a meeting serves no one. 3-4 messages maximum, then either a phone call or a meeting.", "Volume is not the strategy: going on 25 mediocre dates is not more useful than going on 5 specifically chosen ones. Be selective based on real criteria, not just availability."]}], "callout": "Apps are meetings, not relationships. Get to in-person."},
        {"title": "What You Actually Want vs. What You Think You Want", "intro": "The stated criteria for a partner often correlate weakly with actual compatibility.", "sections": [{"heading": "Values Over Attributes", "body": ["Checklists of desired attributes — height, job, appearance, hobby overlap — are poor predictors of relationship quality. Values, communication style, attachment patterns, and the experience of being with someone are far better predictors.", "The question to ask after a date is not 'do they match my list?' but 'how did I feel in this person's company? Did I feel seen? Did I feel good about who I was in this interaction?'"]}], "callout": "Chemistry is real. Checklist compatibility is overrated."},
        {"title": "The History Conversation", "intro": "Past relationships are present in current ones. Navigating others' histories (and your own) with wisdom is part of mature dating.", "sections": [{"heading": "First Date History Rules", "body": ["First date is not the time for comprehensive trauma disclosure or detailed ex relationship post-mortems. It's the time to establish genuine present-tense connection.", "Later, as trust builds, sharing history becomes appropriate and deepens connection. The sequence matters: connection first, then history; not the reverse."]}], "callout": "History is context. Earn the right to share it."},
        {"title": "Children, Exes, and Complex Lives", "intro": "Relationships after 35 often involve navigating significant complexity that younger relationships don't.", "sections": [{"heading": "The Practical Realities", "body": ["Children from previous relationships are not complications to manage — they're people who are part of your life. A potential partner who is uncomfortable with this reality is not a good fit.", "Co-parenting relationships with exes require respect and functional communication. A potential partner's ability to be reasonable about your necessary relationship with an ex is a meaningful criterion.", "These are grown-up dating circumstances. They require grown-up assessment, communication, and grace."]}], "callout": "Complex lives deserve partners who can hold complexity."},
        {"title": "Taking Your Time, Not Too Much Time", "intro": "There is a meaningful difference between taking the relationship at a healthy pace and using caution to avoid genuine commitment.", "sections": [{"heading": "The Caution vs. Avoidance Question", "body": ["Healthy caution: taking time to assess genuine compatibility, allowing trust to develop naturally, not rushing a major life decision.", "Avoidance dressed as caution: keeping emotional distance as a protection against disappointment, being perpetually 'not ready,' finding reasons why each person is almost but not quite right.", "The honest question: is my hesitation protecting me from a genuinely unsuitable person, or protecting me from risk entirely?"]}], "callout": "Know the difference between choosing slowly and not choosing."},
    ]
}

b10 = {
    "title": "When to Leave and When to Stay",
    "subtitle": "The Honest Questions That Help You Decide",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG, "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Hardest Question", "intro": "The stay-or-leave question is one of the most significant decisions a person makes. It deserves serious thought, not a formula.", "sections": [{"heading": "Why It's So Hard", "body": ["The difficulty is not usually information scarcity — most people who are genuinely trying to decide this question already know things that are relevant. The difficulty is the weight of the implications: financial, social, logistical, relational, and the deep grief of ending something that mattered.", "Therapist Dan Wile observed: 'When choosing a long-term partner, you will inevitably be choosing a particular set of unresolvable problems.' Every relationship has its intractable elements. The question is whether this relationship's specific intractable elements are ones you can live with.", "There is no formula that answers this question for you."]}], "callout": "No one can answer this question for you. But the right questions help."},
        {"title": "Non-Negotiables: What Always Justifies Leaving", "intro": "Some circumstances are not ambiguous — they are clear signals to exit.", "sections": [{"heading": "The Absolute Indicators", "body": ["Physical violence or serious threat of violence: this is always sufficient grounds to leave and to leave safely. If you are in a violent relationship, please contact the National Domestic Violence Hotline or equivalent in your country before anything else.", "Sustained emotional abuse: psychological control, sustained contempt, gaslighting, isolation from support systems — these produce serious psychological harm and do not improve without significant intervention.", "Sexual coercion: any sexual activity that is not freely and enthusiastically consented to.", "Addiction without treatment: an actively untreated serious addiction damages everything it touches and cannot be managed by the partner."]}], "callout": "Violence, serious abuse, and untreated addiction are not problems to work through. They are reasons to leave."},
        {"title": "The Harder Cases", "intro": "Most people wrestling with this question are not in abusive situations — they are in relationships that are real and complicated and painful in ways that don't have obvious answers.", "sections": [{"heading": "Questions That Help", "body": ["Have we genuinely tried to address the core issues, with professional support, and been unable to? Or have we talked around them indefinitely without real effort?", "Is my partner capable of genuine change in the areas that matter most, and are they willing to do the work? Or am I waiting for change that has not materialized despite repeated chances?", "When I imagine my life in ten years with this person — not an idealized version, but the realistic one — does that feel like a life I want?", "What would I tell a close friend who described exactly this situation?"]}], "callout": "The right questions are clearer than the answers. Start with the questions."},
        {"title": "What 'Working on the Relationship' Actually Means", "intro": "Deciding to stay is only meaningful if the stay is followed by genuine work — not more of the same.", "sections": [{"heading": "The Commitment Requires Content", "body": ["Couples therapy with a skilled therapist is not the last resort — it is the standard tool for people who want to work on a relationship seriously. 'Working on it' through continued unproductive argument is not the same.", "A clear agreement about what specifically needs to change, with a specific timeline for reassessment, prevents the indefinite hope that things will improve without change. 'Let's try for 6 months with a therapist and reassess honestly' is a workable commitment. 'Let's try' is not."]}], "callout": "Working on it requires a plan, not just a hope."},
        {"title": "The Decision to Leave", "intro": "Choosing to leave a long-term relationship is a profound decision that deserves to be made carefully and then carried out with clarity.", "sections": [{"heading": "The Process", "body": ["Make the decision privately before announcing it. The conversation in which you end the relationship should not be the first time you are working out whether you have decided.", "Practical preparation: financial clarity, housing plan, support network, understanding of legal implications if married.", "Communicate the decision clearly and with compassion, once. Extended negotiation that reopens the question is painful for both people."]}], "callout": "Decide clearly before you speak. Then speak clearly."},
        {"title": "Life After the Relationship", "intro": "The relationship ends. The person continues.", "sections": [{"heading": "What Comes After", "body": ["Grief after relationship ending is real grief — the loss of a shared life, a shared identity, shared plans and dreams. It should be grieved, not rushed past.", "The quality of the next relationship is significantly determined by what is learned from the last one. The questions: what patterns did I bring? What did I need that I didn't ask for? What will I do differently?", "People who leave difficult relationships often discover, after the acute grief passes, a quality of relief and self-respect that the relationship had not allowed. That discovery is not a commentary on the relationship's value — it's a statement about what becomes possible when you choose yourself."]}], "callout": "You are not defined by the relationship that ended. You are defined by how you carry forward what it taught you."},
    ]
}

books = [b1, b2, b3, b4, b5, b6, b7, b8, b9, b10]
filenames = [
    "01 - Attachment Styles and Why You Love the Way You Do.pdf",
    "02 - Communication That Actually Connects.pdf",
    "03 - Recovering From Infidelity.pdf",
    "04 - The Art of Healthy Conflict.pdf",
    "05 - Loving Someone With Anxiety.pdf",
    "06 - Rebuilding Trust.pdf",
    "07 - Intimacy After Trauma.pdf",
    "08 - Parenting as Partners.pdf",
    "09 - Dating After 35.pdf",
    "10 - When to Leave and When to Stay.pdf",
]

for book, fname in zip(books, filenames):
    generate_ebook(os.path.join(OUT, fname), book)

print("SERIES 9 DONE")
