import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from generate_ebook import generate_ebook

OUT = os.path.dirname(__file__)
ACCENT = "#9B59B6"
BG = "#FAF0FF"
SERIES = "The Hormone Reset Series"

DISCLAIMER = """This book is intended for educational and informational purposes only. The content does not constitute medical, clinical, or professional health advice. The author and publisher are not licensed healthcare providers.

Nothing in this book should replace consultation with a qualified physician, endocrinologist, gynecologist, or other healthcare professional. Hormone health is highly individual and requires personalized clinical evaluation.

Always seek the advice of your doctor or qualified health provider with questions you may have regarding a medical condition or before starting any new health regimen. Never disregard professional medical advice or delay seeking it because of something you have read in this book."""

# ── Book 1 ────────────────────────────────────────────────────────────────────
b1 = {
    "title": "Cortisol and the Body Under Stress",
    "subtitle": "Understanding Your Stress Hormone and How to Work With It",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Cortisol Actually Is", "intro": "Cortisol has become a wellness villain. The truth is both simpler and more nuanced.", "sections": [
            {"heading": "The Hormone You Need", "body": ["Cortisol is a glucocorticoid hormone produced by the adrenal glands, and it is not optional. Without it, you would not be able to wake up in the morning, regulate blood pressure, manage inflammation, or respond to emergencies. It is essential, not toxic.", "The problem is not cortisol — it's chronically elevated cortisol in the absence of actual physical threat. Evolution designed this hormone to spike briefly during danger and then return to baseline after the threat passed. Modern life has hijacked that system with threats that never fully resolve: financial stress, relationship tension, work pressure, news cycles, traffic.", "Understanding cortisol means understanding it as a tool that's being misused — not a poison to be eliminated."]},
            {"heading": "The Cortisol Rhythm", "body": ["Healthy cortisol follows a diurnal pattern: highest within 30-45 minutes of waking (the cortisol awakening response, which helps you get going), gradually declining through the day, lowest in the evening to permit sleep.", "Chronic stress disrupts this pattern. The morning peak may be blunted (explaining exhaustion upon waking despite adequate sleep), levels may remain elevated through the evening (explaining racing thoughts at bedtime), or the pattern may flatten entirely.", "Before treating cortisol issues with supplements or elaborate protocols, understanding your own pattern — through symptom observation or formal saliva testing — provides a more targeted approach."]},
        ], "callout": "Cortisol isn't your enemy. Chronically elevated cortisol is."},
        {"title": "Signs Your Cortisol Is Out of Range", "intro": "The body communicates hormonal imbalance through systems that seem unrelated until you understand the connections.", "sections": [
            {"heading": "High Cortisol Signals", "body": ["Persistent central weight gain (particularly abdominal), difficulty falling asleep despite fatigue, anxiety or irritability without clear cause, blood sugar dysregulation, frequent illness or slow healing, thinning skin, and poor recovery from exercise can all reflect chronically elevated cortisol.", "High evening cortisol specifically presents as an activated, wired feeling when you should be winding down — difficulty being still, racing thoughts, a body that won't settle even when the mind is tired."]},
            {"heading": "Low Cortisol Signals", "body": ["Low cortisol — sometimes called adrenal fatigue in functional medicine, though this is a contested term — presents as profound morning fatigue, low blood pressure, salt cravings, dizziness upon standing, difficulty concentrating, and a general flatness of energy.", "Both extremes disrupt quality of life. Neither should be self-treated aggressively without professional input, particularly because cortisol is deeply interconnected with thyroid function, sex hormones, and immune regulation."]},
        ], "callout": "Symptoms are data. Learn to read them."},
        {"title": "Sleep as the Primary Reset Tool", "intro": "Every cortisol-modulating intervention pales compared to consistent, quality sleep. This is not optional information.", "sections": [
            {"heading": "The Sleep-Cortisol Loop", "body": ["Sleep and cortisol have a bidirectional relationship. Poor sleep elevates cortisol. Elevated cortisol disrupts sleep. Once the loop is established, it self-perpetuates.", "Breaking the loop requires intervening at both ends: improving sleep hygiene to create the conditions for lower evening cortisol, while reducing daytime stressors to allow natural evening wind-down.", "Practically: maintain a consistent wake time even on weekends (the single most impactful sleep intervention in research), stop all screens at least 60 minutes before bed, keep your sleeping space cool and dark, and treat the hour before bed as genuinely non-stimulating."]},
        ], "callout": "You cannot supplement your way out of a sleep deficit."},
        {"title": "Movement and Cortisol", "intro": "Exercise is a stress on the body — which is why the type, timing, and intensity all matter for cortisol regulation.", "sections": [
            {"heading": "The Exercise Paradox", "body": ["Moderate exercise reduces cortisol long-term by improving stress resilience and sleep quality. But high-intensity exercise chronically pursued without adequate recovery raises cortisol and can worsen the picture for people who are already running in survival mode.", "If you are exhausted, sleeping poorly, and your body composition is worsening despite training hard, you may be adding to a cortisol burden rather than reducing it. Counterintuitive but well-documented.", "The prescription for high cortisol: more walking, more restorative movement (yoga, swimming, gentle cycling), and less high-intensity training until the baseline improves. This is not giving up — it's strategic recovery."]},
        ], "callout": "More exercise is not always better. More recovery often is."},
        {"title": "Food, Blood Sugar, and the Cortisol Connection", "intro": "Every blood sugar spike triggers a cortisol response. Every cortisol spike is a blood sugar event. Understanding this loop changes how you eat.", "sections": [
            {"heading": "The Glycemic Cortisol Cycle", "body": ["Refined carbohydrates and sugar cause rapid blood glucose elevation followed by an insulin spike and subsequent drop. That blood sugar drop is experienced by the body as a mild stress emergency — and cortisol is released to raise blood sugar back up.", "For people with elevated cortisol, this cycle amplifies an already stressed system. Eating in ways that moderate blood sugar — prioritizing protein and fiber, eating regularly, minimizing refined sugar on an empty stomach — reduces the frequency of cortisol-triggering blood sugar swings.", "This isn't about eliminating carbohydrates. It's about sequencing and pairing them with protein and fat to slow glucose absorption."]},
        ], "callout": "Blood sugar stability is cortisol stability."},
        {"title": "Mind Practices That Actually Move the Needle", "intro": "Meditation apps and breathing exercises are real interventions with real physiological effects. The research is not ambiguous.", "sections": [
            {"heading": "What Works and Why", "body": ["Diaphragmatic breathing — slow, deep breaths that activate the diaphragm fully — directly activates the parasympathetic nervous system through the vagus nerve, reducing cortisol measurably within minutes. This is not metaphor. It is physiology.", "Even 10 minutes of slow breathing (inhale 4 counts, hold 4, exhale 6) practiced daily has been shown to reduce cortisol markers over weeks of consistent practice.", "Nature exposure, social connection with people you feel safe with, creative activities done without performance pressure, and time with animals all have documented cortisol-reducing effects. This is not hippie wellness advice — it's basic biology about which stimuli trigger the parasympathetic system."]},
        ], "callout": "Nervous system regulation is the most powerful free cortisol tool you have."},
    ]
}

# ── Book 2 ────────────────────────────────────────────────────────────────────
b2 = {
    "title": "Estrogen in Balance",
    "subtitle": "What Every Woman Needs to Know About Her Most Talked-About Hormone",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Estrogen Does (Beyond the Obvious)", "intro": "Estrogen affects your brain, your bones, your heart, your mood, and your metabolism. Its role is far larger than reproduction.", "sections": [
            {"heading": "The Systems Estrogen Touches", "body": ["Most people associate estrogen with female reproductive function — and it is central to that. But estrogen receptors are found throughout the body: in the brain (affecting mood, memory, and sleep), in bone tissue (preventing osteoporosis), in the cardiovascular system (influencing cholesterol and arterial flexibility), in the gut (affecting the microbiome), and in skin (influencing collagen production).", "This distribution is why estrogen changes — in perimenopause, after pregnancy, due to stress or illness — affect so many systems simultaneously. Hot flashes and mood changes and joint pain and sleep disruption are not unrelated complaints. They are a connected response to a single hormonal shift."]},
        ], "callout": "Estrogen is a whole-body hormone, not just a reproductive one."},
        {"title": "The Three Estrogens", "intro": "Estrogen is not a single hormone — it's a family. The distinction matters clinically.", "sections": [
            {"heading": "E1, E2, E3 — And Why They Matter", "body": ["Estrone (E1) is the primary estrogen in postmenopausal women, produced largely in fat tissue. Estradiol (E2) is the most potent form, dominant during reproductive years — the estrogen that cycles monthly and whose decline drives perimenopause symptoms. Estriol (E3) is the weakest form, elevated primarily during pregnancy.", "When practitioners discuss estrogen levels in testing, they are usually measuring estradiol. Estradiol's relationship to progesterone — the balance between them — is frequently more relevant than either in isolation.", "Estrogen dominance, a term commonly used in functional medicine, refers to an unfavorable ratio between estrogen and progesterone — not necessarily high estrogen in absolute terms."]},
        ], "callout": "Ratios often matter more than absolute levels."},
        {"title": "Estrogen Through the Life Stages", "intro": "Estrogen levels change significantly across the female lifespan. Each stage has its own hormonal landscape and its own common challenges.", "sections": [
            {"heading": "Reproductive Years to Perimenopause", "body": ["During the reproductive years, estradiol rises and falls monthly in coordination with the menstrual cycle. Many common experiences — PMS, mood changes before menstruation, menstrual migraines — are related to the rate of estrogen change rather than the level itself.", "In the late 30s and 40s, ovarian estrogen production begins to fluctuate irregularly — this is perimenopause, which can begin 8-10 years before the final menstrual period. During this transition, estrogen can swing dramatically: both higher than normal (causing heavy periods, breast tenderness) and lower (causing hot flashes, sleep disruption, vaginal dryness).", "Understanding that perimenopause is not a linear decline but an erratic fluctuation explains why symptoms are often confusing and variable."]},
        ], "callout": "Perimenopause is hormonal turbulence before the calm of menopause."},
        {"title": "Supporting Estrogen Metabolism", "intro": "How your body processes and clears estrogen matters as much as how much it produces.", "sections": [
            {"heading": "The Liver and Gut Connection", "body": ["Estrogen is metabolized primarily by the liver and then cleared through the gut. If either system is compromised, estrogen can be reabsorbed rather than excreted — contributing to estrogen excess symptoms.", "Cruciferous vegetables (broccoli, Brussels sprouts, cauliflower, kale) contain indole-3-carbinol and DIM, compounds that support healthy estrogen metabolism pathways in the liver. Fiber supports the gut's clearance role.", "Alcohol impairs liver metabolism of estrogen — this is one reason regular alcohol consumption is associated with elevated estrogen levels and increased breast cancer risk in research. This is not a moral statement; it's a metabolic one."]},
        ], "callout": "What your body does with estrogen matters as much as how much it makes."},
        {"title": "Environmental Estrogens", "intro": "Synthetic compounds that mimic estrogen in the body are ubiquitous in modern environments.", "sections": [
            {"heading": "Endocrine Disruptors — The Basics", "body": ["Endocrine disruptors are chemicals that interfere with hormone systems. Xenoestrogens — estrogen-mimicking compounds — are found in certain plastics (particularly BPA and phthalates), some pesticide residues, personal care products containing parabens, and certain industrial chemicals.", "The research on low-dose endocrine disruptor effects is still developing and genuinely complex. What is established: they bind to estrogen receptors, they can affect hormonal signaling, and reducing unnecessary exposure is a prudent precaution.", "Practical steps: store food in glass or stainless steel rather than plastic, avoid heating food in plastic containers, choose personal care products with simpler ingredient lists, and prioritize organic produce for the highest-pesticide crops when budget allows."]},
        ], "callout": "Small reductions in endocrine disruptor exposure add up over time."},
        {"title": "Working With Your Doctor on Estrogen", "intro": "Hormonal health benefits enormously from professional partnership. This chapter is about being an informed participant.", "sections": [
            {"heading": "Getting Tested and Understanding Results", "body": ["Estrogen testing is most meaningful when timed correctly in the cycle (day 3 for baseline, day 21 for progesterone comparison) and interpreted in context — not as an isolated number against a reference range.", "Serum blood testing, salivary testing, and urine testing (DUTCH test) each capture different aspects of hormonal health. Many integrative and functional medicine practitioners use expanded panels that assess multiple estrogen metabolites, which provides more clinical information than estradiol alone.", "Bring specific symptoms, cycle history, and sleep quality data to hormonal appointments. Quantified, specific symptom descriptions help clinicians form more accurate pictures than vague 'I don't feel well.'"]},
        ], "callout": "Being an informed patient is not the same as self-treating. Both are necessary."},
    ]
}

# ── Book 3 ────────────────────────────────────────────────────────────────────
b3 = {
    "title": "Thyroid Health Simplified",
    "subtitle": "Understanding the Gland That Runs Your Metabolism",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What the Thyroid Actually Does", "intro": "The thyroid is small, butterfly-shaped, and responsible for more bodily functions than most people realize.", "sections": [
            {"heading": "The Metabolic Master Switch", "body": ["Every cell in your body has thyroid hormone receptors. Thyroid hormones — primarily T3 and T4 — regulate the rate of virtually all metabolic activity: how quickly cells produce energy, how fast your heart beats, how efficiently your digestive system moves, your body temperature, your cognitive speed, and the rate at which your body breaks down fat.", "A well-functioning thyroid operates almost invisibly — you feel energetic, your weight is stable without extraordinary effort, your mind is clear, your bowels regular. Its dysfunction is what makes it visible.", "Thyroid disorders are among the most common endocrine conditions, affecting an estimated 20 million Americans — and up to 60% are unaware of their condition."]},
        ], "callout": "When the thyroid is off, everything feels off — because everything is."},
        {"title": "Hypothyroidism and Its Many Faces", "intro": "Underactive thyroid is often missed for years because its symptoms mirror so many other conditions.", "sections": [
            {"heading": "Classic and Overlooked Symptoms", "body": ["Classic hypothyroid symptoms include fatigue, weight gain despite unchanged diet, cold intolerance, constipation, dry skin and hair, hair loss, brain fog, depression, and slow pulse.", "Less commonly recognized: puffy face especially in the morning, hoarse voice, elevated cholesterol (thyroid hormones affect lipid metabolism), carpal tunnel syndrome, joint pain, heavy or irregular periods, and memory impairment that can be mistaken for early cognitive decline.", "The challenge: any individual symptom is nonspecific. The pattern — especially combined with fatigue and cold intolerance — is more diagnostic. If you recognize several of these symptoms together, thyroid testing is a reasonable first step in conversation with your doctor."]},
        ], "callout": "The symptom pattern is more informative than any single symptom."},
        {"title": "Testing and Why TSH Isn't the Whole Picture", "intro": "Standard thyroid screening catches many cases and misses others. Knowing what to ask for helps.", "sections": [
            {"heading": "What the Tests Measure", "body": ["TSH (thyroid stimulating hormone) is the standard screening test — it measures the pituitary's signal to the thyroid, not thyroid output directly. Elevated TSH suggests the thyroid is underperforming (the pituitary is shouting louder because the thyroid isn't responding adequately).", "Free T4 and Free T3 measure the actual available thyroid hormones. Some people have 'normal' TSH but suboptimal free hormone levels, or conversion problems (converting T4 to the more active T3 inadequately).", "Thyroid antibodies (TPO and TgAb) identify autoimmune thyroid disease (Hashimoto's) which is the most common cause of hypothyroidism and can be active for years before TSH becomes abnormal. A complete thyroid panel includes all of these."]},
        ], "callout": "Ask for the full panel, not just TSH."},
        {"title": "Hashimoto's Thyroiditis", "intro": "The most common thyroid condition is autoimmune — and most people with it don't know.", "sections": [
            {"heading": "What Autoimmune Thyroid Disease Means", "body": ["Hashimoto's thyroiditis occurs when the immune system produces antibodies that attack thyroid tissue. Over time, this progressively reduces thyroid function, eventually leading to hypothyroidism in most cases.", "It is diagnosed by the presence of elevated thyroid peroxidase (TPO) or thyroglobulin antibodies, often before TSH becomes abnormal. This means Hashimoto's can cause symptoms — fatigue, brain fog, mood changes — while standard screening still reads 'normal.'", "Hashimoto's is more common in women and tends to run in families alongside other autoimmune conditions (celiac disease, rheumatoid arthritis, type 1 diabetes). A personal or family history of any autoimmune condition warrants antibody testing."]},
        ], "callout": "Hashimoto's is often present years before conventional thyroid numbers shift."},
        {"title": "Nutrition and the Thyroid", "intro": "Several nutrients are directly involved in thyroid hormone synthesis and function. Deficiencies are more common than most people realize.", "sections": [
            {"heading": "The Key Nutrients", "body": ["Iodine is required to synthesize thyroid hormones — both T4 (four iodine atoms) and T3 (three iodine atoms). Severe deficiency causes goiter and hypothyroidism. Excessive supplementation can also impair thyroid function and worsen autoimmune thyroid disease. Iodized salt and seafood are the primary dietary sources.", "Selenium is required for the conversion of T4 to the more active T3. Deficiency is associated with worse Hashimoto's outcomes. Brazil nuts (2 per day) are the most selenium-dense food source.", "Iron, zinc, and vitamin D all play supporting roles in thyroid function and are commonly deficient in people with thyroid disorders. Testing and addressing these through diet and supplementation (under professional guidance) can improve how thyroid treatment works."]},
        ], "callout": "Thyroid treatment works better when nutritional foundations are solid."},
        {"title": "Working With Your Healthcare Team", "intro": "Thyroid care benefits from a proactive patient who understands the basics.", "sections": [
            {"heading": "Having Productive Appointments", "body": ["Track symptoms over time — fatigue levels, weight changes, mood, bowel habits, temperature sensitivity. Bringing specific, dated observations gives your doctor more clinical information than 'I just feel off.'", "If you suspect Hashimoto's and only TSH has been tested, you can specifically request TPO and TgAb antibody testing. This is a reasonable clinical request.", "Some people with thyroid symptoms feel better on combination T4/T3 therapy versus T4 alone (levothyroxine). This is an area of active clinical discussion — not all practitioners are open to it, but it is a legitimate conversation to have if standard treatment isn't fully resolving symptoms."]},
        ], "callout": "Your lived experience is clinical data. Bring it to your appointments."},
    ]
}

# ── Book 4 ────────────────────────────────────────────────────────────────────
b4 = {
    "title": "Perimenopause Without Panic",
    "subtitle": "What's Happening, Why It Matters, and What You Can Do About It",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Transition Nobody Warned You About", "intro": "Most women know menopause is coming. Almost none of them are told about the 4-to-10 years before it.", "sections": [
            {"heading": "Perimenopause: The Definition", "body": ["Perimenopause is the hormonal transition period leading up to menopause (defined as 12 consecutive months without a period). It typically begins in the mid-40s, though it can start in the late 30s, and lasts an average of 4-8 years.", "During perimenopause, ovarian hormone production becomes erratic — not uniformly declining, but fluctuating unpredictably. Estrogen can spike higher than premenopausal levels in some cycles, then plummet. Progesterone declines more steadily.", "This erratic pattern — rather than steady decline — is why perimenopause symptoms are often confusing and inconsistent. A woman may feel fine one week and symptomatic the next, with no apparent explanation."]},
        ], "callout": "Perimenopause is the storm before the calm, not the beginning of the end."},
        {"title": "The Symptom Spectrum", "intro": "The perimenopause symptom list is longer and stranger than most people expect.", "sections": [
            {"heading": "Beyond Hot Flashes", "body": ["Hot flashes and night sweats are the most recognized perimenopausal symptoms. But the full picture includes: sleep disruption (often the first symptom, preceding other changes by years), mood changes (anxiety, irritability, or low mood that feels different from previous experience), cognitive changes (brain fog, word-finding difficulties, memory lapses), joint pain, palpitations, headaches, changed body composition (fat redistribution toward the abdomen), and libido changes.", "Some women experience heavy, irregular, or more frequent periods. Others experience skipping. Both are normal features of the transition.", "The age at which these symptoms appear is often the most disorienting part — many women in their early-to-mid 40s do not expect to be in perimenopause and may seek other explanations first."]},
        ], "callout": "If multiple systems seem to be changing simultaneously, hormones are worth investigating."},
        {"title": "Sleep in Perimenopause", "intro": "Sleep disruption in perimenopause is hormonally driven — and therefore responds to different interventions than ordinary insomnia.", "sections": [
            {"heading": "Why Perimenopausal Sleep Breaks Down", "body": ["Progesterone has direct sedative effects — it binds to GABA receptors (the same receptor that sleep medications target) and promotes sleep onset and maintenance. As progesterone declines in perimenopause, this sedative effect diminishes.", "Night sweats interrupt sleep architecture even when they don't fully wake you, fragmenting sleep and reducing restorative deep sleep stages. The result is often waking feeling exhausted despite spending adequate time in bed.", "Estrogen decline also affects serotonin and melatonin signaling, further disrupting the sleep-wake cycle.", "Standard sleep hygiene helps but may not be sufficient when the root cause is hormonal. This is an appropriate conversation to have with a healthcare provider who has expertise in menopause medicine."]},
        ], "callout": "Perimenopausal insomnia often has a hormonal root that sleep hygiene alone won't resolve."},
        {"title": "Lifestyle Modifications That Work", "intro": "Several evidence-based lifestyle changes reduce perimenopause symptom burden. These are not instead of medical care — they are alongside it.", "sections": [
            {"heading": "The Evidence-Based Short List", "body": ["Strength training: preserves muscle mass (which declines with estrogen loss), supports bone density, improves metabolic health, and has documented mood benefits. Two to three sessions per week of progressive resistance work is among the most robustly beneficial interventions for perimenopausal women.", "Reducing alcohol: alcohol directly disrupts sleep architecture and triggers hot flashes in many women. Even moderate intake (1-2 drinks) measurably worsens sleep quality.", "Stress reduction: elevated cortisol worsens hot flash frequency and sleep disruption. Mind-body practices (yoga, meditation, slow breathing) have documented effects on vasomotor symptoms.", "Cooling the sleeping environment: lowering bedroom temperature to 65-67°F reduces the frequency and severity of night sweats."]},
        ], "callout": "Small consistent changes in lifestyle can meaningfully reduce symptom burden."},
        {"title": "Hormone Therapy — The Honest Overview", "intro": "The history of HRT is complicated. The current evidence is clearer. You deserve an accurate summary.", "sections": [
            {"heading": "What the Research Actually Shows", "body": ["The 2002 Women's Health Initiative study significantly frightened women and physicians away from hormone therapy for over two decades. Subsequent analysis revealed the study's design limitations: participants were older (average age 63) and had been postmenopausal for an average of 12 years before starting therapy — very different from treating symptoms in perimenopause.", "Current evidence, summarized by the Menopause Society (formerly NAMS), indicates that for healthy women under 60 or within 10 years of menopause onset, the benefits of hormone therapy generally outweigh risks for bothersome vasomotor symptoms.", "Bioidentical hormones (structurally identical to human hormones), transdermal delivery (patches, gels, creams — which bypass first-pass liver metabolism), and progesterone type all affect the risk-benefit calculation. This is a nuanced discussion best had with a menopause-knowledgeable clinician."]},
        ], "callout": "The HRT conversation has changed significantly. Work with a provider who knows the current evidence."},
        {"title": "The Long Game: Bone and Cardiovascular Health", "intro": "Estrogen decline doesn't just cause symptoms. It changes long-term health risk profiles.", "sections": [
            {"heading": "Investing in the Next 40 Years", "body": ["Estrogen has protective effects on bone and cardiovascular tissue. Its decline during menopause accelerates bone loss (women lose up to 20% of bone density in the 5-7 years following menopause) and shifts the cardiovascular risk profile toward that of men.", "This is not to alarm — it's to orient. The lifestyle interventions that manage perimenopausal symptoms (strength training, good nutrition, adequate protein, stress management) are the same interventions that support bone and cardiovascular health long-term.", "Annual conversations with your doctor about bone density (DEXA scan), cardiovascular risk markers, and long-term preventive strategy become more important, not less, as you navigate this transition. This is the decade to establish those patterns."]},
        ], "callout": "The healthiest menopause is the one you actively prepare for."},
    ]
}

# ── Book 5 ────────────────────────────────────────────────────────────────────
b5 = {
    "title": "Insulin Resistance Explained",
    "subtitle": "What It Is, Why It Happens, and How to Reverse It",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Most Common Hormonal Problem You've Heard the Least About", "intro": "Insulin resistance affects an estimated 1 in 3 American adults. Most of them don't know it.", "sections": [
            {"heading": "What Insulin Does", "body": ["Insulin is a peptide hormone produced by the pancreatic beta cells. Its primary job is to act as a key — unlocking cells to allow glucose (blood sugar) to enter and be used for energy.", "After eating, blood glucose rises. The pancreas releases insulin. Cells respond to insulin by absorbing glucose. Blood sugar returns to normal. This cycle, working smoothly, keeps energy balanced.", "Insulin resistance occurs when cells progressively stop responding well to insulin's signal. The pancreas compensates by producing more insulin. For a time, blood sugar stays normal — but it requires increasingly large insulin doses to achieve this. Eventually, the system can't keep up, and blood sugar begins to rise."]},
        ], "callout": "Insulin resistance is a spectrum that begins silently and progresses gradually."},
        {"title": "Recognizing the Signs", "intro": "Insulin resistance rarely announces itself — it whispers for years before shouting.", "sections": [
            {"heading": "The Symptom Profile", "body": ["Persistent fatigue, particularly after carbohydrate-heavy meals. Difficulty losing weight despite reasonable diet and exercise. Central abdominal fat that seems resistant to intervention. Skin tags, particularly around the neck and armpits. Acanthosis nigricans — darkened, velvety skin in skin folds. Brain fog after meals. Intense carbohydrate cravings. Waking in the night (blood sugar fluctuations disrupt sleep).", "Polycystic ovarian syndrome (PCOS) is deeply linked to insulin resistance, and many of the hallmark features of PCOS — irregular periods, elevated androgens, difficulty with weight — are driven by or worsened by insulin resistance.", "Many people with significant insulin resistance have 'normal' fasting blood glucose — because the elevated insulin is still doing its job. Fasting insulin, hemoglobin A1c, and the HOMA-IR calculation give a more complete picture."]},
        ], "callout": "Normal blood sugar on a standard test does not rule out insulin resistance."},
        {"title": "The Role of Diet", "intro": "Dietary changes are the most powerful evidence-based intervention for insulin resistance.", "sections": [
            {"heading": "What Helps", "body": ["Reducing the frequency and quantity of foods that cause rapid blood sugar spikes — refined carbohydrates, sugary drinks, processed snacks — directly reduces the demand for insulin and gives cells time to recover sensitivity.", "This does not require elimination of all carbohydrates. It requires choosing carbohydrates that are paired with fiber, protein, or fat (which slow glucose absorption), prioritizing whole food sources, and managing portion sizes of high-glycemic foods.", "Vinegar (particularly apple cider vinegar) taken before meals has modest but consistent evidence for reducing post-meal blood sugar spikes — a simple, low-cost intervention worth incorporating.", "Protein at every meal supports satiety and has minimal effect on blood sugar — making it a key ally in restructuring the diet."]},
        ], "callout": "You don't have to eat perfectly. You have to eat differently."},
        {"title": "Movement as Medicine", "intro": "Muscle is the largest glucose sink in the body. Using it changes insulin dynamics profoundly.", "sections": [
            {"heading": "Why Exercise Works for Insulin Resistance", "body": ["Skeletal muscle absorbs glucose during and after exercise through an insulin-independent pathway. This means that muscle movement clears blood sugar without needing insulin to open the door — bypassing the resistance mechanism entirely.", "A 10-15 minute walk after meals has been shown in multiple studies to reduce post-meal blood sugar spikes significantly — more effectively than a longer walk at a different time of day.", "Resistance training is particularly powerful for insulin resistance because it increases muscle mass, creating more glucose storage capacity. Two to three sessions per week of progressive strength training is among the most evidence-based interventions available — on par with some medications."]},
        ], "callout": "A short walk after eating is one of the most underused metabolic tools available."},
        {"title": "Sleep and Stress in Insulin Resistance", "intro": "Two seemingly non-dietary factors have enormous impact on glucose metabolism.", "sections": [
            {"heading": "The Evidence", "body": ["A single night of poor sleep (under 6 hours) reduces insulin sensitivity the next day by 25% in controlled studies. Chronic poor sleep is a direct driver of insulin resistance progression.", "Cortisol, released during stress, directly raises blood sugar through gluconeogenesis — the liver releasing stored glucose into the bloodstream. Chronic stress chronically elevates blood sugar. This is a significant but underappreciated driver of insulin resistance in people under high occupational or psychological stress."]},
        ], "callout": "Sleep and stress management are metabolic interventions, not wellness extras."},
        {"title": "Testing, Tracking, and Working With Your Doctor", "intro": "Informed participation in your metabolic health is the most powerful tool you have.", "sections": [
            {"heading": "Key Tests to Request", "body": ["Fasting insulin: a normal-range fasting glucose with elevated fasting insulin indicates compensated insulin resistance before blood sugar rises — this is the early warning sign most standard panels miss.", "Hemoglobin A1c: measures average blood sugar over the preceding 2-3 months. Prediabetes range is 5.7-6.4%.", "Fasting lipid panel: insulin resistance characteristically raises triglycerides and lowers HDL — the lipid signature of metabolic dysfunction.", "Tracking your own post-meal blood sugar with a continuous glucose monitor (increasingly available without prescription) provides real-time data about how specific foods and activities affect your individual glucose response — data that no population-level guideline can replicate."]},
        ], "callout": "Understanding your numbers changes your relationship with your choices."},
    ]
}

# ── Book 6 ────────────────────────────────────────────────────────────────────
b6 = {
    "title": "Testosterone for Women",
    "subtitle": "The Hormone You Weren't Told About — and Why It Matters",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Women Have Testosterone Too", "intro": "Testosterone is not a male hormone. It's a human hormone that happens to be present in different amounts.", "sections": [
            {"heading": "What It Does in the Female Body", "body": ["Women produce testosterone in the ovaries and adrenal glands in amounts roughly 10-20 times lower than men — but this doesn't make it inconsequential. In women, testosterone influences libido, mood, energy, muscle maintenance, bone density, cognitive sharpness, and motivation.", "Symptoms of low testosterone in women include: diminished sexual desire (one of the most commonly reported but least commonly investigated complaints in women's health), fatigue that doesn't respond to sleep, loss of muscle mass and strength, reduced motivation or sense of drive, and blunted mood.", "These symptoms overlap with many other conditions — depression, thyroid disorders, perimenopause — which is why testosterone is often missed as a contributing factor."]},
        ], "callout": "Low testosterone in women is common and commonly overlooked."},
        {"title": "When Testosterone Is Too High", "intro": "Elevated androgens in women produce their own distinct set of challenges.", "sections": [
            {"heading": "PCOS and Androgen Excess", "body": ["Polycystic ovarian syndrome affects an estimated 10% of women of reproductive age and is the most common cause of androgen excess. Elevated testosterone in PCOS drives acne, hirsutism (unwanted facial and body hair), scalp hair thinning, and irregular or absent periods.", "PCOS is a complex condition with significant metabolic overlap — insulin resistance both drives and worsens androgen excess in many PCOS phenotypes.", "Other causes of elevated androgens include congenital adrenal hyperplasia, adrenal or ovarian tumors (rare), and certain medications. Any new-onset rapid androgen excess warrants medical evaluation."]},
        ], "callout": "Androgen imbalance in either direction has quality-of-life consequences worth addressing."},
        {"title": "Testing and Interpretation", "intro": "Testosterone testing in women is more complex than a single number suggests.", "sections": [
            {"heading": "What to Test and Why", "body": ["Total testosterone provides a gross measure. Free testosterone — the unbound, biologically active fraction — is more clinically relevant. Sex hormone binding globulin (SHBG) affects how much testosterone is free versus bound, and elevated SHBG (common with oral contraceptive use) can lower free testosterone significantly.", "Testing should be done in the morning and, for cycling women, during the same phase of the cycle for meaningful comparison. Results should be interpreted by a clinician familiar with female reference ranges — not those developed primarily from male physiology."]},
        ], "callout": "Context and clinical correlation matter more than a single number."},
        {"title": "Supporting Healthy Testosterone Levels Naturally", "intro": "Lifestyle factors influence androgen levels in both directions.", "sections": [
            {"heading": "Lifestyle Foundations", "body": ["Resistance training consistently and reliably increases testosterone in women — this is one of many reasons strength training is repeatedly highlighted as a cornerstone intervention across female hormone health.", "Adequate dietary fat is required for sex hormone synthesis. Very low fat diets reliably suppress testosterone (and other steroid hormones). Healthy fats from avocados, olive oil, eggs, and fatty fish support the lipid substrate hormones are built from.", "Zinc is required for testosterone synthesis. Chronic zinc deficiency impairs androgen production. Red meat, shellfish (especially oysters), pumpkin seeds, and legumes are dietary sources."]},
        ], "callout": "You can't build sex hormones without fat and zinc."},
        {"title": "Testosterone Therapy for Women", "intro": "Low-dose testosterone therapy for women is a growing area of clinical evidence — and still underutilized.", "sections": [
            {"heading": "The Current Evidence", "body": ["The strongest evidence for testosterone therapy in women exists for hypoactive sexual desire disorder (HSDD) — low sexual desire that causes distress. Multiple randomized controlled trials show benefit from low-dose testosterone.", "Evidence also supports benefit for fatigue, mood, and muscle maintenance in postmenopausal women, though this remains less established.", "Testosterone therapy in women is typically administered as a low-dose topical gel or cream. It is not FDA-approved for women in the US, but is prescribed off-label by practitioners familiar with female hormone health. This requires an honest conversation about the evidence, the risks, and the monitoring required."]},
        ], "callout": "The evidence for testosterone therapy in women is growing. Find a provider who knows it."},
        {"title": "Androgens Across the Lifespan", "intro": "Testosterone in women follows its own lifecycle, with peaks, declines, and clinical implications at each stage.", "sections": [
            {"heading": "The Trajectory", "body": ["Peak testosterone in women occurs in the mid-20s and declines gradually and continuously thereafter. By menopause, women have approximately half the testosterone they had at their peak.", "Surgical menopause (oophorectomy — removal of the ovaries) causes an abrupt 50% reduction in testosterone production and often produces more acute low-androgen symptoms than natural menopause.", "Oral contraceptives increase SHBG, which binds testosterone and reduces free levels — some women experience significant mood, libido, and energy changes on certain OCP formulations that are partially driven by this mechanism.", "Understanding the testosterone trajectory across your life informs conversations about energy, motivation, and wellbeing that might otherwise be attributed to 'just getting older.'"]},
        ], "callout": "Androgen health is part of lifelong hormone health, not just a reproductive-years concern."},
    ]
}

# ── Book 7 ────────────────────────────────────────────────────────────────────
b7 = {
    "title": "Gut Hormones and the Hunger Code",
    "subtitle": "Leptin, Ghrelin, and the Science of Why You Eat What You Eat",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "You Are Not Weak-Willed. You Have Hormones.", "intro": "The conversation about weight and eating that ignores hormones is the conversation missing the main character.", "sections": [
            {"heading": "The Hunger Hormones", "body": ["Hunger and satiety are regulated by a network of hormones, with leptin and ghrelin as the primary players. Ghrelin is the 'hunger hormone' — produced primarily in the stomach, it rises before meals and falls after eating, signaling hunger to the brain. Leptin is the 'satiety hormone' — produced by fat cells, it signals fullness and energy sufficiency to the hypothalamus.", "In a healthy metabolic state, these two hormones work in counterbalance to regulate appetite. In a dysregulated state — due to poor sleep, obesity, chronic stress, or restrictive dieting — this balance breaks down in ways that make hunger management genuinely physiologically difficult, not a matter of willpower."]},
        ], "callout": "Hunger is a hormone signal, not a moral choice."},
        {"title": "Leptin Resistance — When the Fullness Signal Stops Working", "intro": "You can have high leptin levels and still feel hungry all the time. This is leptin resistance.", "sections": [
            {"heading": "How It Develops", "body": ["Leptin resistance follows a pattern similar to insulin resistance: prolonged exposure to high leptin levels — typically associated with excess body fat — causes leptin receptors in the hypothalamus to become desensitized. The signal is high, but the receiver stops responding.", "The result is that the brain perceives starvation despite adequate energy stores, drives increased appetite, and reduces metabolic rate. This is a biological lock-in mechanism that explains why weight loss, once established, requires ongoing management.", "The factors that worsen leptin resistance overlap significantly with those driving insulin resistance: chronic inflammation, poor sleep, a diet high in processed foods, and sedentary behavior."]},
        ], "callout": "Leptin resistance makes your brain think you're starving while your body has plenty."},
        {"title": "Ghrelin, Sleep, and the Midnight Eating Drive", "intro": "If you eat more when you're tired, you're not lacking discipline. Your ghrelin is elevated.", "sections": [
            {"heading": "The Sleep-Appetite Connection", "body": ["A single night of poor sleep increases ghrelin levels and decreases leptin levels the following day. In practical terms: you feel hungrier, fullness signals are weaker, and cravings for calorie-dense, high-sugar foods are stronger.", "A landmark Stanford study found that participants sleeping under 6 hours had 15% lower leptin and 15% higher ghrelin than those sleeping 8 hours. In the same study, short sleepers ate an average of 300 calories more per day — approximately the caloric deficit required to lose one pound per week — wiped out entirely by poor sleep.", "Sleep is a metabolic intervention. Treating it as optional while trying to manage body composition is working against your own biology."]},
        ], "callout": "Sleep more. Eat less. Not discipline — physiology."},
        {"title": "GLP-1 and the New Frontier of Appetite Science", "intro": "GLP-1 receptor agonists have transformed the weight management landscape. Understanding the underlying biology helps frame what they're actually doing.", "sections": [
            {"heading": "What GLP-1 Is", "body": ["GLP-1 (glucagon-like peptide-1) is an incretin hormone produced in the gut in response to food. It stimulates insulin secretion, suppresses glucagon (which raises blood sugar), slows gastric emptying, and — critically — signals satiety to the brain's hypothalamic appetite centers.", "GLP-1 receptor agonist medications (semaglutide, liraglutide, tirzepatide) replicate and amplify this signal, producing significant reductions in appetite and food intake. The weight loss observed in clinical trials is directly related to reduced caloric intake driven by enhanced satiety signaling.", "Understanding GLP-1 biology reframes the discussion around these medications — they are not bypassing willpower or effort. They are restoring hormonal signaling that drives appropriate appetite regulation."]},
        ], "callout": "The science of appetite is the science of hormones. Both require respect."},
        {"title": "The Gut Microbiome and Metabolic Hormones", "intro": "Your gut bacteria influence the production of hormones that regulate hunger, metabolism, and mood.", "sections": [
            {"heading": "The Microbiome-Hormone Connection", "body": ["The gut microbiome — the trillions of bacteria inhabiting the digestive tract — communicates directly with the enteroendocrine system, influencing the production of hormones including GLP-1, ghrelin, and gut-brain signaling peptides.", "A microbiome characterized by high diversity and a favorable ratio of beneficial bacteria produces more short-chain fatty acids and other metabolites that support appetite regulation and metabolic health.", "Diet is the primary modifiable factor in microbiome composition. Fiber diversity — eating a wide variety of plant-based foods — consistently promotes microbiome health in research. The goal of 30 different plant foods per week (used in the American Gut Project research) is a useful practical target."]},
        ], "callout": "Feeding your microbiome is feeding your hormones."},
        {"title": "Practical Strategies for Hunger Regulation", "intro": "Understanding the system points toward practical interventions that work with the biology rather than against it.", "sections": [
            {"heading": "The Evidence-Based Short List", "body": ["Prioritize protein: protein is the most satiating macronutrient, producing the strongest GLP-1 and PYY response and reducing ghrelin more effectively than equivalent calories from carbohydrates or fat. Aim for protein at every meal.", "Eat slowly: gastric signals take 15-20 minutes to reach the brain's satiety centers. Eating quickly bypasses this system, producing overconsumption before the signal arrives. Slowing down is a direct intervention on the ghrelin-leptin loop.", "Protect sleep above all other interventions: no supplement, no diet pattern, no exercise protocol will compensate for the appetite-dysregulating effects of chronic sleep deprivation.", "Prioritize whole, fiber-rich foods: they slow gastric emptying (extending satiety), feed a healthy microbiome, and reduce the glycemic volatility that drives cortisol and secondary hunger signals."]},
        ], "callout": "Eat protein. Eat slowly. Sleep well. Everything else is refinement."},
    ]
}

# ── Book 8 ────────────────────────────────────────────────────────────────────
b8 = {
    "title": "Cycle Syncing",
    "subtitle": "How to Work With Your Hormonal Rhythm Instead of Against It",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Infradian Rhythm You Didn't Know You Had", "intro": "The 24-hour circadian clock gets all the attention. Women also operate on a 28-day ultradian cycle that affects everything from energy to cognition.", "sections": [
            {"heading": "What the Monthly Cycle Actually Is", "body": ["The menstrual cycle is not just a reproductive event. It's a monthly fluctuation in estrogen, progesterone, testosterone, LH, and FSH that affects brain function, metabolism, sleep, mood, physical strength, and immune function across its four phases.", "Phase 1 (menstruation): low estrogen and progesterone. Energy typically lower, inward orientation natural. Phase 2 (follicular): rising estrogen, increased energy, improved cognitive sharpness and social ease. Phase 3 (ovulation): estrogen peaks, testosterone rises, typically the highest energy and most extroverted phase. Phase 4 (luteal): progesterone rises then falls, energy more variable, premenstrual symptoms most common in the late luteal phase.", "These are not personality shifts. They are predictable neurochemical changes driven by hormone fluctuations."]},
        ], "callout": "Your energy is not random. It's cyclical."},
        {"title": "Exercise and the Cycle", "intro": "Strength, endurance, recovery, and injury risk all fluctuate with the cycle. Training accordingly isn't extra — it's efficient.", "sections": [
            {"heading": "Phase-Based Training", "body": ["Follicular and ovulatory phases (days 1-14): rising estrogen supports muscle recovery, improves neuromuscular coordination, and elevates pain tolerance. This is the optimal phase for higher-intensity training, new PRs, and skill-intensive work.", "Luteal phase (days 15-28): rising and falling progesterone increases core body temperature slightly, impairs heat dissipation, and elevates the stress response. Moderate-intensity training is often more productive than maximum effort. Research also shows increased ACL injury risk around ovulation — worth knowing for high-impact athletes.", "There is no phase in which rest is required unless symptoms are genuinely limiting. The adaptation is about optimizing effort, not restricting it."]},
        ], "callout": "Syncing training to your cycle is not an excuse to do less. It's a strategy to do more where it counts."},
        {"title": "Nutrition Across the Phases", "intro": "Metabolic rate, iron needs, and carbohydrate tolerance all shift across the menstrual cycle.", "sections": [
            {"heading": "What Changes and When", "body": ["Resting metabolic rate increases by approximately 100-300 calories in the luteal phase — meaning the body genuinely needs more fuel in the week before menstruation. Premenstrual increased appetite is a physiological response, not a lack of self-control.", "Iron loss during menstruation warrants attention, particularly in women with heavy cycles. Iron-rich foods (red meat, shellfish, lentils, dark leafy greens) and pairing iron sources with vitamin C to enhance absorption support replenishment.", "Magnesium needs may increase premenstrually — deficiency is associated with worse PMS symptoms including cramps and mood changes. Magnesium-rich foods include dark chocolate, pumpkin seeds, leafy greens, and almonds."]},
        ], "callout": "Increased appetite before your period is your metabolism talking. Listen to it."},
        {"title": "Mood, Cognition, and Hormonal Variability", "intro": "Understanding why you feel different at different times of your cycle is powerfully normalizing.", "sections": [
            {"heading": "The Hormone-Brain Connection", "body": ["Estrogen increases serotonin receptor sensitivity and supports dopamine production — explaining improved mood and cognitive sharpness in the follicular phase. Progesterone has calming GABA-like effects but can also cause fatigue and, in women sensitive to progesterone fluctuations, premenstrual mood changes.", "PMDD (premenstrual dysphoric disorder) represents the severe end of this spectrum — not 'normal PMS' but a clinical condition where the central nervous system responds abnormally to normal hormonal fluctuations. It affects 3-8% of women and is highly treatable. If premenstrual mood changes are significantly impairing function, clinical evaluation is warranted.", "Tracking your cycle with symptom notes for 2-3 months reveals individual patterns that help distinguish cycle-driven variability from other mood conditions."]},
        ], "callout": "Knowing when you're in a vulnerable phase is half the battle."},
        {"title": "Work and the Cycle", "intro": "Applying cycle awareness to how you schedule work, social commitments, and rest is the practical heart of cycle syncing.", "sections": [
            {"heading": "Scheduling With Biology", "body": ["This is not about limiting yourself based on hormones — it's about scheduling higher-demand activities when energy and cognition are typically at their natural peak, and scheduling lower-demand or more creative work during phases when those capacities are naturally reduced.", "Follicular phase: ideal for starting new projects, brainstorming, learning new skills, social commitments, difficult conversations. Luteal phase: ideal for detail work, finishing projects, solitary focus, administrative tasks. Menstrual phase: ideal for reflection, evaluation, planning, rest.", "Most people find that they were already unconsciously adapting to some of this variability. Making it conscious allows you to design your schedule rather than react to your energy."]},
        ], "callout": "Work with your cycle, not despite it."},
        {"title": "Cycle Syncing in Practice", "intro": "The first step is simply knowing where you are in your cycle. Everything else builds from there.", "sections": [
            {"heading": "Starting Simply", "body": ["Track your cycle for three months using a basic app or notebook: day 1 (first day of bleeding), approximate ovulation (usually days 12-16 for a 28-day cycle, confirmed by basal body temperature or cervical mucus changes), and subjective energy and mood notes.", "After three months, patterns become visible. The tracking itself is revelatory for most people who have never thought about their experience as cyclical rather than random.", "You don't need to restructure your entire life around your cycle to benefit from this awareness. Even small adjustments — scheduling the most demanding meeting in the follicular phase, planning rest on day one of your period, not making major decisions in the late luteal phase when anxiety tends to be higher — add up to a meaningfully more sustainable experience of life."]},
        ], "callout": "Awareness is the first adjustment. Everything else follows."},
    ]
}

# ── Book 9 ────────────────────────────────────────────────────────────────────
b9 = {
    "title": "Men's Hormonal Health",
    "subtitle": "Testosterone, Stress, Fatigue, and the Things Nobody Tells You",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Testosterone Conversation Men Avoid", "intro": "Testosterone is central to male health in ways that go far beyond the gym. And its decline is more common — and more impactful — than most men realize.", "sections": [
            {"heading": "What Testosterone Actually Does", "body": ["Testosterone drives libido, mood, energy, muscle mass, bone density, red blood cell production, cognitive sharpness, and competitiveness. It is not just a sex hormone — it is a systemic hormone with receptors in nearly every tissue.", "In men, testosterone peaks in the late teens and early 20s and declines approximately 1-2% per year after age 30. By 60, many men have testosterone levels significantly below their youthful peak — and an increasing number of younger men are presenting with low-normal levels far earlier than expected.", "Low testosterone (hypogonadism) is clinically defined but exists on a spectrum. Subclinical decline — levels technically within the normal range but at the lower end — produces real symptoms that often aren't investigated because the number is 'normal.'"]},
        ], "callout": "Low testosterone doesn't look like the stereotype. It looks like fatigue, irritability, and giving up."},
        {"title": "The Modern Testosterone Crisis", "intro": "Population-level testosterone levels in men have been declining for decades. This is not inevitable aging.", "sections": [
            {"heading": "Why Average Testosterone Has Declined", "body": ["Multiple studies show that average testosterone levels in men have dropped 20-30% since the 1980s, independent of age. A 60-year-old man today has significantly lower testosterone on average than a 60-year-old man in 1987.", "The leading hypotheses involve endocrine-disrupting chemicals (phthalates, BPA, pesticides), the obesity epidemic (adipose tissue converts testosterone to estradiol), sedentary lifestyles, chronic sleep deprivation, and chronic psychological stress.", "This is not a personal failing. It is a public health trend with identifiable causes — many of which are individually modifiable."]},
        ], "callout": "Declining testosterone is not destiny. Many causes are within your control."},
        {"title": "Lifestyle Factors That Support Testosterone", "intro": "Before considering medical intervention, the lifestyle variables that influence testosterone production are worth exhausting.", "sections": [
            {"heading": "The Evidence-Based List", "body": ["Sleep: testosterone is produced primarily during sleep, particularly during slow-wave sleep. Men who sleep under 5 hours per night have testosterone levels equivalent to someone 10-15 years older. Sleep is the single most impactful lifestyle variable for testosterone.", "Resistance training: heavy compound lifts (squats, deadlifts, bench press, rows) produce acute testosterone elevations and support long-term hormonal health better than cardio-only exercise programs.", "Body fat management: adipose tissue contains aromatase, the enzyme that converts testosterone to estradiol. Higher body fat means higher conversion rates and lower free testosterone. Body composition management directly affects testosterone levels.", "Zinc and vitamin D: both are required for testosterone synthesis. Deficiency in either impairs production. Both are commonly deficient in the modern population.", "Stress management: chronically elevated cortisol directly suppresses testosterone production. These two hormones operate in a seesaw relationship."]},
        ], "callout": "Sleep, strength training, and stress management are testosterone's foundation."},
        {"title": "When to Consider Medical Evaluation", "intro": "Lifestyle optimization has limits. Some cases warrant medical assessment and potentially treatment.", "sections": [
            {"heading": "The Clinical Picture", "body": ["Symptoms of low testosterone: persistent fatigue, reduced libido, erectile dysfunction, loss of muscle despite training, increased body fat, mood changes (depression, irritability, reduced motivation), cognitive changes, reduced bone density.", "Testing: total testosterone (morning sample — levels fluctuate diurnally, highest in the morning), free testosterone, LH, FSH, estradiol, SHBG, prolactin, and a complete metabolic panel. This panel identifies whether low testosterone is primary (testicular) or secondary (pituitary/hypothalamic) and rules out contributing conditions.", "Testosterone replacement therapy (TRT) has robust evidence for men with clinically low levels. It requires regular monitoring of hematocrit, PSA, and testosterone levels. The decision to start TRT should involve a urologist or endocrinologist with experience in men's hormone health."]},
        ], "callout": "Getting tested is not weakness. It's information."},
        {"title": "Estrogen in Men: The Underappreciated Variable", "intro": "Men produce estrogen too — and both too much and too little causes problems.", "sections": [
            {"heading": "The Balance", "body": ["Estradiol in men is essential: it supports bone density, cardiovascular health, libido, and cognitive function. Men who artificially suppress estrogen entirely (as sometimes happens with overly aggressive aromatase inhibitor use) develop osteoporosis, joint pain, and sexual dysfunction.", "Estrogen excess in men — common in obesity, due to elevated aromatase activity in fat tissue — suppresses the HPG axis, reducing testosterone production and causing symptoms including gynecomastia, reduced libido, mood changes, and water retention.", "The therapeutic goal in men's hormone health is appropriate testosterone-to-estrogen ratio, not maximum testosterone and minimum estrogen."]},
        ], "callout": "Estrogen in men is a balance problem, not an elimination problem."},
        {"title": "Mental Health and Male Hormones", "intro": "The relationship between testosterone, depression, and emotional regulation in men is real and underappreciated.", "sections": [
            {"heading": "What the Research Shows", "body": ["Low testosterone is associated with depression, anxiety, and reduced emotional resilience in men. The relationship is bidirectional — depression lowers testosterone, low testosterone worsens depression.", "Men are statistically less likely to report mood symptoms and less likely to be evaluated for hormonal contributors to those symptoms. The result is that men with hormonally driven depression often receive antidepressants without testosterone assessment, treating a symptom while missing a cause.", "Testosterone treatment in men with clinically low levels and comorbid depression often produces meaningful mood improvements — sometimes sufficient to resolve the depressive symptoms entirely. This is not an alternative to mental health care; it's a complementary piece of the picture."]},
        ], "callout": "Mood is hormonal. For men, testosterone is part of that conversation."},
    ]
}

# ── Book 10 ───────────────────────────────────────────────────────────────────
b10 = {
    "title": "Hormones After 50",
    "subtitle": "Navigating Menopause, Andropause, and the Long-Term Hormone Picture",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Hormone Shift at Midlife", "intro": "The hormonal changes at midlife are universal. The experience of them is not.", "sections": [
            {"heading": "What Changes and Why", "body": ["For women, menopause marks the end of ovarian estrogen and progesterone production. The transition (perimenopause) can take years; the aftermath (postmenopause) is a permanently altered hormonal landscape.", "For men, the parallel transition — sometimes called andropause or late-onset hypogonadism — is a gradual decline in testosterone and DHEA, less dramatic than menopause but cumulatively significant over years.", "Both transitions are normal biological events. But 'normal' doesn't mean they need to be endured without support. Understanding what is changing and what options exist is the beginning of an active approach."]},
        ], "callout": "Midlife hormonal change is normal. Suffering through it unnecessarily is not required."},
        {"title": "Bone Health: The Silent Long-Term Priority", "intro": "Bone density loss after midlife is one of the most consequential — and most preventable — consequences of hormonal change.", "sections": [
            {"heading": "The Scope of the Problem", "body": ["Osteoporosis affects approximately 10 million Americans; another 44 million have low bone density. One in two women and one in four men over 50 will experience an osteoporosis-related fracture in their lifetime.", "Hip fractures in older adults carry a mortality rate of 20-30% within one year. Vertebral fractures cause chronic pain, height loss, and disability. These are not inevitable — they are largely preventable with appropriate attention beginning in midlife.", "The most important time to protect bone is the decade before and immediately after the major hormonal transition, when bone loss accelerates most rapidly."]},
            {"heading": "Building and Maintaining Bone", "body": ["Weight-bearing exercise and resistance training are the most powerful non-pharmacological interventions for bone density. Bone responds to mechanical load — it remodels to meet demand. Sedentary adults lose bone; loading adults maintain and rebuild it.", "Calcium and vitamin D are essential cofactors — vitamin D3 at doses sufficient to maintain serum 25-OH-D above 40 ng/mL, paired with dietary or supplemental calcium at recommended levels. Magnesium and vitamin K2 play supporting roles in calcium metabolism and bone mineralization.", "DEXA scan (dual-energy X-ray absorptiometry) is the standard bone density test. Baseline scan at menopause (or at 65 if no risk factors) allows meaningful tracking over time."]},
        ], "callout": "Bone loss is silent. Monitoring and intervention make it visible and manageable."},
        {"title": "Cardiovascular Health and Hormone Loss", "intro": "Estrogen and testosterone both have cardiovascular protective effects. Their decline changes the risk profile.", "sections": [
            {"heading": "What Changes After Menopause", "body": ["Premenopausal women have lower rates of cardiovascular disease than age-matched men — a protection largely attributed to estrogen's effects on lipid profiles, arterial flexibility, and anti-inflammatory properties.", "After menopause, this protection diminishes. LDL cholesterol typically rises, HDL may fall, and arterial stiffness increases. Within 10 years of menopause, women's cardiovascular risk approaches that of men.", "This is not inevitable. The lifestyle interventions that protect cardiovascular health — regular aerobic exercise, a diet rich in vegetables and fiber and low in ultra-processed food, not smoking, maintaining healthy blood pressure — have the same or greater impact in postmenopausal women as in any other demographic."]},
        ], "callout": "The cardiovascular protection of your reproductive years can be extended with intention."},
        {"title": "Brain Health and Hormones", "intro": "Estrogen and testosterone both affect cognitive function and long-term brain health. The emerging research is important.", "sections": [
            {"heading": "The Cognitive Transition", "body": ["Many women report cognitive changes during perimenopause — word-finding difficulties, memory lapses, reduced processing speed — that are often attributed to stress or aging but may be primarily hormonal. These changes are typically temporary during the transition, resolving after the hormonal environment stabilizes.", "The longer-term relationship between estrogen and Alzheimer's risk is an active research area. Current evidence suggests that the timing of hormone therapy initiation matters — the 'critical window hypothesis' proposes that early initiation (within 10 years of menopause or before age 60) may have neuroprotective effects that late initiation does not.", "Both estrogen and testosterone support brain health through multiple mechanisms: anti-inflammatory effects, support of neuronal energy metabolism, synaptic plasticity, and amyloid clearance. This is an evolving field worth staying current on."]},
        ], "callout": "Protecting the brain is a lifelong project. Hormones are one piece of it."},
        {"title": "Hormone Therapy at 50 and Beyond", "intro": "The decision about hormone therapy in postmenopause involves individual risk assessment, personal symptom burden, and current evidence.", "sections": [
            {"heading": "Who Benefits Most", "body": ["The evidence most clearly supports hormone therapy for women with significant vasomotor symptoms, genitourinary syndrome of menopause (vaginal dryness, recurrent UTIs, sexual discomfort), and osteoporosis risk — particularly when initiated within 10 years of menopause.", "Localized vaginal estrogen (cream, ring, or tablet) is effective for genitourinary symptoms with minimal systemic absorption, making it appropriate for many women who cannot or choose not to use systemic therapy.", "The risk-benefit calculation changes as time from menopause increases. Women who are 15-20 years postmenopausal initiating therapy for the first time face a different picture than those managing the transition actively. This is a discussion with a menopause-specialist clinician, not a one-size answer."]},
        ], "callout": "Hormone therapy is a tool. Whether to use it is a personal decision made with good information."},
        {"title": "Thriving in the Second Half", "intro": "The hormonal second half of life is not a decline. It's a different terrain with its own strengths.", "sections": [
            {"heading": "Reframing Midlife and Beyond", "body": ["The medicalization of menopause and aging has, in some ways, framed the postmenopausal years primarily as a period of loss — lost fertility, lost hormones, lost vitality. This framing is both inaccurate and unhelpful.", "Research on wellbeing across the lifespan consistently shows that life satisfaction often increases after 50. The postmenopausal years, when navigated well, can be characterized by clarity, confidence, reduced concern about others' approval, and genuine self-knowledge.", "The same attention to sleep, nutrition, movement, stress management, and purposeful connection that supports hormonal health supports the full picture of thriving in midlife and beyond. These are not medical interventions. They are how human beings were designed to live — and in the second half of life, they matter more, not less."]},
        ], "callout": "The second half is not a decline. It's a different kind of strength."},
    ]
}

books = [b1, b2, b3, b4, b5, b6, b7, b8, b9, b10]
filenames = [
    "01 - Cortisol and the Body Under Stress.pdf",
    "02 - Estrogen in Balance.pdf",
    "03 - Thyroid Health Simplified.pdf",
    "04 - Perimenopause Without Panic.pdf",
    "05 - Insulin Resistance Explained.pdf",
    "06 - Testosterone for Women.pdf",
    "07 - Gut Hormones and the Hunger Code.pdf",
    "08 - Cycle Syncing.pdf",
    "09 - Men's Hormonal Health.pdf",
    "10 - Hormones After 50.pdf",
]

for book, fname in zip(books, filenames):
    generate_ebook(os.path.join(OUT, fname), book)

print("SERIES 5 DONE")
