"""
Instagram Automation Config
10 series pages — 2 carousels/day + 1 story/day per page
Stack: Gemini 2.0 Flash (free) + Instagram Graph API + GitHub Actions
"""

SERIES_PAGES = [
    {
        "series_id": 1,
        "name": "The Somatic Reset Series",
        "niche": "somatic healing, nervous system regulation, body-based trauma recovery",
        "accent_hex": "#1ABC9C",
        "ig_page_username": "somaticshift",
        "ig_access_token_env": "IG_TOKEN_SOMATIC",
        "ig_user_id_env": "IG_USER_ID_SOMATIC",
        "bio_cta": "Your nervous system isn't broken — it's stuck 📚 10-book bundle 👇",
        "bundle_tagline": "Reset your nervous system. Reclaim your body.",
        "books": [
            {"num": 1,  "title": "The Vagus Nerve Reset",          "subtitle": "Rewire Your Nervous System for Calm"},
            {"num": 2,  "title": "Trauma Stored in the Body",       "subtitle": "Understanding Somatic Memory"},
            {"num": 3,  "title": "The Freeze Response",             "subtitle": "Why You Shut Down and How to Thaw"},
            {"num": 4,  "title": "Breathwork for Survival Mode",    "subtitle": "Breathe Your Way Out of Stress"},
            {"num": 5,  "title": "Grounding When the World Spins",  "subtitle": "Embodied Techniques for Anxiety"},
            {"num": 6,  "title": "The Tension Release Method",      "subtitle": "Let Go of What the Body Holds"},
            {"num": 7,  "title": "Somatic Boundaries",              "subtitle": "Feeling Safe in Your Own Skin"},
            {"num": 8,  "title": "The Gut-Brain Reset",             "subtitle": "How Your Belly Holds Your Emotions"},
            {"num": 9,  "title": "Sleep and the Nervous System",    "subtitle": "Why You Can't Switch Off at Night"},
            {"num": 10, "title": "Living Regulated",                "subtitle": "A Life Beyond Survival Mode"},
        ],
        "hashtags": [
            "#somatichealing", "#nervoussystemhealing", "#vagusnerve", "#traumarecovery",
            "#somatictherapy", "#bodymindhealing", "#polyvagaltheory", "#traumainformed",
            "#nervousystemregulation", "#healyourself", "#somaticwork", "#bodymind",
            "#anxietyrelief", "#healingjourney",
        ],
    },
    {
        "series_id": 2,
        "name": "The GLP-1 Lifestyle Series",
        "niche": "GLP-1 medications, sustainable weight loss, metabolic health",
        "accent_hex": "#3498DB",
        "ig_page_username": "glp1decoded",
        "ig_access_token_env": "IG_TOKEN_GLP1",
        "ig_user_id_env": "IG_USER_ID_GLP1",
        "bio_cta": "The GLP-1 guide no one gave you 📚 Full 10-book bundle 👇",
        "bundle_tagline": "Everything you need to know about GLP-1 — in one bundle.",
        "books": [
            {"num": 1,  "title": "GLP-1 Explained",                  "subtitle": "What These Medications Actually Do"},
            {"num": 2,  "title": "Eating on GLP-1",                  "subtitle": "Nutrition That Works With the Medication"},
            {"num": 3,  "title": "Managing Side Effects",            "subtitle": "Nausea, Fatigue, and What's Normal"},
            {"num": 4,  "title": "The Muscle Question",              "subtitle": "Preserving Strength While Losing Weight"},
            {"num": 5,  "title": "Mental Shifts on GLP-1",           "subtitle": "When Food No Longer Controls You"},
            {"num": 6,  "title": "Exercise and GLP-1",               "subtitle": "Moving Your Body at Every Stage"},
            {"num": 7,  "title": "Coming Off GLP-1",                 "subtitle": "Transitioning Without Gaining It Back"},
            {"num": 8,  "title": "GLP-1 for Type 2 Diabetes",        "subtitle": "Beyond Weight Loss"},
            {"num": 9,  "title": "The Emotional Weight",             "subtitle": "Body Image, Identity, and the Scale"},
            {"num": 10, "title": "Sustaining the Results",           "subtitle": "Life After the Medication"},
        ],
        "hashtags": [
            "#glp1", "#ozempicjourney", "#weightlossjourney", "#metabolichealth",
            "#glp1community", "#semaglutide", "#wegovy", "#ozempic",
            "#healthyweightloss", "#diabetesmanagement", "#insulinresistance",
            "#sustainableweightloss", "#glp1lifestyle", "#healthtransformation",
        ],
    },
    {
        "series_id": 3,
        "name": "The ADHD Blueprint Series",
        "niche": "ADHD management, executive function, neurodiversity, focus strategies",
        "accent_hex": "#E67E22",
        "ig_page_username": "rewiredadhd",
        "ig_access_token_env": "IG_TOKEN_ADHD",
        "ig_user_id_env": "IG_USER_ID_ADHD",
        "bio_cta": "ADHD doesn't hold you back — this does 📚 Full blueprint 👇",
        "bundle_tagline": "10 books. One complete ADHD operating manual.",
        "books": [
            {"num": 1,  "title": "How the ADHD Brain Works",         "subtitle": "Finally, an Explanation That Makes Sense"},
            {"num": 2,  "title": "The Executive Function Playbook",  "subtitle": "Systems for the Systemless Mind"},
            {"num": 3,  "title": "ADHD and Emotions",                "subtitle": "Rejection, Rage, and Riding the Waves"},
            {"num": 4,  "title": "Focus on Demand",                  "subtitle": "Getting Things Done Without Willpower"},
            {"num": 5,  "title": "ADHD at Work",                     "subtitle": "Thriving in Environments Built for Others"},
            {"num": 6,  "title": "ADHD in Relationships",            "subtitle": "When One Partner Has ADHD"},
            {"num": 7,  "title": "ADHD and Sleep",                   "subtitle": "Why Your Brain Won't Shut Up at Night"},
            {"num": 8,  "title": "Women and ADHD",                   "subtitle": "The Late Diagnosis No One Saw Coming"},
            {"num": 9,  "title": "Medication Questions Answered",    "subtitle": "The Honest Guide to ADHD Meds"},
            {"num": 10, "title": "Building Your ADHD Life",          "subtitle": "A System That Actually Fits You"},
        ],
        "hashtags": [
            "#adhd", "#adhdawareness", "#adhdlife", "#adhdadult",
            "#neurodiversity", "#adhdtips", "#executivefunction", "#adhdcoach",
            "#adhdcommunity", "#adhdwomen", "#neurodivergent", "#adhdmind",
            "#focustips", "#adhdlifestyle",
        ],
    },
    {
        "series_id": 4,
        "name": "The Money Healing Series",
        "niche": "money mindset, financial trauma, debt recovery, wealth psychology",
        "accent_hex": "#F7B731",
        "ig_page_username": "healyourmoney",
        "ig_access_token_env": "IG_TOKEN_MONEY",
        "ig_user_id_env": "IG_USER_ID_MONEY",
        "bio_cta": "Heal your relationship with money 💰 10-book bundle 👇",
        "bundle_tagline": "Money isn't just math. It's deeply personal.",
        "books": [
            {"num": 1,  "title": "The Scarcity Mindset Fix",         "subtitle": "Why You Never Feel Like You Have Enough"},
            {"num": 2,  "title": "Debt Without Shame",               "subtitle": "A Compassionate Path to Paying It Off"},
            {"num": 3,  "title": "First-Generation Wealth",          "subtitle": "Building What Nobody Taught You"},
            {"num": 4,  "title": "The Emotional Spender",            "subtitle": "What's Really Behind the Impulse Buy"},
            {"num": 5,  "title": "Side Income Without Burnout",      "subtitle": "Earning More Without Losing Yourself"},
            {"num": 6,  "title": "Money and Mental Health",          "subtitle": "The Anxiety-Finance Connection"},
            {"num": 7,  "title": "Negotiating Your Worth",           "subtitle": "Ask for More Without the Guilt"},
            {"num": 8,  "title": "The Minimalist Budget",            "subtitle": "Spend Less on What Doesn't Matter"},
            {"num": 9,  "title": "Investing for the Skeptic",        "subtitle": "For People Who Don't Trust the Market"},
            {"num": 10, "title": "Couples and Money",                "subtitle": "Having the Conversation That Changes Everything"},
        ],
        "hashtags": [
            "#moneymindset", "#financialhealing", "#debtfree", "#budgeting",
            "#moneytrauma", "#financialfreedom", "#personalfinance",
            "#wealthmindset", "#financialliteracy", "#debtpayoff",
            "#moneycoach", "#financetips", "#scarcitymindset", "#moneyhealing",
        ],
    },
    {
        "series_id": 5,
        "name": "The Hormone Reset Series",
        "niche": "hormonal health, cortisol balance, thyroid, perimenopause, cycle syncing",
        "accent_hex": "#9B59B6",
        "ig_page_username": "hormonecode",
        "ig_access_token_env": "IG_TOKEN_HORMONE",
        "ig_user_id_env": "IG_USER_ID_HORMONE",
        "bio_cta": "Balance your hormones. Reclaim your energy. 📚 Bundle 👇",
        "bundle_tagline": "Your hormones aren't broken — they're trying to tell you something.",
        "books": [
            {"num": 1,  "title": "Cortisol and the Body Under Stress","subtitle": "Why You're Wired and Tired at Once"},
            {"num": 2,  "title": "Estrogen in Balance",              "subtitle": "What Too Much or Too Little Really Means"},
            {"num": 3,  "title": "Thyroid Health Simplified",        "subtitle": "The Gland Everyone Ignores Until It Breaks"},
            {"num": 4,  "title": "Perimenopause Without Panic",      "subtitle": "What's Happening and What to Do About It"},
            {"num": 5,  "title": "Insulin Resistance Explained",     "subtitle": "The Hidden Driver Behind So Many Symptoms"},
            {"num": 6,  "title": "Testosterone for Women",           "subtitle": "Why You Need It and How to Support It"},
            {"num": 7,  "title": "Gut Hormones and the Hunger Code", "subtitle": "Why Willpower Has Nothing to Do With It"},
            {"num": 8,  "title": "Cycle Syncing",                    "subtitle": "Working With Your Hormones, Not Against Them"},
            {"num": 9,  "title": "Men's Hormonal Health",            "subtitle": "Testosterone, Stress, and the Silent Decline"},
            {"num": 10, "title": "Hormones After 50",                "subtitle": "The Second Chapter Nobody Prepared You For"},
        ],
        "hashtags": [
            "#hormonehealth", "#hormonebalance", "#cortisolbalance", "#thyroidhealth",
            "#perimenopause", "#hormonereset", "#insulinresistance", "#womenshealth",
            "#hormonalbalance", "#cyclicalliving", "#estrogendominance",
            "#menopauserelief", "#adrenalhealth", "#hormonehealing",
        ],
    },
    {
        "series_id": 6,
        "name": "The AI Professional Series",
        "niche": "AI tools for work, prompt engineering, career future-proofing, productivity",
        "accent_hex": "#2D9CDB",
        "ig_page_username": "promptmastery",
        "ig_access_token_env": "IG_TOKEN_AI",
        "ig_user_id_env": "IG_USER_ID_AI",
        "bio_cta": "Master AI before it masters your career 📚 Bundle 👇",
        "bundle_tagline": "AI isn't replacing you. Someone using AI will.",
        "books": [
            {"num": 1,  "title": "AI for the Overwhelmed Professional","subtitle": "Where to Start When Everything Feels Like Too Much"},
            {"num": 2,  "title": "Prompt Engineering for Non-Coders", "subtitle": "Get 10x Better Results From Any AI Tool"},
            {"num": 3,  "title": "AI for Freelancers",               "subtitle": "Charge More, Do More, Work Less"},
            {"num": 4,  "title": "AI Writing for Content Creators",  "subtitle": "Your Voice, Amplified"},
            {"num": 5,  "title": "AI for Small Business Owners",     "subtitle": "The Tools That Actually Save You Time"},
            {"num": 6,  "title": "AI Ethics for Everyday Users",     "subtitle": "What You Should Actually Be Concerned About"},
            {"num": 7,  "title": "The AI Job Search",                "subtitle": "Find Work Faster in a Competitive Market"},
            {"num": 8,  "title": "AI for Educators and Trainers",    "subtitle": "Teaching Smarter in the Age of AI"},
            {"num": 9,  "title": "AI Tools Compared",                "subtitle": "Honest Breakdown of What's Worth Your Time"},
            {"num": 10, "title": "Future-Proofing Your Career",      "subtitle": "Stay Relevant When Everything Keeps Changing"},
        ],
        "hashtags": [
            "#aitools", "#promptengineering", "#aiproductivity", "#futureofwork",
            "#artificialintelligence", "#chatgpt", "#aiforbusiness", "#aicareer",
            "#worksmarter", "#ailearning", "#aistrategy", "#techskills",
            "#digitaltransformation", "#aiprofessional",
        ],
    },
    {
        "series_id": 7,
        "name": "The Inner Healing Series",
        "niche": "inner child work, emotional healing, self-compassion, boundaries, shadow work",
        "accent_hex": "#E17055",
        "ig_page_username": "innerworkdaily",
        "ig_access_token_env": "IG_TOKEN_INNER",
        "ig_user_id_env": "IG_USER_ID_INNER",
        "bio_cta": "The healing starts from within 📚 Full 10-book series 👇",
        "bundle_tagline": "You can't think your way out of what you felt your way into.",
        "books": [
            {"num": 1,  "title": "Healing After Childhood Wounds",   "subtitle": "What You Carried Into Adulthood"},
            {"num": 2,  "title": "The Boundaries Blueprint",         "subtitle": "Saying No Without Guilt or Explanation"},
            {"num": 3,  "title": "Self-Compassion in Practice",      "subtitle": "Being as Kind to Yourself as You Are to Others"},
            {"num": 4,  "title": "Anger",                            "subtitle": "Understanding the Fire Within"},
            {"num": 5,  "title": "Loneliness and Connection",        "subtitle": "Finding Your People in an Isolated World"},
            {"num": 6,  "title": "The Highly Sensitive Person",      "subtitle": "A Guide to Thriving, Not Just Surviving"},
            {"num": 7,  "title": "Forgiveness Is for You",           "subtitle": "Letting Go Without Letting Them Off the Hook"},
            {"num": 8,  "title": "Emotional Intelligence",           "subtitle": "At Work, at Home, and in the Mirror"},
            {"num": 9,  "title": "Finding Purpose After Loss",       "subtitle": "When Everything Falls Apart"},
            {"num": 10, "title": "The Anxiety Reset",                "subtitle": "Breaking the Cycle From the Inside Out"},
        ],
        "hashtags": [
            "#innerhealing", "#innerchildwork", "#emotionalhealing", "#boundaries",
            "#selfcompassion", "#healingtrauma", "#shadowwork", "#mentalwellness",
            "#emotionalintelligence", "#healingjourney", "#selfawareness",
            "#personalgrowth", "#innerwork", "#healingcommunity",
        ],
    },
    {
        "series_id": 8,
        "name": "The Career Reset Series",
        "niche": "burnout recovery, career change, remote work, leadership, personal branding",
        "accent_hex": "#27AE60",
        "ig_page_username": "careerpivotlab",
        "ig_access_token_env": "IG_TOKEN_CAREER",
        "ig_user_id_env": "IG_USER_ID_CAREER",
        "bio_cta": "Your career on your terms 📚 10-book reset bundle 👇",
        "bundle_tagline": "Burned out, stuck, or starting over — this series is for you.",
        "books": [
            {"num": 1,  "title": "Burned Out and Starting Over",     "subtitle": "What to Do When Work Has Taken Everything"},
            {"num": 2,  "title": "The Introverted Professional",     "subtitle": "Thriving Without Pretending to Be an Extrovert"},
            {"num": 3,  "title": "Negotiating at Every Career Stage","subtitle": "How to Ask — and Actually Get It"},
            {"num": 4,  "title": "Remote Work Mastery",              "subtitle": "Productivity, Boundaries, and Visibility from Home"},
            {"num": 5,  "title": "The Career in Your 40s",           "subtitle": "It's Not Too Late to Change Everything"},
            {"num": 6,  "title": "Building a Personal Brand",        "subtitle": "That Actually Works and Doesn't Feel Fake"},
            {"num": 7,  "title": "Difficult Conversations at Work",  "subtitle": "Say the Hard Thing Without Burning Bridges"},
            {"num": 8,  "title": "Leadership Without Authority",     "subtitle": "Influence Without the Title"},
            {"num": 9,  "title": "The Consultant Mindset",           "subtitle": "Think Like a Freelancer, Even as an Employee"},
            {"num": 10, "title": "Work-Life Integration",            "subtitle": "Because Balance Was Always a Lie"},
        ],
        "hashtags": [
            "#careerreset", "#burnoutrecovery", "#careerchange", "#remotework",
            "#careergrowth", "#leadership", "#professionaldevelopment",
            "#worklifebalance", "#careeradvice", "#personalbrand",
            "#careertips", "#careerdevelopment", "#careercoach", "#workculture",
        ],
    },
    {
        "series_id": 9,
        "name": "The Relationship Reset Series",
        "niche": "attachment styles, relationship communication, trust, intimacy, dating",
        "accent_hex": "#E84393",
        "ig_page_username": "attachmentfix",
        "ig_access_token_env": "IG_TOKEN_RELATIONSHIP",
        "ig_user_id_env": "IG_USER_ID_RELATIONSHIP",
        "bio_cta": "Reset how you love 📚 Complete relationship series 👇",
        "bundle_tagline": "Love better. Connect deeper. Fight smarter.",
        "books": [
            {"num": 1,  "title": "Attachment Styles",                "subtitle": "Why You Love the Way You Do"},
            {"num": 2,  "title": "Communication That Connects",      "subtitle": "Actually Being Heard by the People You Love"},
            {"num": 3,  "title": "Recovering From Infidelity",       "subtitle": "Can You Stay? Can You Go? Can You Heal?"},
            {"num": 4,  "title": "The Art of Healthy Conflict",      "subtitle": "Fighting Without Destroying the Relationship"},
            {"num": 5,  "title": "Loving Someone With Anxiety",      "subtitle": "How to Support Without Losing Yourself"},
            {"num": 6,  "title": "Rebuilding Trust",                 "subtitle": "After It's Been Broken"},
            {"num": 7,  "title": "Intimacy After Trauma",            "subtitle": "Reconnecting When You've Shut Down"},
            {"num": 8,  "title": "Parenting as Partners",            "subtitle": "Staying a Couple While Raising Kids"},
            {"num": 9,  "title": "Dating After 35",                  "subtitle": "The Real Rules Nobody Told You"},
            {"num": 10, "title": "When to Leave, When to Stay",      "subtitle": "The Honest Questions to Ask Yourself"},
        ],
        "hashtags": [
            "#relationshipadvice", "#attachmentstyle", "#healthyrelationships",
            "#communication", "#trustbuilding", "#relationshiphealing",
            "#datingadvice", "#relationshiptips", "#emotionalintimacy",
            "#relationships", "#loveanddating", "#relationshipcoach",
            "#attachmenttheory", "#relationshipreset",
        ],
    },
    {
        "series_id": 10,
        "name": "The Calm Parent Series",
        "niche": "conscious parenting, emotional regulation, child development, discipline",
        "accent_hex": "#16A085",
        "ig_page_username": "raisecalm",
        "ig_access_token_env": "IG_TOKEN_CALM",
        "ig_user_id_env": "IG_USER_ID_CALM",
        "bio_cta": "Raise calm kids by becoming one first 📚 Bundle 👇",
        "bundle_tagline": "You can't pour from an empty cup — and neither can your kids.",
        "books": [
            {"num": 1,  "title": "The Regulated Parent",             "subtitle": "How Your Nervous System Shapes Your Child's"},
            {"num": 2,  "title": "Raising Emotionally Intelligent Kids","subtitle": "Feelings Are Data, Not Drama"},
            {"num": 3,  "title": "Screens and the Developing Brain", "subtitle": "What the Research Actually Says"},
            {"num": 4,  "title": "Discipline That Doesn't Damage",   "subtitle": "Firm, Kind, and Actually Effective"},
            {"num": 5,  "title": "Raising Kids Who Can Fail",        "subtitle": "Resilience Over Perfection"},
            {"num": 6,  "title": "Parenting the Anxious Child",      "subtitle": "How to Help Without Making It Worse"},
            {"num": 7,  "title": "Talking to Kids About Hard Topics","subtitle": "Death, Race, Bodies, and Everything In Between"},
            {"num": 8,  "title": "The Teenage Brain",                "subtitle": "Why They Do What They Do"},
            {"num": 9,  "title": "Single Parenting With Intention",  "subtitle": "Doing It Alone Without Doing It Wrong"},
            {"num": 10, "title": "Mindful Parenting",                "subtitle": "Showing Up When You're Running on Empty"},
        ],
        "hashtags": [
            "#consciousparenting", "#calmparenting", "#gentleparenting",
            "#parentingtips", "#emotionalintelligence", "#positiveparenting",
            "#childdevelopment", "#mindfulparenting", "#parentingadvice",
            "#raisingkids", "#parentinglife", "#attachmentparenting",
            "#parentingcommunity", "#calmparent",
        ],
    },
]

# GitHub Actions schedule: 2 carousels + 1 story per page per day
POST_TIMES_UTC = ["09:00", "18:00"]   # carousel 1, carousel 2
STORY_TIME_UTC = "12:00"              # story (midday)

GROQ_MODEL = "llama-3.3-70b-versatile"
GROQ_API_KEY_ENV = "GROQ_API_KEY"
