import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from generate_ebook import generate_ebook

OUT = os.path.dirname(__file__)
ACCENT = "#E17055"
BG = "#FFF8F5"
SERIES = "The Inner Healing Series"

DISCLAIMER = """This book is intended for educational and informational purposes only. It does not constitute medical, psychological, therapeutic, or clinical advice of any kind. The author and publisher are not licensed mental health professionals.

The practices and perspectives described are educational in nature and are not a substitute for professional psychological or psychiatric care. If you are experiencing significant distress, trauma responses, or mental health symptoms, please consult a qualified mental health professional.

Nothing in this book should be used to diagnose, treat, or manage any mental health condition."""

# ── Book 1 ────────────────────────────────────────────────────────────────────
b1 = {
    "title": "Healing After Childhood Wounds",
    "subtitle": "Understanding How the Past Lives in the Present — and What to Do About It",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Wound That Kept You Safe", "intro": "Every adaptive pattern you carry was once a solution. Understanding it that way changes everything.", "sections": [
            {"heading": "How Childhood Shapes the Adult", "body": ["The human brain develops most rapidly in the first five years of life — and develops in direct response to the environment it encounters. A child raised in an environment of safety, attunement, and consistent care develops a nervous system calibrated for connection. A child raised in unpredictability, neglect, or threat develops a nervous system calibrated for survival.", "Neither of these outcomes is a moral verdict. They are adaptations. The nervous system optimizes for the environment it lives in. The problem arises when you carry a nervous system optimized for a childhood environment into an adult life that is genuinely safer — and the optimization becomes a limitation rather than a protection."]},
            {"heading": "The Core Wounds", "body": ["Abandonment: an early experience of being left, literally or emotionally, that encodes as 'I will be left.' Adults with this wound often experience intense anxiety in relationships, difficulty trusting availability, and behavioral patterns that push people away while desperately wanting closeness.", "Shame: the pervasive sense of being fundamentally defective or unworthy — distinct from guilt (I did something bad) in being about identity (I am bad). Shame hides, and it hides itself. It shows up as perfectionism, overachievement, people-pleasing, or profound self-sabotage.", "Invisibility: the wound of not being seen, acknowledged, or mattered to. Adults carry this as chronic seeking of validation, a fragile sense of self that depends on external recognition, and difficulty identifying their own needs or preferences.", "Enmeshment: growing up without appropriate psychological boundaries — where your emotional job was to manage a parent's feelings rather than your own. Adults carry this as difficulty separating their own feelings from others', compulsive caretaking, and chronic guilt around self-care."]},
        ], "callout": "The wound isn't what happened to you. The wound is what you had to become to survive it."},
        {"title": "Recognizing the Patterns", "intro": "Childhood wounds don't look like childhood memories in adult life. They look like current behavior.", "sections": [
            {"heading": "The Pattern Recognition Practice", "body": ["The most useful question in healing work is not 'what happened to me?' but 'what keeps happening?' The patterns that repeat in relationships, at work, with authority, with intimacy — these are the wound in action.", "Write down the five most consistent complaints you receive from people close to you. Then write the five most consistent ways you respond to stress in relationships. Then ask: do these patterns remind me of anything from my family of origin? The answer is usually yes.", "This isn't about blame. It's about seeing the loop clearly enough to step out of it."]},
        ], "callout": "Recurring patterns are invitations. They are asking to be seen."},
        {"title": "The Reparenting Concept", "intro": "You cannot change your childhood. You can change what you offer your inner child now.", "sections": [
            {"heading": "What Reparenting Actually Is", "body": ["Reparenting is the practice of giving yourself now what you needed then — not to rewrite the past, but to update the present experience of self. It is providing the consistent attunement, encouragement, and soothing that an attuned parent would have provided, from yourself, now.", "This is not the same as self-indulgence or bypassing real problems. It is meeting legitimate developmental needs that weren't adequately met — needs for validation, comfort, encouragement, and unconditional regard — in an appropriate adult form.", "Practically: notice when you feel small, scared, ashamed, or abandoned. Before responding behaviorally, pause and ask: what does this part of me actually need right now? Then provide it — through self-talk, self-soothing, or deliberate self-care."]},
        ], "callout": "The most important relationship you'll ever repair is the one with yourself."},
        {"title": "Grief as Part of Healing", "intro": "Healing childhood wounds requires grieving the childhood you didn't have. Most people skip this step and wonder why they stall.", "sections": [
            {"heading": "The Grief Most People Avoid", "body": ["One of the most difficult aspects of childhood wound work is grieving not what happened, but what didn't happen — the attunement that was absent, the protection that wasn't there, the encouragement never given, the seeing and knowing and loving that was sparse or conditional.", "This grief often feels disloyal, especially toward parents who 'did their best.' Both things can be true: your parents did their best and their best was not enough. Grief doesn't require blame. It requires honesty.", "Ungrieved losses don't disappear. They live in the body as chronic low-level sadness, cynicism, or numbness — or in relationships as unconscious expectations that current partners will finally provide what parents didn't."]},
        ], "callout": "Grieving what you didn't have is how you stop expecting it from the wrong people."},
        {"title": "The Role of the Body in Childhood Healing", "intro": "Childhood experiences are stored in the body, not just in the mind. Healing that ignores the body is incomplete.", "sections": [
            {"heading": "Somatic Memory", "body": ["Research in developmental trauma and somatic psychology has established clearly: early experiences are encoded in the nervous system, in habitual muscle tension patterns, in breath patterns, in how the body holds itself. Talk therapy alone often doesn't reach this level of encoding.", "Body-oriented practices — somatic experiencing, EMDR, yoga, breathwork, expressive movement — access the body-stored aspects of early experience. They are not replacements for psychological work; they are complements that make psychological work more complete.", "Even without formal somatic therapy, noticing where in your body you feel childhood-wound emotions (the chest tightness of abandonment, the throat constriction of shame, the shoulder bracing of hypervigilance) and consciously breathing into those spaces is a beginning."]},
        ], "callout": "The body remembers what the mind has learned to skip over."},
        {"title": "When to Work With a Professional", "intro": "Some healing work is genuinely outside the scope of self-help. Knowing the difference is important.", "sections": [
            {"heading": "The Appropriate Help", "body": ["Self-education, journaling, somatic practices, and supportive community are meaningful parts of healing work. They are not sufficient for: complex developmental trauma, dissociative symptoms, active PTSD, significant depression or anxiety that impairs daily function, or early experiences of abuse or neglect.", "Trauma-informed therapy — EMDR, somatic experiencing, IFS (Internal Family Systems), ACT — has substantial evidence for healing developmental wounds. These modalities do not require you to relive experiences in detail or produce dramatic catharsis. They are gentle, evidence-based, and cumulative in their effects.", "Finding a therapist with specific training in developmental trauma or attachment is worth the extra search effort. The fit between therapist and client matters enormously — it's appropriate to interview several and trust your nervous system's response to them."]},
        ], "callout": "Seeking professional support for significant wounds is strength, not failure."},
    ]
}

# ── Book 2 ────────────────────────────────────────────────────────────────────
b2 = {
    "title": "The Boundaries Blueprint",
    "subtitle": "How to Say No Without Guilt and Yes Without Resentment",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Boundaries Actually Are", "intro": "Boundaries are not walls. They are not punishments. They are not rejection. They are a description of what works for you.", "sections": [
            {"heading": "The Misunderstanding", "body": ["Most people think of boundaries as aggressive or cold — something you do to people who've wronged you, or a way of keeping people at arm's length. This framing makes them feel unnatural, unkind, or reserved for severe situations.", "Boundaries are simply communication about your needs, limits, and values. 'I can't take on any more projects this month' is a boundary. 'I need 30 minutes alone after work before I'm available for conversation' is a boundary. 'I'm not comfortable with that kind of humor' is a boundary.", "None of these are hostile. They are honest. And people who care about you would rather know than not know."]},
        ], "callout": "Boundaries are information, not rejection."},
        {"title": "Why Boundaries Feel So Hard", "intro": "If boundaries were easy, everyone would have them. The difficulty is almost always rooted in something older than the current situation.", "sections": [
            {"heading": "The Roots of Boundary Difficulty", "body": ["Boundaries are hardest for people who grew up in environments where: their needs were treated as burdens, saying no produced consequences, their emotional job was to manage others' feelings, love felt conditional on compliance, or conflict was genuinely unsafe.", "These experiences produce adults who feel deep guilt when saying no, who read normal boundary-setting as abandonment or cruelty, who compulsively override their own needs to prevent others' discomfort — and who eventually feel profoundly resentful and depleted.", "Understanding this root doesn't eliminate the difficulty. But it explains why 'just say no' advice feels impossible — it's not a skill gap, it's a fear response."]},
        ], "callout": "Difficulty with boundaries is almost always a trauma response, not a character flaw."},
        {"title": "The Guilt — Working Through It", "intro": "Boundary guilt is almost never a sign that you've done something wrong. It's a sign that you've done something unfamiliar.", "sections": [
            {"heading": "Separating Guilt from Conscience", "body": ["Genuine conscience says: you've caused real harm to someone who didn't deserve it. Adapt your behavior.", "Boundary guilt says: someone is disappointed or displeased, which means you've failed. This is not conscience — it is the internalized voice of an environment that trained you to take responsibility for others' emotional states.", "When you feel guilty after setting a healthy boundary, practice asking: have I actually caused harm? Or am I just experiencing the discomfort of someone's disappointment?", "If the answer is the latter, the work is to tolerate the feeling without reversing the boundary. Guilt that is allowed to exist without being acted on eventually diminishes. Guilt that is always appeased through compliance grows stronger."]},
        ], "callout": "Tolerate the guilt. Don't let it run your decisions."},
        {"title": "How to Communicate Limits Clearly", "intro": "Vague limits invite interpretation. Clear communication is kind, not harsh.", "sections": [
            {"heading": "The Simple Script", "body": ["You don't need a long explanation. 'I'm not available for calls after 7pm' needs no justification. 'I can't take on that project right now' requires no excuse.", "The more you explain and justify, the more you invite negotiation. A boundary stated simply and calmly signals confidence. A boundary buried in apology and qualification signals ambivalence that some people will try to exploit.", "If someone consistently pushes against your boundaries despite clear communication, that is information about them — about whether this relationship has the qualities that allow your authentic self to exist in it."]},
        ], "callout": "Over-explaining a boundary weakens it."},
        {"title": "Boundaries in Specific Relationships", "intro": "Different relationships have different boundary architectures.", "sections": [
            {"heading": "Family, Work, and Romantic Relationships", "body": ["Family: family-of-origin relationships often have the deepest boundary violations and the most emotional complexity. Boundaries with family sometimes require starting very small and being prepared for significant resistance before things stabilize.", "Work: professional boundaries include availability outside work hours, emotional labor limits, and capacity management. The culture increasingly normalizes 24/7 availability; resisting this requires clarity about your own professional standards.", "Romantic relationships: boundaries in intimate relationships are not about distance — they are about preserving two distinct individuals in genuine connection. A relationship where both people have dissolved their individuality to accommodate the other is enmeshed, not close."]},
        ], "callout": "Good relationships have room for two whole people."},
        {"title": "When Others Don't Respect Your Limits", "intro": "The response to boundary violations tells you more about a relationship than the violation itself.", "sections": [
            {"heading": "Evaluating the Response", "body": ["When you communicate a clear, reasonable limit, healthy people respond with: acknowledgment, even if they're disappointed. Brief disappointment that resolves. Curiosity about your needs. Adaptation.", "Unhealthy responses include: manipulation, guilt-tripping, punishing you with silence, escalating demands, dismissing your need as unreasonable, or consistent 'forgetting.'", "Repeated, sustained disrespect of clearly communicated limits is information about the relationship. It is not an invitation to set the limit differently, justify it more, or work harder to earn being treated well. It is information about whether this relationship has space for your whole self."]},
        ], "callout": "The response to your boundary is data about the relationship."},
    ]
}

# ── Book 3 ────────────────────────────────────────────────────────────────────
b3 = {
    "title": "Self-Compassion in Practice",
    "subtitle": "How to Be on Your Own Side",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Why Being Kind to Yourself Is Harder Than Being Kind to Others", "intro": "Most people apply a double standard: grace for others, judgment for themselves. Understanding why reveals the path forward.", "sections": [
            {"heading": "The Inner Critic's Job", "body": ["The inner critic — that relentless voice that catalogs your failures, anticipates your inadequacy, and compares you unfavorably to everyone around you — is not random cruelty. It has a job: to motivate you to be better, to protect you from the pain of failure, to keep you small enough to stay safe.", "The problem is that the inner critic is spectacularly bad at its job. Research by Kristin Neff and others shows consistently that self-criticism increases anxiety, decreases motivation, reduces resilience after failure, and produces worse outcomes than self-compassion on virtually every metric it's trying to improve.", "The inner critic is trying to help. It's using the wrong method. Self-compassion is not the absence of standards — it's a more effective way to meet them."]},
        ], "callout": "Self-criticism doesn't make you better. Self-compassion does."},
        {"title": "The Three Components of Self-Compassion", "intro": "Kristin Neff's framework offers a practical structure for understanding and practicing self-compassion.", "sections": [
            {"heading": "Mindfulness, Common Humanity, Self-Kindness", "body": ["Mindfulness: seeing clearly what is happening — the pain, the struggle, the mistake — without exaggerating it or suppressing it. Just: this is hard. This hurts. I made a mistake.", "Common humanity: recognizing that struggle, imperfection, and suffering are universal human experiences — not personal failures that set you apart. You are not the only person who has felt this. You are not uniquely broken.", "Self-kindness: responding to your own pain with the warmth you would offer a good friend. Not indulgence, not bypassing accountability — just warmth. 'This is hard. You're doing your best. It's okay to struggle with this.'", "These three components work together. Mindfulness without warmth is cold observation. Warmth without honesty is false comfort. Common humanity prevents the isolation that shame thrives in."]},
        ], "callout": "What would you say to a good friend in this situation? Say it to yourself."},
        {"title": "Self-Compassion Is Not Self-Pity", "intro": "The most common objection to self-compassion: 'won't I just wallow and give up?' The research says no.", "sections": [
            {"heading": "What the Evidence Shows", "body": ["People who score high on self-compassion take more personal responsibility for their mistakes (not less), because they can look at mistakes honestly without being overwhelmed by shame that requires denial.", "They are more motivated to try again after failure — the self-compassionate response to failure is 'I can learn from this and try again' rather than 'I'm fundamentally inadequate and should stop.'", "They have lower rates of anxiety and depression, higher emotional resilience, and better relationship quality. The worried belief that self-compassion produces laziness or low standards is directly contradicted by research."]},
        ], "callout": "Self-compassion produces more growth than self-criticism. Every time."},
        {"title": "Practices for Building the Habit", "intro": "Self-compassion is a practice, not a state you achieve once.", "sections": [
            {"heading": "Daily Practices", "body": ["The self-compassion pause: when you notice self-critical thoughts, pause and ask: how would I talk to a friend going through exactly this? Then say that to yourself. Out loud if possible.", "Hand on heart: placing a hand on your chest and breathing slowly while acknowledging your difficulty activates the same physiological calming as receiving physical comfort. It sounds simple. It works.", "The three-step phrase: in moments of struggle, say to yourself: 'This is a moment of suffering. Suffering is part of life. May I be kind to myself in this moment.' The repetition and structure interrupt the shame spiral before it escalates."]},
        ], "callout": "The pause before the self-judgment is where the practice lives."},
        {"title": "Self-Compassion and Performance", "intro": "The counterintuitive truth: self-compassion in high-performance contexts produces better results than self-criticism.", "sections": [
            {"heading": "Athletes, Professionals, and Perfectionists", "body": ["Perfectionism and high standards are often defended as necessary for excellence. Research consistently shows the opposite: perfectionistic self-criticism is associated with burnout, reduced creativity, decreased resilience to setbacks, and ultimately lower performance than a high-standards-with-self-compassion approach.", "The athlete who can recover from a bad performance with self-compassion — 'that wasn't my best, I can analyze it and do better' — outperforms the one spiraling in shame. The professional who can acknowledge mistakes clearly and course-correct without a shame crisis learns faster.", "Self-compassion is not a soft skill. In high-performance contexts, it may be the most practically important one."]},
        ], "callout": "High standards and self-compassion are not in conflict. They're partners."},
        {"title": "When Self-Compassion Meets Deep Pain", "intro": "For some people, self-compassion touches something very old and very painful. This is not failure — it's progress.", "sections": [
            {"heading": "The Backdraft", "body": ["Some people, when they first practice self-kindness, find that it triggers grief, sadness, or intense emotion rather than relief. This is called 'backdraft' in self-compassion research — when you finally open the door to self-warmth, the pain that has been waiting there floods through.", "This is a sign that the practice is reaching something real. The appropriate response is not to stop — it is to slow down, moderate the intensity, and if needed, work with a therapist.", "If you find that self-compassion consistently produces overwhelming emotion, professional support in developing the skill is appropriate. This is not a sign that you need more willpower — it's a sign that the wounds are significant enough to deserve skilled companionship."]},
        ], "callout": "If self-compassion breaks you open, you've found what needed tending."},
    ]
}

# ── Book 4 ────────────────────────────────────────────────────────────────────
b4 = {
    "title": "Anger: Understanding the Fire Within",
    "subtitle": "What Your Anger Is Telling You — and How to Listen",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Anger Is Not the Problem", "intro": "Anger is information. What you do with it is the question.", "sections": [
            {"heading": "The Signal Under the Emotion", "body": ["Anger is the emotional signal for: a value has been violated, a limit has been crossed, an injustice has occurred, or a need is not being met. It is designed to mobilize energy for action in response to a perceived threat or wrong.", "The problem is not anger. The problem is: anger that is expressed destructively, anger that is suppressed and turns inward, and anger that is displaced onto targets that didn't generate it.", "People who were taught that anger is bad, dangerous, or unacceptable often find it emerging sideways — as passive aggression, sarcasm, emotional coldness, depression (often described as 'anger turned inward'), or explosive outbursts after extended suppression."]},
        ], "callout": "Suppressing anger doesn't eliminate it. It relocates it."},
        {"title": "Reading the Anger Signal", "intro": "Before responding to anger, it's worth understanding what it's actually about.", "sections": [
            {"heading": "The Four Questions", "body": ["When you notice anger, ask: What happened specifically? What value or limit does this violate? What is the unmet need underneath this? And — with honesty — is this about what's happening now, or is something older activated?", "That last question is crucial. Much interpersonal anger is disproportionate because the current situation has activated an old wound. The anger is real, but its intensity belongs to an earlier story that the present moment has echoed.", "Understanding which anger you're carrying in any given moment makes your response more precise and less collateral-damage-producing."]},
        ], "callout": "Disproportionate anger is almost always carrying something from before."},
        {"title": "Healthy Expression and Release", "intro": "Anger needs movement. Not permission to harm — movement.", "sections": [
            {"heading": "Physical and Expressive Outlets", "body": ["Anger is a high-energy state — the body is primed for action. Exercise is one of the most effective and socially safe ways to metabolize that physiological charge: running, heavy lifting, boxing, anything vigorous.", "Expressive writing: write the anger without editing. Don't send it. Don't even keep it. Write it to get it out of the body and onto the page, where you can look at it rather than be trapped inside it.", "The important distinction: expressing anger to release physical charge (healthy) versus expressing anger to punish the target (harmful). The first is for you. The second is for them — and it rarely produces what you're actually looking for."]},
        ], "callout": "Release the charge. Then decide what communication is needed."},
        {"title": "Anger in Relationships", "intro": "How couples and close relationships handle anger determines whether conflict becomes connection or destruction.", "sections": [
            {"heading": "The Gottman Research", "body": ["John Gottman's decades of relationship research identifies four patterns — he calls them the Four Horsemen — that predict relationship dissolution with about 93% accuracy: criticism (attacking the person rather than the behavior), contempt (communicating superiority), defensiveness (responding to complaints with counter-complaints), and stonewalling (shutting down and withdrawing).", "All four are anger-related. Contempt is weaponized anger. Stonewalling is often fear of uncontrolled anger.", "The alternative: complaints instead of criticism ('when you did X, I felt Y, and I need Z' versus 'you always do this'), taking responsibility instead of defensiveness, physiological self-soothing before difficult conversations, and repair attempts that acknowledge impact."]},
        ], "callout": "Contempt is the most destructive thing you can do to a relationship. Anger isn't."},
        {"title": "When Anger Becomes a Problem", "intro": "There is a difference between healthy anger expression and anger that causes harm or signals something clinical.", "sections": [
            {"heading": "Knowing the Line", "body": ["Anger becomes a problem when: it is disproportionate to the situation consistently, it produces behavior that harms relationships or property, it is followed by shame and regret regularly, it significantly impairs your daily functioning, or it involves physical aggression.", "Intermittent explosive disorder, complex PTSD with anger dysregulation, and certain medical conditions can all produce anger that feels uncontrollable. These warrant professional evaluation.", "Anger management programs have solid evidence for their effectiveness. Individual therapy with a focus on emotion regulation is often more effective than group programs for people with significant anger history. Seeking help for anger that causes harm is an act of care for yourself and everyone in your life."]},
        ], "callout": "Seeking help for damaging anger is strength."},
        {"title": "The Gifts of Healthy Anger", "intro": "Anger, properly understood, is one of the most important forces for growth and justice.", "sections": [
            {"heading": "What Anger Makes Possible", "body": ["Healthy anger draws the line that needed drawing. It says: this treatment is not acceptable, and I am worth being treated better.", "It mobilizes the energy to leave what needs to be left, to defend what needs defending, to speak what needs saying. Many people in unhealthy relationships or circumstances stay longer than is good for them precisely because their anger has been so thoroughly suppressed that they can't access the signal that would move them.", "When anger is neither suppressed nor acted out destructively, but listened to — its message honored and its energy channeled into appropriate action — it is one of the most clarifying, boundary-setting, self-respecting emotions a person can have."]},
        ], "callout": "Anger, listened to, is the voice of your own worth."},
    ]
}

# ── Book 5 ────────────────────────────────────────────────────────────────────
b5 = {
    "title": "Loneliness and the Art of Connection",
    "subtitle": "Understanding Modern Disconnection and Finding Your Way Back to Each Other",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Loneliness Epidemic That Nobody Wants to Admit", "intro": "More connected by technology than ever. More lonely in practice than any previous generation measured.", "sections": [
            {"heading": "The Numbers", "body": ["The US Surgeon General's Advisory on Loneliness (2023) described loneliness as a public health epidemic, noting that 50% of American adults report measurable levels of loneliness — and this predated COVID-19's social disruptions.", "Chronic loneliness is associated with health impacts equivalent to smoking 15 cigarettes per day: elevated cortisol, disrupted sleep, impaired immunity, accelerated cognitive decline, and increased all-cause mortality.", "And yet most people experiencing significant loneliness don't talk about it. The stigma around loneliness — the implication that it reflects some personal deficiency — keeps it invisible and keeps people from seeking connection or help."]},
        ], "callout": "Loneliness is a public health crisis. It is not a personal failure."},
        {"title": "What Loneliness Actually Is", "intro": "Loneliness is not the same as solitude, and understanding the difference changes how you address it.", "sections": [
            {"heading": "The Distinction", "body": ["Solitude is chosen aloneness that is experienced as restorative. Loneliness is the painful mismatch between the social connection you have and the social connection you need.", "You can be lonely in a crowded room, in a marriage, or surrounded by acquaintances if none of those relationships provide genuine emotional intimacy. And you can be entirely alone for days and feel deeply connected if your relationship with yourself and your sense of place in the world are intact.", "The target of loneliness interventions is not just more time with people. It is more genuine connection — more feeling known, understood, and cared for."]},
        ], "callout": "Loneliness is a quality problem, not a quantity problem."},
        {"title": "The Social Skills Gap", "intro": "Many people in the modern era are genuinely missing some of the social skills that connection requires. This is fixable.", "sections": [
            {"heading": "Skills, Not Personality", "body": ["Initiating connection, sustaining conversations, transitioning from acquaintance to friendship, being vulnerable enough to allow genuine closeness — these are skills. They are developed through practice and feedback, not born.", "Many adults in the social media era have spent less time practicing the specific skills of in-person connection than previous generations, and more time in the lower-stakes, more controllable environment of digital communication. The gap is real, and it's not a personality problem.", "The solution is practice in low-stakes environments: classes, hobby groups, volunteer settings, regular recurring social contexts. Not performance anxiety contexts — just places where the same people show up repeatedly and relationship naturally develops over time."]},
        ], "callout": "Connection is a skill. Skills improve with practice."},
        {"title": "The Friendship in Adulthood Problem", "intro": "Making friends as an adult is genuinely harder than it was in school. Understanding why helps you work with the reality.", "sections": [
            {"heading": "Why Adult Friendship Is Hard", "body": ["Jeffrey Hall's friendship research identifies three conditions necessary for friendship formation: proximity, repeated unplanned interaction, and a setting that encourages people to let their guard down. School, college, and early work environments provide all three. Adult life largely provides none of them.", "Most adult social experiences are planned, brief, and don't recur naturally. The friends you make as an adult are almost always made through consistent participation in recurring activities — a running group, a book club, a regular game night, a class, a community of practice.", "The implication: 'I should make more friends' is not a plan. 'I will participate consistently in [recurring activity] for 6 months' is."]},
        ], "callout": "Adult friendship requires infrastructure. Build the infrastructure."},
        {"title": "The Quality of Your Current Relationships", "intro": "Before adding new connections, there's often gold in the relationships you already have.", "sections": [
            {"heading": "Deepening What Exists", "body": ["Research on conversation quality by Nicholas Epley shows that people consistently underestimate how much others want to have meaningful conversations. We assume others prefer small talk; they actually prefer depth just as much as we do, and are happy to go there when someone leads.", "Ask deeper questions. Be more honest about your actual experience rather than the socially acceptable summary. Listen with genuine curiosity rather than waiting to respond. These simple shifts often transform the depth of relationships you already have.", "The relationships where deeper investment is most valuable: people you already trust somewhat, see regularly, and with whom there is natural warmth. These are the highest-return relationships to deepen."]},
        ], "callout": "The connection you're looking for might be in the relationship you're already in."},
        {"title": "When Loneliness Goes Deeper", "intro": "For some people, loneliness has roots that require more than social skills or scheduling.", "sections": [
            {"heading": "The Relational Wounds Beneath", "body": ["Chronic loneliness sometimes reflects deep fear of closeness — where the desire for connection is real but intimacy feels threatening because of past betrayal, abandonment, or attachment trauma.", "These patterns often produce the painful cycle of longing for connection while unconsciously pushing it away when it arrives — finding fault, pulling back, testing loyalty, or simply feeling numb in the presence of people who want to know you.", "This pattern responds to therapy, particularly attachment-informed therapy, more reliably than to social skill building. If you consistently find yourself unable to receive connection that's genuinely offered, the work is internal — and it's worth doing."]},
        ], "callout": "Sometimes loneliness is about the distance you put between yourself and others."},
    ]
}

# ── Book 6 ────────────────────────────────────────────────────────────────────
b6 = {
    "title": "The Highly Sensitive Person's Guide to Thriving",
    "subtitle": "Understanding Your Trait and Building a Life That Works for Your Nervous System",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What High Sensitivity Actually Is", "intro": "Highly sensitive people are not broken. They are wired differently — and that wiring has real advantages.", "sections": [
            {"heading": "The Research", "body": ["Elaine Aron's research, beginning in the early 1990s, identified a trait she called Sensory Processing Sensitivity — a deeper level of cognitive processing of environmental and emotional information that affects approximately 15-20% of the population, distributed equally across genders and present in over 100 animal species.", "HSPs process information more thoroughly, feel emotions more intensely, notice subtle environmental details others miss, have richer inner lives, and are more affected by others' moods and energy. They also require more downtime to process experiences and are more sensitive to overstimulation, pain, and certain sensory inputs.", "This is not a disorder. It is a normal variation in nervous system sensitivity — one that carries both advantages and challenges that require different management than a less-sensitive nervous system."]},
        ], "callout": "Sensitivity is not weakness. It's a trait with both gifts and costs."},
        {"title": "The Overstimulation Cycle", "intro": "The most practical challenge of high sensitivity is managing a world designed for less-sensitive nervous systems.", "sections": [
            {"heading": "Recognizing Overstimulation", "body": ["Overstimulation in HSPs looks like: sudden exhaustion after social interaction, irritability after crowds or noise, difficulty thinking clearly after emotionally intense experiences, the need for long periods of solitude to 'reset', difficulty functioning in chaotic or loud environments.", "What it's not: introversion (though HSPs are often introverted), anxiety disorder (though overstimulation can trigger anxiety responses), or personality weakness.", "The management principle: recognize overstimulation early (before it becomes dysregulation), build in recovery time proactively (not as a last resort), and design your environment and schedule to minimize unnecessary overstimulation while maintaining genuine engagement with life."]},
        ], "callout": "Managing overstimulation proactively is the HSP's most important daily skill."},
        {"title": "Relationships as an HSP", "intro": "High sensitivity transforms the relational experience — for better and worse.", "sections": [
            {"heading": "The Gifts and Challenges", "body": ["HSPs in relationships: deeply empathetic, attuned to a partner's emotional state, capable of profound intimacy, highly conscientious partners who notice small gestures and appreciate them deeply.", "The challenges: absorbing a partner's emotions to the point of difficulty distinguishing their own, needing more solitude than many partners expect, deeply affected by conflict (often avoiding it to a fault), and sometimes perceived as 'too intense' or 'too sensitive' by less-sensitive partners.", "Understanding that these are trait-based patterns rather than problems to fix allows both HSPs and their partners to work with the reality rather than fighting it."]},
        ], "callout": "An HSP in a healthy relationship is an extraordinary partner. The relationship needs to make room for their nervous system."},
        {"title": "Work Environments and Career Fit", "intro": "The work environment matters enormously for HSPs — more than for less-sensitive people.", "sections": [
            {"heading": "Environments That Work", "body": ["HSPs typically thrive in: environments with some control over noise and stimulation, work that involves depth over breadth, roles that use their empathy and attention to detail rather than asking them to override it, cultures that value quality over speed, and contexts where solitary focused work is respected.", "They typically struggle in: open-plan offices, high-conflict workplace cultures, roles requiring constant performance under pressure, contexts that devalue careful work in favor of rapid output, and positions requiring frequent emotional labor with limited recovery time.", "This is not limitation — it's fit. Many of the highest-value professional roles (research, counseling, design, writing, medicine, education, consulting) suit HSP traits well when the environment is appropriate."]},
        ], "callout": "Career fit for an HSP is about environment as much as role."},
        {"title": "Protecting Energy Without Isolating", "intro": "The challenge for HSPs: protecting their nervous system without shrinking their life.", "sections": [
            {"heading": "The Balance", "body": ["Many HSPs respond to overstimulation by progressively narrowing their world — seeing fewer people, taking on less, avoiding stimulating situations. This strategy reduces discomfort in the short term and produces profound dissatisfaction and loneliness over time.", "The alternative: build recovery time into an engaged life rather than an avoidant one. Show up for the experiences that matter. Build in restoration after. Be honest with close people about what you need.", "The goal is not a smaller life. The goal is a life designed for your actual nervous system — with margin built in, recovery respected, and enough genuine engagement that your gifts are actually used."]},
        ], "callout": "Design for your nervous system. Not around it."},
        {"title": "The Gift of the Trait", "intro": "The same sensitivity that makes the world sometimes overwhelming makes it more beautiful.", "sections": [
            {"heading": "What Sensitivity Makes Possible", "body": ["HSPs experience beauty more intensely. Music moves them more deeply. Art speaks to them more specifically. Nature genuinely restores them. They notice the quality of light, the shift in a person's tone, the texture of ideas.", "They care more deeply and more consistently. They make connections between things that less-sensitive people miss. They often produce creative and intellectual work of unusual depth and resonance — precisely because they process so thoroughly.", "The goal of understanding high sensitivity is not to manage a problem. It's to understand a trait that, taken seriously on its own terms, enables a different and valuable way of being in the world."]},
        ], "callout": "The trait that costs you the most is often the one that gives you the most."},
    ]
}

# ── Book 7 ────────────────────────────────────────────────────────────────────
b7 = {
    "title": "Forgiveness Is for You",
    "subtitle": "A Practical Guide to Letting Go Without Letting Anyone Off the Hook",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Forgiveness Is Not", "intro": "More misconceptions exist about forgiveness than about almost any other psychological topic.", "sections": [
            {"heading": "Clearing the Record", "body": ["Forgiveness is not: condoning what happened, pretending it didn't matter, reconciling with the person who hurt you, trusting them again, forgetting what occurred, or declaring that they were right and you were wrong.", "Forgiveness is: releasing yourself from carrying the weight of the wound. It is the decision to stop allowing what someone did in the past to hold your nervous system hostage in the present. It is for you, not for them.", "This distinction matters enormously — because most people's resistance to forgiveness is actually resistance to the misconceptions. Once those misconceptions are cleared, forgiveness becomes more accessible."]},
        ], "callout": "Forgiveness releases the prisoner — and you're the prisoner."},
        {"title": "The Physiology of Holding On", "intro": "Unforgiveness is not a neutral state. It is a physiological burden.", "sections": [
            {"heading": "What Resentment Does to the Body", "body": ["Holding resentment keeps the threat-response system partially activated. The person who wronged you is no longer present — but the hormonal and nervous system response to the threat they represented is still running.", "Research shows that people asked to recall betrayals experience elevated heart rate, blood pressure, and stress hormone levels. Prolonged resentment is associated with elevated chronic inflammation, impaired immune function, and disrupted sleep.", "This is not metaphor. The body does not distinguish between a current threat and a vividly rehearsed historical one. Every time you replay the grievance — and most people replay them many times — you pay the physiological cost again."]},
        ], "callout": "Resentment is a debt you pay — not them."},
        {"title": "The Forgiveness Process", "intro": "Forgiveness is not a decision that happens once. It is a practice that happens many times.", "sections": [
            {"heading": "The Stages", "body": ["Acknowledge the full reality of what happened — not the defended version, the minimized version, or the catastrophized version. The actual event and its actual impact on you.", "Allow the feelings — grief, anger, sadness, betrayal. Feelings that are bypassed in the rush to forgiveness tend to resurface. The fastest path through is through.", "Reframe — not to excuse the behavior, but to understand it. What forces shaped the person who harmed you? This is not sympathy — it's comprehension. Comprehension reduces the mystified hatred that sustains resentment.", "Release — the decision to stop organizing your emotional life around this wound. This may need to be made repeatedly. Each time the resentment resurfaces, you make the choice again."]},
        ], "callout": "Forgiveness is a practice, not an event."},
        {"title": "Self-Forgiveness: The Harder Work", "intro": "For many people, forgiving themselves is significantly harder than forgiving others.", "sections": [
            {"heading": "Why Self-Forgiveness Stalls", "body": ["Self-forgiveness stalls most often because: ongoing punishment feels like accountability (if I stop suffering, it means it didn't matter), shame around the action is so deep that forgiveness feels unearned, or the wound caused to others feels too significant to release.", "Self-forgiveness does not mean the action was acceptable. It means you have acknowledged it fully, taken appropriate responsibility, made repair where possible, and chosen not to continue punishing yourself beyond what is constructive.", "Permanent self-punishment is not accountability. It is suffering masquerading as responsibility. It serves neither you nor the people you harmed."]},
        ], "callout": "Accountability is looking clearly and making repair. Punishment is looking away from the present."},
        {"title": "Forgiveness Without Reconciliation", "intro": "Some people should not be forgiven and also not let back into your life. These are not in conflict.", "sections": [
            {"heading": "Holding Both", "body": ["You can forgive someone — release yourself from carrying the wound — while maintaining clear limits about that person's access to you. Forgiveness does not obligate continued relationship.", "People who are unsafe — who have demonstrated through repeated behavior that they will harm you given proximity — can be forgiven at a distance. The forgiveness is internal. The boundary is relational.", "In fact, forgiving someone genuinely often becomes easier when you're no longer in contact with them — because forgiveness is no longer confused with trust, and the relationship's reality can't keep re-injuring the healing wound."]},
        ], "callout": "You can forgive someone and never speak to them again. Both are appropriate."},
        {"title": "When Forgiveness Feels Impossible", "intro": "Some wounds are genuinely severe. Some situations make forgiveness feel like injustice. This is worth honoring.", "sections": [
            {"heading": "The Long Road", "body": ["For severe violations — abuse, assault, profound betrayal — forgiveness is often a years-long process, not a decision made in a contemplative moment. Expecting rapid forgiveness for severe wounds is both unrealistic and unkind to yourself.", "The goal is not to feel no resentment. The goal is for the resentment to have less and less hold on your daily experience over time — not because the wound was minor, but because your current life deserves your presence more than the past does.", "If you find that a significant wound is actively dominating your present experience — your relationships, your wellbeing, your capacity for joy — working with a therapist who specializes in trauma and forgiveness often accelerates this process significantly."]},
        ], "callout": "You don't have to be ready to forgive. You just have to be willing to begin."},
    ]
}

# ── Book 8 ────────────────────────────────────────────────────────────────────
b8 = {
    "title": "Emotional Intelligence at Work and Home",
    "subtitle": "The Practical Guide to Understanding and Using Your Emotions Well",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Emotional Intelligence Actually Is", "intro": "EQ is not about being nice or managing feelings away. It's about using emotional information effectively.", "sections": [
            {"heading": "The Four Components", "body": ["Peter Salovey and John Mayer's original model, subsequently popularized by Daniel Goleman, identifies four core components: perceiving emotions accurately (in yourself and others), using emotions to facilitate thought (leveraging emotional states for appropriate tasks), understanding emotions (their causes, dynamics, and how they change), and managing emotions (regulating your own and influencing others' constructively).", "Emotional intelligence is a skill set that can be developed, not a fixed trait. Research shows that EQ generally improves with age and deliberate practice — unlike IQ, which remains relatively stable."]},
        ], "callout": "Emotional intelligence is built. It's not assigned at birth."},
        {"title": "Emotional Literacy: Naming What You Feel", "intro": "Most people have a vocabulary of about six emotions. Expanding it is the foundation of emotional intelligence.", "sections": [
            {"heading": "Why Granularity Matters", "body": ["Research by Lisa Feldman Barrett shows that people who can distinguish between emotional states more precisely — who don't just feel 'bad' but can identify whether they're anxious, disappointed, embarrassed, resentful, or overwhelmed — have better emotional regulation outcomes, make better decisions under stress, and have better physical health outcomes.", "Emotion granularity is built by expanding your emotional vocabulary and practicing precise naming. Not 'I'm stressed' but 'I'm dreading this conversation specifically because I'm afraid of being dismissed.' The specificity points to the actual need."]},
        ], "callout": "The more precisely you can name what you feel, the more precisely you can address it."},
        {"title": "Reading Other People", "intro": "Social and empathic accuracy is the interpersonal component of emotional intelligence.", "sections": [
            {"heading": "Tuning In", "body": ["Empathic accuracy is the ability to read what another person is actually feeling — not what they're saying they feel, not what you imagine you'd feel in their situation, but what they're actually experiencing.", "This skill is built through: genuine curiosity about others' inner experience, asking rather than assuming, noticing nonverbal signals (face, body, tone, pacing), and suspending your own emotional narrative long enough to actually receive theirs.", "The most common failure mode: projective empathy — feeling what you'd feel in their situation and assuming it's what they feel. This is better than no empathy but often misses the specific reality of another person's experience."]},
        ], "callout": "Empathy is listening with your whole attention, not just waiting to relate."},
        {"title": "Emotional Regulation", "intro": "Regulation is not suppression. It's the ability to respond rather than react.", "sections": [
            {"heading": "The Regulation Toolkit", "body": ["The most evidence-based regulation techniques: slow diaphragmatic breathing (directly activates the parasympathetic nervous system), cognitive reappraisal (reinterpreting the meaning of a situation before responding), temporal distancing ('how will I feel about this in a year?'), and physiological self-soothing (hand on heart, cold water on face, movement).", "Emotional regulation in practice: notice the emotion arising, name it precisely, pause before responding (the gap between stimulus and response is where choice lives), choose a regulatory tool, then decide on a response from a less activated state.", "This is not about not feeling. It's about not being controlled by feelings in a way that produces outcomes you'll regret."]},
        ], "callout": "Regulation creates the gap where good judgment lives."},
        {"title": "Emotional Intelligence in Leadership", "intro": "The research on leadership and EQ is among the most consistent in organizational psychology.", "sections": [
            {"heading": "What EQ Does for Leaders", "body": ["Leaders with high emotional intelligence: build more trust with their teams, produce higher employee engagement, navigate conflict more constructively, make better decisions under pressure, and are more effective at the core interpersonal dimensions of leadership — communication, motivation, and development.", "The single most impactful EQ behavior in leadership: genuinely listening. Research shows that employees who feel heard by their managers have dramatically higher engagement and lower turnover, and it costs nothing to implement.", "The EQ leadership practice: in every significant interaction, spend at least as much time seeking to understand as seeking to be understood."]},
        ], "callout": "Listening is the highest-leverage leadership skill you can develop today."},
        {"title": "Building EQ as a Daily Practice", "intro": "Emotional intelligence improves through deliberate daily practice, not through occasional insight.", "sections": [
            {"heading": "The Daily Habits", "body": ["End-of-day emotional audit: spend 5 minutes reviewing your day's significant emotional experiences. What did you feel? When? Was your response effective? What would you do differently?", "One empathy conversation per day: in one interaction, focus entirely on understanding the other person's perspective before sharing your own. Practice suspending your interpretation and asking questions.", "Emotion journaling: write about emotional experiences with as much granularity as you can. Not just 'I was angry' but what triggered it, what it felt like in the body, what need was unmet, and what the anger was trying to tell you.", "Over weeks and months, these practices build the neural pathways of emotional awareness and regulation more reliably than any amount of understanding the concept."]},
        ], "callout": "EQ is built in the moments you choose awareness over reaction."},
    ]
}

# ── Book 9 ────────────────────────────────────────────────────────────────────
b9 = {
    "title": "Finding Purpose After Loss",
    "subtitle": "Navigating Grief, Change, and Identity to Rediscover What Matters",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What Loss Does to Identity", "intro": "We are partly defined by what we love and who we love. When that's gone, so is part of the self.", "sections": [
            {"heading": "The Identity Dimension of Grief", "body": ["Most discussions of grief focus on the emotional dimension — the sadness, the longing, the shock. Less discussed is the identity dimension: when someone important dies, or when a significant life chapter ends, you also lose the version of yourself that existed in relation to that person or in that chapter.", "The spouse who loses a partner of 30 years doesn't just lose the person — they lose the daily structure, the shared identity, the role of partner that was central to who they were. The professional who loses a career doesn't just lose income — they lose a primary source of meaning, competence, and social identity.", "This identity disruption is why major losses often produce a quality of confusion and purposelessness that goes beyond emotional pain."]},
        ], "callout": "Grief is not just about who or what you've lost. It's about who you are without them."},
        {"title": "The Non-Linear Path of Grief", "intro": "Grief doesn't follow five stages in order. It follows the complicated logic of being human.", "sections": [
            {"heading": "What the Research Actually Says", "body": ["Elisabeth Kübler-Ross's five stages — denial, anger, bargaining, depression, acceptance — were originally developed for people facing their own death, not bereavement. Applied to grief, they have been widely misunderstood as a linear prescription.", "The research since then is clear: grief is non-linear, highly individual, and doesn't follow predictable stages. Most people move in and out of different emotional states, experience unexpected resurgences of acute grief well after they thought they were 'past it,' and have individualized timelines that no model accurately predicts.", "The 'dual process model' of bereavement — oscillating between loss-oriented processing and restoration-oriented processing (adjusting to new roles and identity) — is more consistent with how people actually grieve than the stage model."]},
        ], "callout": "There is no correct timeline for grief. There is only yours."},
        {"title": "The Work of Meaning-Making", "intro": "Research suggests that meaning-making — finding some significance or growth in the experience — is one of the strongest predictors of healthy grief adaptation.", "sections": [
            {"heading": "Post-Traumatic Growth", "body": ["Post-traumatic growth — positive psychological change as a result of struggling with highly challenging life circumstances — is a documented phenomenon, not a platitude. It doesn't mean the loss wasn't devastating. It means the struggle to adapt to it can produce new strengths, perspectives, and connections.", "Common forms of growth after loss: deeper appreciation for relationships and what actually matters, increased personal strength (discovering you can survive what you feared would be unsurvivable), new possibilities and directions that weren't visible before, increased compassion and connection with other people's suffering.", "Growth doesn't negate the loss. Both things are true simultaneously — the loss is terrible and something meaningful has also emerged from surviving it."]},
        ], "callout": "Growth after grief doesn't mean the loss was worth it. It means you made something from it anyway."},
        {"title": "Practical Navigation of the Grief Period", "intro": "The period immediately following significant loss has practical as well as emotional dimensions.", "sections": [
            {"heading": "Surviving the First Year", "body": ["Lower your expectations for your own functioning. Major loss genuinely impairs concentration, memory, decision-making, sleep, and energy. This is normal and temporary, not a sign of permanent change.", "Postpone major irreversible decisions when possible — the first year after significant loss is not ideal for major life changes. The person making decisions under acute grief is not operating with their full cognitive and emotional capacity.", "Accept help. The social impulse to help in early grief is real and genuine. Letting people provide meals, company, practical assistance, and presence is not weakness — it is the appropriate use of a support network during an extreme circumstance."]},
        ], "callout": "In grief, receiving care is as important as giving it."},
        {"title": "Rebuilding Identity and Purpose", "intro": "After the acute phase of grief, the work of reconstruction begins.", "sections": [
            {"heading": "Finding the New Self", "body": ["The rebuilt self after major loss is not the same self as before — and trying to return to who you were before is often both impossible and unhelpful. Something has changed. The invitation is to integrate that change.", "Questions that help in the reconstruction phase: What do I care about now that I didn't before? What matters less than I thought it did? Who am I outside of the roles that are now gone? What do I want my remaining time to be about?", "These are not comfortable questions. They are the right questions. The people who navigate major loss best over time are generally those who engage with these questions rather than trying to restore the previous life unchanged."]},
        ], "callout": "You can't return to who you were. You can build someone worth being."},
        {"title": "When Grief Becomes Complicated Grief", "intro": "Most grief, while painful, resolves over time. Some doesn't — and that's a clinical reality worth knowing.", "sections": [
            {"heading": "Recognizing Complicated Grief", "body": ["Complicated grief (also called prolonged grief disorder) is characterized by: intense grief that remains largely undiminished after 12 months (6 months in some criteria), significant impairment in daily functioning, persistent disbelief about the loss, avoidance of reminders or conversely, preoccupation with the deceased or lost object, and inability to experience positive emotions.", "Complicated grief affects approximately 10-15% of bereaved people. It is not a sign of weakness or excessive love — it is a specific clinical condition that responds well to targeted treatment (particularly Complicated Grief Treatment or CGT, a specific therapy protocol).", "If your grief is actively preventing you from functioning a year or more after loss, this is a signal to seek professional support — not as a sign that you're grieving incorrectly, but as compassionate care for yourself."]},
        ], "callout": "Grief that doesn't move deserves professional attention, not judgment."},
    ]
}

# ── Book 10 ───────────────────────────────────────────────────────────────────
b10 = {
    "title": "The Anxiety Reset",
    "subtitle": "Understanding, Managing, and Transforming Your Relationship With Worry",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Anxiety Is Not the Enemy", "intro": "Anxiety is your nervous system doing its job in a situation it wasn't designed for.", "sections": [
            {"heading": "What Anxiety Is For", "body": ["Anxiety is the body's preparatory response to anticipated threat. Elevated heart rate, heightened alertness, muscle tension, shallow breathing — these are all preparations for action. They are useful when there is a physical threat requiring rapid response.", "The problem is that the nervous system cannot reliably distinguish between a tiger in the tall grass and a performance review, a first date, or an unanswered text message. The physiological response is similar; the usefulness of the response to those situations is very limited.", "Anxiety is not a character flaw, a weakness, or a personal failing. It is an ancient survival system operating in a modern environment it was not designed for."]},
        ], "callout": "Anxiety is your nervous system trying to keep you safe. It just doesn't always know what 'safe' means in a modern context."},
        {"title": "The Worry Cycle and How to Break It", "intro": "Worry feels productive. It rarely is. Understanding the difference is one of the most practical anxiety interventions available.", "sections": [
            {"heading": "Productive Problem-Solving vs. Worry", "body": ["Productive problem-solving: identifying a specific problem, generating potential solutions, evaluating them, choosing one, and implementing it. This is useful and terminates when action is taken.", "Worry: repetitive, unresolved mental rehearsal of threatening scenarios without arriving at action. It feels like problem-solving but produces no solutions and no termination. Worry maintains anxiety by keeping the threat active in the nervous system without resolving it.", "The intervention: when you notice worry, ask — is there an action I can take right now about this? If yes, take it. If no, schedule a specific 'worry time' (a real 15-minute slot where you allow yourself to worry about this specific topic) and when the worry appears outside that slot, redirect: 'I'll think about this at 4pm.'"]},
        ], "callout": "Schedule your worry. Everything else is hijacking."},
        {"title": "The Body-First Approach to Anxiety", "intro": "Anxiety lives in the body first and the mind second. The most direct interventions start in the body.", "sections": [
            {"heading": "Physiological Interventions", "body": ["Slow breathing (extended exhale): exhale twice as long as your inhale. Inhale for 4 counts, exhale for 8. This activates the parasympathetic nervous system directly through the vagus nerve and is the fastest evidence-based intervention for acute anxiety.", "Cold water: splashing cold water on the face or holding ice triggers the dive reflex, which activates the parasympathetic system and can interrupt a panic response within seconds.", "Vigorous exercise: burns off the stress hormones that fuel the physical experience of anxiety. Even a 10-minute brisk walk after an anxiety-provoking event measurably reduces circulating cortisol and adrenaline.", "The principle: reduce physiological arousal first, then engage cognitive approaches. Trying to think your way out of anxiety while the nervous system is fully activated is like trying to hear a quiet voice in a loud room."]},
        ], "callout": "Bring the body down first. The mind follows."},
        {"title": "Cognitive Approaches That Actually Work", "intro": "Anxiety involves distorted thinking patterns that respond well to specific cognitive interventions.", "sections": [
            {"heading": "The Core Distortions", "body": ["Catastrophizing: assuming the worst possible outcome is the most likely. 'My boss seemed annoyed — I'm going to be fired — I'll never find another job — I'll lose my apartment.' Each step in the chain is treated as certain when it is actually speculative.", "Probability distortion: treating low-probability events as likely because they are vivid and frightening. Flying feels more dangerous than driving because crashes are dramatic — it is statistically far safer.", "The interventions: 'What's the actual probability of the worst case?' 'What's the best case? What's the most likely case?' 'Have I survived similar situations before?' 'What would I tell a friend thinking this?'", "CBT (Cognitive Behavioral Therapy) for anxiety has the most extensive evidence base of any psychological intervention. If your anxiety is significantly impairing your life, working through CBT with a therapist or via a structured workbook is highly recommended."]},
        ], "callout": "Anxious thoughts are predictions, not facts. Treat them accordingly."},
        {"title": "Lifestyle Factors and Anxiety", "intro": "Several entirely modifiable lifestyle factors have large effects on baseline anxiety. They're worth attending to before more complex interventions.", "sections": [
            {"heading": "The High-Impact Variables", "body": ["Sleep: sleep deprivation dramatically worsens anxiety the following day. The hippocampus and prefrontal cortex — which are critical for contextualizing threats and regulating emotional response — are impaired by poor sleep. This is a direct biological mechanism, not a metaphor.", "Caffeine: caffeine directly stimulates the sympathetic nervous system, mimicking the physiological state of anxiety. People with anxiety disorders or high baseline anxiety often experience significant symptom reduction when caffeine is reduced or eliminated. Try one week caffeine-free as an experiment.", "Exercise: 150 minutes of moderate aerobic activity per week (the standard public health recommendation) has anxiety-reducing effects comparable to some medications in meta-analyses. Exercise also improves sleep, which further reduces anxiety.", "Social connection: social support directly buffers the stress response. Consistent, genuine social contact is one of the most robust biological regulators of anxiety that exists."]},
        ], "callout": "Sleep, exercise, caffeine, and connection are anxiety variables. Treat them as such."},
        {"title": "Living Well With Anxiety", "intro": "The goal is not a life without anxiety. It's a life where anxiety doesn't run the show.", "sections": [
            {"heading": "The Long-Term Relationship", "body": ["Some people's nervous systems will always be more anxiety-prone than others. The goal of anxiety work is not to become a person who never feels anxious — it's to develop the relationship with anxiety such that it gives you useful information without dominating your decisions and limiting your life.", "Acceptance and Commitment Therapy (ACT) offers a useful frame: anxiety is not something to eliminate, it's something to make room for while continuing to act in accordance with your values. The anxiety may come; you don't have to let it steer.", "The life well-lived is not the one with the fewest uncomfortable feelings. It's the one where you showed up for what mattered — even scared."]},
        ], "callout": "Courage is not the absence of anxiety. It's acting in spite of it."},
    ]
}

books = [b1, b2, b3, b4, b5, b6, b7, b8, b9, b10]
filenames = [
    "01 - Healing After Childhood Wounds.pdf",
    "02 - The Boundaries Blueprint.pdf",
    "03 - Self-Compassion in Practice.pdf",
    "04 - Anger Understanding the Fire Within.pdf",
    "05 - Loneliness and the Art of Connection.pdf",
    "06 - The Highly Sensitive Person's Guide to Thriving.pdf",
    "07 - Forgiveness Is for You.pdf",
    "08 - Emotional Intelligence at Work and Home.pdf",
    "09 - Finding Purpose After Loss.pdf",
    "10 - The Anxiety Reset.pdf",
]

for book, fname in zip(books, filenames):
    generate_ebook(os.path.join(OUT, fname), book)

print("SERIES 7 DONE")
