import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from generate_ebook import generate_ebook

OUT = os.path.dirname(__file__)
ACCENT = "#2D9CDB"
BG = "#F0F8FF"
SERIES = "The AI Professional Series"

DISCLAIMER = """This book is intended for educational and informational purposes only. The tools, strategies, and workflows described are based on publicly available information at time of writing. AI technology evolves rapidly; some specific features or platforms mentioned may change after publication.

Nothing in this book constitutes professional, legal, or financial advice. The author and publisher make no guarantees about the results achievable from applying these techniques.

Always evaluate AI-generated content for accuracy before professional or public use. Users remain responsible for the quality and appropriateness of their outputs."""

# ── Book 1 ────────────────────────────────────────────────────────────────────
b1 = {
    "title": "AI for the Overwhelmed Professional",
    "subtitle": "Cut Your Workload in Half Using Tools You Already Have Access To",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Why Most People Get AI Wrong at Work", "intro": "The mistake isn't using AI too much. It's using it too narrowly.", "sections": [
            {"heading": "The Copy-Paste Trap", "body": ["Most people discover ChatGPT or Claude, ask it a question, get an answer, paste it into a document, and consider that 'using AI.' This is the equivalent of buying a car and only sitting in it in the driveway. You're not going anywhere.", "The real leverage in AI for professional work is in systematic integration — building repeatable processes where AI handles the high-volume, cognitively expensive parts of your work so your judgment, relationships, and creative thinking can operate on more important problems.", "This book is about the second kind of AI use. The kind that compounds."]},
            {"heading": "The 80/20 of AI at Work", "body": ["In most professional roles, 20% of your tasks produce 80% of your value. The other 80% — email management, scheduling, report writing, research compilation, summarization, formatting, follow-ups — is necessary but not differentiating.", "AI excels at the 80%. It can draft emails, summarize documents, organize research, write first drafts, create agendas, format data, and generate options. These are tasks that take you time and cognitive energy but require minimal judgment.", "The transformation: redirect the hours saved from the 80% toward the 20% where your actual value lives."]},
        ], "callout": "AI doesn't replace your best work. It makes more room for it."},
        {"title": "Your Daily AI Workflow", "intro": "An AI workflow isn't a single tool. It's a system of prompts and processes that becomes faster and more useful over time.", "sections": [
            {"heading": "Morning Triage with AI", "body": ["Start your morning by pasting your email inbox summary or calendar into an AI assistant and asking: 'Help me prioritize these items by urgency and importance. Flag anything that needs a response today and suggest three-sentence draft replies for the urgent ones.'", "This takes 5 minutes and replaces the 30-45 minutes most people spend in reactive email mode. You're still making the decisions — AI is doing the drafting and organizing.", "Build a 'morning brief' template specific to your role and refine it weekly. After a month, it becomes a powerful daily orienting tool that requires almost no thought to run."]},
            {"heading": "End-of-Day Capture", "body": ["Spend 5 minutes at the end of each day dictating or writing a summary of what you did, what decisions were made, and what's pending. Paste this into your AI assistant and ask it to: create tomorrow's priority list, identify anything that needs follow-up, and draft any outstanding communications.", "This process takes tasks that would otherwise live in your head overnight — generating stress and fragmented thinking — and externalizes them into a reliable system."]},
        ], "callout": "A consistent daily AI workflow compounds weekly. Build the habit before optimizing it."},
        {"title": "Writing at AI Speed", "intro": "Writing is one of the highest-leverage AI applications for professionals. Most people use it for 10% of what's possible.", "sections": [
            {"heading": "The Draft-Then-Edit Model", "body": ["For any piece of writing longer than a paragraph, stop writing from scratch. Provide AI with your key points, intended audience, and desired tone, and ask for a draft. Then edit that draft — which is dramatically faster than writing from a blank page.", "Your editing reveals what you actually think, refines your voice, and produces better output than either pure AI writing or pure from-scratch human writing. The AI produces the structure and speed; you provide the judgment and authenticity.", "This approach reduces writing time by 60-75% for most people while improving consistency and reducing writer's block entirely."]},
            {"heading": "The Prompt Vault", "body": ["Build a personal library of prompts that work for your most common writing tasks. Email to a difficult stakeholder. Executive summary of a meeting. Project status update. Proposal introduction. Monthly report.", "Save these prompts in a simple document. Over time, this vault becomes more valuable than any AI tool — it's institutional knowledge about how to get the specific outputs your role requires."]},
        ], "callout": "Stop writing from scratch. Start editing AI drafts."},
        {"title": "Research, Summarization, and Knowledge Work", "intro": "AI has transformed research from a time-consuming bottleneck into a rapid first-pass process.", "sections": [
            {"heading": "The Research Workflow", "body": ["For any research task: paste the raw material (documents, articles, transcripts) into an AI assistant and request a structured summary with key themes, notable findings, and open questions. This gives you a map before you dive into the territory.", "For competitive research, market analysis, or background preparation: use AI to generate a framework of questions first. What would I need to know to make this decision? What are the likely counterarguments? What am I probably not considering? These AI-generated question sets often reveal blind spots in your initial thinking.", "Always verify specific facts and figures from AI summaries against source documents before using them professionally."]},
        ], "callout": "AI doesn't replace research. It makes your research time higher signal."},
        {"title": "Meetings: Before, During, and After", "intro": "The meeting before the meeting and the meeting after the meeting are where most professionals waste the most time.", "sections": [
            {"heading": "AI-Powered Meeting Preparation", "body": ["Before any significant meeting, spend 10 minutes with AI: 'I'm meeting with [context]. The goal is [outcome]. Help me prepare: key questions to ask, potential objections to anticipate, the strongest version of the other party's position, and three opening statements I could use.'", "This preparation produces visibly better meeting performance. You show up with sharper questions, fewer surprises, and stronger positioning than most people who've been in the same role for years.", "After meetings: dictate or type your notes into AI and ask for action items formatted for your task manager, a summary paragraph for stakeholders who weren't present, and any follow-up emails needed."]},
        ], "callout": "AI-prepared meetings run better and conclude cleaner."},
        {"title": "Building Your AI-Augmented Career", "intro": "The professional advantage of AI isn't just today's productivity. It's compounding over your career.", "sections": [
            {"heading": "The AI-Literate Professional Edge", "body": ["AI literacy is already differentiating at the hiring level in most industries. Candidates who can demonstrate systematic AI integration in their work — not just 'I use ChatGPT sometimes' but 'here are the workflows I've built and the results they've produced' — stand out.", "Document your AI workflows. Keep a running log of time saved, quality improvements, and new capabilities you've developed. This is your professional AI portfolio, and it becomes more valuable as AI becomes more central to professional work.", "The professionals who will be most valuable in five years are those who are the best at combining human judgment with AI capability. Both sides of that equation matter — AI skill alone isn't sufficient without the domain expertise and judgment to direct it."]},
        ], "callout": "AI skill without domain expertise is a party trick. Combined with expertise, it's a career advantage."},
    ]
}

# ── Book 2 ────────────────────────────────────────────────────────────────────
b2 = {
    "title": "Prompt Engineering for Non-Coders",
    "subtitle": "How to Talk to AI Like You Know What You're Doing",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Why Your AI Gives Bad Answers", "intro": "Vague inputs produce vague outputs. Prompt engineering is the science of asking better questions.", "sections": [
            {"heading": "The AI Isn't Dumb — Your Prompt Is Ambiguous", "body": ["When an AI produces output that's too generic, too long, off-tone, or misses the point — this is almost always a prompt problem. AI models are extremely powerful pattern-completion engines. They complete the pattern you give them. If your pattern is vague, the completion is vague.", "The difference between 'write me an email about the project' and 'write a 150-word email to my operations manager, formal tone, summarizing last week's progress on the warehouse automation project and requesting a decision on vendor X by Friday' is the difference between something you'll rewrite entirely and something you'll edit in 30 seconds."]},
        ], "callout": "Specificity is the single biggest lever in prompt quality."},
        {"title": "The Anatomy of a Strong Prompt", "intro": "Strong prompts share a consistent structure. Learn it once, apply it everywhere.", "sections": [
            {"heading": "The RTSC Framework", "body": ["Role: tell the AI what role to take. 'You are an experienced marketing copywriter.' 'You are a senior financial analyst.' 'You are an expert editor who specializes in business writing.' Role-setting changes the register, assumptions, and quality of output dramatically.", "Task: be specific about what you want. Not 'write a summary' but 'write a 3-paragraph executive summary with a one-sentence conclusion that recommends a specific action.'", "Style/tone: specify how it should sound. Formal. Conversational. Direct. Empathetic. Like Harvard Business Review. Like a text message to a colleague.", "Context: give relevant background. Who is the audience? What do they already know? What decision are they trying to make? What went wrong that makes this communication necessary?"]},
        ], "callout": "Role, Task, Style, Context — use all four for important prompts."},
        {"title": "Advanced Techniques That Actually Matter", "intro": "Beyond the basics, a handful of techniques produce disproportionate quality improvements.", "sections": [
            {"heading": "Chain of Thought Prompting", "body": ["For complex reasoning tasks, ask the AI to 'think step by step' or 'show your reasoning before giving the final answer.' This activates more careful processing and produces more reliable outputs on analytical tasks.", "'Analyze the pros and cons of this decision, step by step, before giving a recommendation' produces dramatically better analysis than 'what should I do?'", "For multi-step tasks: break them into sequential prompts rather than asking for everything at once. Complete step one, review it, then use that output as context for step two. This catches errors early and maintains quality across long outputs."]},
            {"heading": "Few-Shot Prompting", "body": ["Give the AI examples of what good looks like before asking for your deliverable. 'Here is an example of the kind of email I'm trying to write: [example]. Now write a similar one for [new situation].'", "This technique is the fastest way to match your voice and style. Paste examples of your own writing and ask the AI to write in the same style. The output will sound far more like you than generic AI text."]},
        ], "callout": "Examples in your prompt outperform descriptions of what you want."},
        {"title": "Prompts for Specific Professional Tasks", "intro": "Context-specific prompts for the situations you encounter most often.", "sections": [
            {"heading": "The Prompt Templates", "body": ["Difficult email: 'I need to communicate [bad news/conflict/request] to [person/group]. They are likely to react with [frustration/resistance/confusion]. Write a professional email that is direct but not harsh, acknowledges their perspective, and moves toward [desired outcome].'", "Meeting preparation: 'I'm about to have a [type] meeting with [stakeholder] about [topic]. My goal is [outcome]. What are the 5 most important things I should know or prepare, and what questions should I ask?'", "Document review: 'I'm going to paste a document. Please summarize the main points, identify any gaps or weak arguments, flag anything that seems factually questionable, and suggest three improvements.'", "Performance review: 'Write a self-evaluation paragraph for [accomplishment] that is specific, quantitative where possible, and frames my contribution in terms of team and organizational impact.'"]},
        ], "callout": "The best prompt for a task is one you've tested and refined. Save what works."},
        {"title": "When AI Gets It Wrong and What to Do", "intro": "Recognizing AI failures is part of using AI well.", "sections": [
            {"heading": "Common Failure Modes", "body": ["Hallucination: AI confidently states incorrect facts. This is not lying — it's pattern completion that generates plausible-sounding but false information. Always verify specific claims, statistics, citations, and technical details.", "Sycophancy: many AI models are trained to please, which means they'll agree with you even when you're wrong and produce validating rather than honest responses. Counter this by explicitly asking: 'Where are the weaknesses in this argument?' or 'What am I getting wrong?'", "Generic output: the AI optimizes for the most common interpretation of your prompt, which produces average output. Specificity, examples, and iteration cure this."]},
        ], "callout": "AI is a tool that needs supervision, not a replacement for judgment."},
        {"title": "Building a Prompt Library That Grows", "intro": "Your prompt library is an asset that compounds over time.", "sections": [
            {"heading": "How to Build and Maintain It", "body": ["Every time you write a prompt that produces great output, save it. Add it to a simple document organized by task type. Note what made it work.", "Review your prompt library monthly. Refine prompts that produce inconsistent results. Add new categories as your use cases expand.", "Share your best prompts with your team. A shared prompt library is a productivity multiplier that benefits everyone and establishes you as the person who systematizes knowledge rather than hoarding it. That's a valuable professional reputation."]},
        ], "callout": "A prompt library is a professional asset. Build it intentionally."},
    ]
}

# ── Book 3 ────────────────────────────────────────────────────────────────────
b3 = {
    "title": "AI for Freelancers",
    "subtitle": "Work Smarter, Earn More, and Scale Without Burning Out",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Freelancer's Unfair Advantage", "intro": "Freelancers who integrate AI effectively can do what used to require a small team. That's not an exaggeration.", "sections": [
            {"heading": "The Solo Operator Transformation", "body": ["A freelancer's core constraint has always been time. You have 8-10 workable hours per day, and everything — client work, business development, administration, learning — competes for those hours.", "AI doesn't add hours to your day. It changes the output per hour dramatically for a specific category of tasks: writing, research, communication, drafting, organizing, and creating first-pass deliverables. For freelancers in writing, design, consulting, marketing, programming, or client services, this category covers 40-70% of billable work.", "The freelancer who systematically integrates AI into their workflow can serve more clients at the same quality, or the same clients at dramatically higher quality, in the same time. That's the economic transformation on offer."]},
        ], "callout": "AI turns a one-person operation into something that performs like a small team."},
        {"title": "Client Communication at Scale", "intro": "Client communication is essential but rarely revenue-generating. AI makes it faster without making it feel automated.", "sections": [
            {"heading": "Templates That Sound Human", "body": ["The risk with AI-generated client communication is the AI smell — that generic, slightly formal, strangely optimistic tone that makes people wonder if they're being handled rather than served.", "Counter this by: providing examples of your own voice, specifying what makes you different, and always reviewing and editing before sending. AI generates the structure and saves you from staring at a blank page; your edits put your personality back in.", "Build templates for: project proposals, project updates, scope change notifications, late payment reminders, project completion summaries, testimonial requests, and referral asks. These are the 80% of client emails most freelancers write over and over."]},
        ], "callout": "Efficient client communication isn't less personal. It's more consistent."},
        {"title": "Delivering Better Work Faster", "intro": "AI as a collaborator on client deliverables is where the real leverage lives.", "sections": [
            {"heading": "The First Draft Flip", "body": ["For any deliverable that involves writing — reports, proposals, content, copy, documentation, strategy briefs — stop writing from scratch and start with AI drafts that you refine.", "The key: your AI draft is a starting point, not a finished product. The quality of your editing and refinement is where your professional value lives. AI produces the raw material; you shape it into something that reflects your expertise and judgment.", "Track the time savings. Most freelancers find this saves 2-4 hours per day on writing-intensive work. Price your services accordingly — the time savings doesn't mean you should charge less. It means you can take on more clients or deliver better quality."]},
        ], "callout": "Your value is your judgment, not your typing speed."},
        {"title": "Business Development Without the Dread", "intro": "Business development is the task most freelancers hate and avoid. AI makes it significantly less painful.", "sections": [
            {"heading": "Proposals, Outreach, and Follow-Ups", "body": ["AI-drafted proposals: provide your process, results, relevant case studies, and the client's brief, and ask AI to draft a proposal structure. Edit for specifics and voice. This takes 45 minutes instead of 3 hours.", "Outreach emails: the most effective freelance outreach is specific and brief. 'I noticed [specific thing about your business]. I work with [type of company] on [specific problem]. Here's an example: [result]. Would a 20-minute call make sense?' AI can draft dozens of these variations from a single template.", "Follow-up sequences: most new freelance business comes from consistent follow-up. Build a 3-touch follow-up sequence with AI and deploy it consistently. The follow-up most freelancers never send is usually the one that converts."]},
        ], "callout": "The proposal you send faster is better than the perfect one you never finish."},
        {"title": "Pricing, Positioning, and AI Research", "intro": "Knowing what to charge and how to position your services is a research problem. AI accelerates both.", "sections": [
            {"heading": "Using AI for Market Research", "body": ["Ask AI to help you understand your competitive positioning: 'I'm a [specialty] freelancer with [experience]. My ideal client is [description]. Help me identify: how I should position my services, what pricing signals professionalism vs. commoditization in this market, and what the top 3 objections prospects likely have to hiring someone like me.'", "This won't replace real market research, but it generates a useful starting framework and often surfaces considerations you hadn't thought of.", "Use AI to analyze competitor positioning: paste competitor website copy and ask what they're emphasizing, where the gaps are, and how you could differentiate."]},
        ], "callout": "AI research is a starting point. Your own market observation refines it."},
        {"title": "Systems, Automation, and the Scalable Practice", "intro": "The goal for most freelancers isn't just more work — it's a more sustainable, higher-value practice.", "sections": [
            {"heading": "Building Standard Operating Procedures", "body": ["Use AI to document your own processes. 'Walk me through how you'd document a client onboarding process for a freelance [type] practice' — then fill in your specific steps. This turns tacit knowledge into explicit documentation.", "Documented processes let you: onboard subcontractors or collaborators faster, maintain quality consistency under time pressure, identify bottlenecks, and hand off tasks cleanly.", "The freelancer with documented systems is more scalable — and more valuable to acquirers, partners, and collaborators — than the one who keeps everything in their head."]},
        ], "callout": "Document your processes. Systematized knowledge is scalable. Brain-trapped knowledge is not."},
    ]
}

# ── Book 4 ────────────────────────────────────────────────────────────────────
b4 = {
    "title": "AI Writing for Content Creators",
    "subtitle": "How to Create More Without Sounding Like a Bot",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Content Creator's AI Dilemma", "intro": "AI can produce content faster than you can. That's not the threat most people think it is.", "sections": [
            {"heading": "What AI Can't Replace", "body": ["AI produces technically competent content easily. It cannot produce your specific perspective on an idea you've lived. It cannot draw on your specific audience relationship. It cannot be wrong in an interesting way, take a genuine risk, make a joke that lands because it's unexpected from you specifically.", "The content creators who are thriving with AI are using it to scale the mechanical parts — research, structuring, first drafts, repurposing — while investing their creative energy in the parts that are genuinely irreplaceable: their point of view, their voice, their relationship with their audience.", "The ones struggling are either avoiding AI entirely (falling behind on volume) or using it wholesale (losing the differentiation that built their audience in the first place)."]},
        ], "callout": "Use AI for the scaffolding. Build the building yourself."},
        {"title": "Ideation and Research at Machine Speed", "intro": "Coming up with ideas is often the slowest part of content creation. AI can help significantly.", "sections": [
            {"heading": "The Idea Generation Workflow", "body": ["Give AI your niche, your audience profile, and recent top-performing content, then ask: 'Generate 20 content ideas that would resonate with this audience, ranging from evergreen to timely. For each, suggest an angle that goes against the conventional wisdom in this space.'", "The 'against conventional wisdom' modifier is key — it forces AI away from the obvious and surfaces ideas worth actually exploring.", "Then filter ruthlessly. You're looking for ideas that make you think 'oh, I actually have a lot to say about that' — the intersection of AI-generated topics and your genuine knowledge. Those become your content calendar."]},
        ], "callout": "AI generates the options. You choose the ones only you can execute."},
        {"title": "Drafting Without Losing Your Voice", "intro": "The AI draft is a starting gun, not a finished race.", "sections": [
            {"heading": "Voice Preservation Techniques", "body": ["Provide examples of your best content when prompting for drafts. Ask AI to match your style — informal, contrarian, story-driven, data-heavy — rather than produce generic content.", "Edit heavily at the opening and closing. These are where voice is most critical and where AI drafts are typically most generic. Rewrite the first paragraph from scratch. Make sure the last paragraph sounds like you.", "Add at least one observation, story, or opinion that is genuinely yours — something AI couldn't have generated because it requires your specific lived experience. This is the ingredient that makes AI-assisted content feel authentic."]},
        ], "callout": "Edit the middle. Rewrite the edges."},
        {"title": "Repurposing: One Piece, Many Platforms", "intro": "The real efficiency gain from AI in content is repurposing — turning one piece of quality content into five.", "sections": [
            {"heading": "The Repurposing Stack", "body": ["Start with one long-form piece (article, video script, podcast episode). Then use AI to: extract 5-10 standalone insights for social posts, create a short-form summary for email, generate a thread version, rewrite it for a different platform's tone (LinkedIn vs. Instagram vs. Twitter), and create a 'key takeaways' slide format.", "This stack turns 2 hours of content creation into 7-10 distinct pieces distributed across platforms — without writing from scratch seven times.", "The quality requirement: the original piece has to be genuinely good. AI repurposing of mediocre content produces mediocre content in five formats. Start with something you're proud of."]},
        ], "callout": "One good piece, repurposed intelligently, beats ten mediocre pieces every time."},
        {"title": "SEO and Distribution with AI", "intro": "AI can significantly accelerate the technical side of content distribution.", "sections": [
            {"heading": "The Technical Workflow", "body": ["Keyword research: AI can help you brainstorm keyword clusters, identify intent behind search queries, and suggest semantic variations you might have missed. This doesn't replace dedicated SEO tools — it supplements them.", "Meta descriptions and titles: provide your article and ask AI to generate 5-10 title options and meta descriptions optimized for both click-through and keyword relevance. Choose and refine.", "Alt text, captions, and tags: use AI to generate these for every image and piece of content. Consistent, descriptive alt text improves accessibility and SEO simultaneously."]},
        ], "callout": "The distribution details are where most creators leak value. AI makes them fast."},
        {"title": "Audience Building in the AI Age", "intro": "When AI content floods every platform, human connection and consistent perspective become the differentiator.", "sections": [
            {"heading": "The New Differentiators", "body": ["Specificity: the more niche your perspective, the harder it is to AI-generate. A generalist content approach becomes commoditized by AI. A highly specific, deeply knowledgeable perspective — even on a narrow topic — is increasingly valuable.", "Consistency: showing up reliably, with a recognizable perspective and voice, over months and years, builds audience trust that no volume of AI-generated content can shortcut.", "Community: moving beyond content consumption to active community — comments, live interactions, direct conversations with your audience — creates value that AI cannot replicate and platform algorithms cannot undermine."]},
        ], "callout": "In the AI age, specificity and consistency are the only moats."},
    ]
}

# ── Book 5 ────────────────────────────────────────────────────────────────────
b5 = {
    "title": "AI for Small Business Owners",
    "subtitle": "Practical Tools to Run Your Business Better Without a Big Team",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What AI Means for the Small Business", "intro": "For the first time in business history, a small team can perform like a large one in certain key areas.", "sections": [
            {"heading": "The Operational Leverage", "body": ["Small business owners wear every hat: marketing, customer service, operations, financial oversight, sales, HR, and the actual work of the business. The limiting factor has always been time and expertise across all these functions.", "AI doesn't make you an expert in everything. But it gives you a knowledgeable first-pass assistant in almost every domain — one that can draft, research, analyze, communicate, and generate options 24 hours a day without taking a salary.", "The small business owners gaining the most from AI are using it as a thinking partner and first-draft machine across every function — not just for marketing copy or chatbots."]},
        ], "callout": "AI is the first genuinely useful generalist assistant most small business owners have ever had."},
        {"title": "Customer Communication and Service", "intro": "Consistent, fast, professional customer communication builds trust. AI makes it achievable for teams of one.", "sections": [
            {"heading": "The Customer Communication Stack", "body": ["Response templates: build AI-assisted templates for your 10 most common customer inquiries. Not robotic FAQ answers — genuine, helpful, on-brand responses that can be personalized in seconds.", "Complaint handling: these require particular care. Provide AI with your service philosophy and the specific complaint, and ask it to draft a response that acknowledges the issue genuinely, takes responsibility where appropriate, offers a clear resolution, and does not sound defensive.", "Follow-up sequences: after purchase, after delivery, after service — automated follow-ups (using AI to draft them once) that check in, invite feedback, and plant the seeds for repeat business."]},
        ], "callout": "Customer communication built on templates is more consistent than communication built on mood."},
        {"title": "Marketing Without a Marketing Team", "intro": "Small businesses consistently underinvest in marketing because it feels overwhelming and expensive. AI changes both.", "sections": [
            {"heading": "Content Marketing Made Feasible", "body": ["One well-written blog post per week, consistently published, builds search visibility over years. AI can cut the writing time from 3 hours to 45 minutes — making the consistency actually achievable.", "Social media: plan a month of content in a single 2-hour session using AI to generate ideas, draft posts, and create variation across platforms. Review and edit everything — but stop starting from scratch each day.", "Email marketing: a monthly customer email is one of the highest-ROI marketing activities for most small businesses. AI can draft it from your key points in minutes."]},
        ], "callout": "Consistent imperfect marketing beats occasional perfect marketing every time."},
        {"title": "Operations and Administration", "intro": "The operational overhead of running a small business is where hours disappear silently.", "sections": [
            {"heading": "Documents, SOPs, and Agreements", "body": ["Use AI to draft standard operating procedures for your core processes. These don't need to be formal — they need to capture what good looks like so you or anyone else can reproduce it.", "Contract templates, proposal templates, onboarding documents, employee handbooks (for small teams) — AI can draft first versions of all of these from your description of your needs. Have a relevant professional (attorney, HR consultant) review anything with legal implications.", "Job postings: AI-drafted job descriptions save hours and often produce more specific, appealing listings than ones written under time pressure. Provide a clear description of the role and your company culture — then edit for accuracy."]},
        ], "callout": "Document once. Benefit indefinitely."},
        {"title": "Financial Analysis and Decision Support", "intro": "You don't need a CFO to think financially. You need good questions and time to work through them.", "sections": [
            {"heading": "AI as a Financial Thinking Partner", "body": ["Paste your P&L or basic financial summary into AI and ask: 'What are the most important observations here? What should I be concerned about? What questions should I be asking that I'm not?'", "This doesn't replace an accountant. But it surfaces observations you might miss when you're too close to the numbers, and it prepares you for more productive conversations with your financial professionals.", "Scenario modeling: 'If I hire a part-time employee at $X, and it allows me to take on Y% more revenue, what's the break-even point and how long would it take to see positive ROI?' AI can structure this analysis for you to plug real numbers into."]},
        ], "callout": "AI can ask the financial questions you didn't know to ask."},
        {"title": "Building a Business That Can Run Without You", "intro": "The ultimate goal of systematizing your small business is optionality — a business that generates income whether you're there or not.", "sections": [
            {"heading": "The Systemization Roadmap", "body": ["Identify the three processes in your business where you are the single point of failure. These are your systemization priorities.", "Use AI to help document these processes step by step: 'Help me create a step-by-step standard operating procedure for [process] that someone with no prior knowledge of my business could follow.'", "Review the documentation. Add the nuances and judgment calls that AI couldn't know. Test it. Refine it. Then you have a transferable process.", "A business built on documented processes can be delegated, automated, scaled, or sold. A business built entirely on the owner's tacit knowledge cannot."]},
        ], "callout": "A documented business is a scalable business."},
    ]
}

# ── Book 6 ────────────────────────────────────────────────────────────────────
b6 = {
    "title": "AI Ethics for Everyday Users",
    "subtitle": "How to Use Powerful Tools Responsibly",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "Why Ethics Matter When You're Just Using a Tool", "intro": "A hammer can build a home or break a window. How you use the tool determines which.", "sections": [
            {"heading": "The Scale Problem", "body": ["What makes AI ethics different from the ethics of other tools is scale and speed. A single person with a word processor can produce limited harm. A single person with a large language model and poor judgment can generate thousands of pieces of misleading content, mass-personalize manipulative messages, or amplify false information to enormous audiences in hours.", "This isn't hypothetical. Scale is what changes the ethical calculation around AI. Actions that would be inconsequential at human speed become significant at AI speed."]},
        ], "callout": "AI amplifies what you do with it — including the mistakes."},
        {"title": "Transparency and Disclosure", "intro": "When does it matter to tell people you used AI? More often than most people want to admit.", "sections": [
            {"heading": "The Disclosure Question", "body": ["The general principle: disclose AI use when the person receiving your work would reasonably want to know it. In journalism, academic work, professional advice, and personal creative work presented as your own — disclosure matters.", "In commercial content — marketing, product descriptions, service communications — the standards vary by industry and are evolving. The underlying principle: don't use AI to create false impressions that a human expert reviewed and endorsed something that wasn't actually reviewed.", "In your personal communications: you're not obligated to disclose that you used AI to help draft an email. But if the communication is deeply personal — a eulogy, a heartfelt letter, a therapeutic exchange — the authenticity question is worth sitting with."]},
        ], "callout": "Ask: would this person want to know? If yes, tell them."},
        {"title": "Misinformation and Your Responsibility", "intro": "AI hallucination is real and your responsibility to check doesn't go away because AI generated the content.", "sections": [
            {"heading": "The Verification Imperative", "body": ["AI models generate plausible-sounding text. Plausible-sounding and accurate are different things. The model does not know it's wrong when it's wrong — it generates the most statistically likely continuation of your prompt, which can be factually incorrect with high confidence.", "When you publish, share, or present AI-generated content as fact — especially statistics, historical claims, citations, medical information, legal information, or scientific findings — you are responsible for its accuracy.", "The professional standard: verify specific factual claims against authoritative sources before professional or public use. This is not optional. It's the minimum due diligence."]},
        ], "callout": "AI generated it. You're still responsible for it."},
        {"title": "Privacy and Data Considerations", "intro": "What you put into AI tools matters. Once it's there, your control over it is limited.", "sections": [
            {"heading": "What Not to Put Into AI Tools", "body": ["Do not paste personally identifiable information about third parties into commercial AI tools unless you have explicit authorization and understand the tool's data handling policy. Patient information, client information, employee information, financial account details — these carry legal and ethical obligations.", "Most commercial AI tools use inputs to improve their models by default unless you opt out or use an enterprise tier. Check the privacy settings and data policies of any tool you use professionally.", "Use the AI's enterprise or privacy-preserving tier when handling sensitive business information. The cost is usually modest; the risk reduction is significant."]},
        ], "callout": "Your inputs are data. Protect other people's data as seriously as your own."},
        {"title": "Bias, Fairness, and Critical Use", "intro": "AI models reflect the data they were trained on — which means they reflect human biases, historical inequities, and cultural blind spots.", "sections": [
            {"heading": "Using AI Critically", "body": ["AI models can produce content that stereotypes, excludes, or subtly favors certain perspectives due to training data composition. This is not the model being malicious — it's a reflection of patterns in human-generated text.", "When using AI for communications, hiring support, customer profiling, or content that affects diverse audiences: review outputs with a critical eye for implicit bias. Ask: who is centered in this output? Who is absent? What assumptions does this make?", "Prompt for diversity explicitly when it's relevant: 'Make sure your examples represent diverse professional backgrounds, genders, and cultures.' This doesn't fix systemic bias, but it improves individual outputs."]},
        ], "callout": "AI inherits human biases. Critical use means spotting them."},
        {"title": "The Human Judgment Line", "intro": "Some decisions should never be delegated to AI. Knowing where that line is matters.", "sections": [
            {"heading": "Where Human Judgment Is Non-Negotiable", "body": ["High-stakes irreversible decisions: hiring final decisions, firing decisions, major financial commitments, medical treatment choices, legal strategy — AI can inform these but should not make them.", "Communications with emotional weight: bereavement messages, disciplinary conversations, relationship-defining discussions — these require human presence and judgment that AI cannot provide.", "Accountability: when someone will be harmed or helped by an outcome, a human accountable to that person should be the decision-maker. AI cannot be held accountable in the way that matters — it cannot apologize authentically, cannot be sued, cannot feel the weight of consequences.", "Use AI to prepare for these moments, to research, to draft, to think. Then step up yourself."]},
        ], "callout": "Efficiency is not the highest value. Some things require you."},
    ]
}

# ── Book 7 ────────────────────────────────────────────────────────────────────
b7 = {
    "title": "The AI Job Search",
    "subtitle": "Land Interviews Faster Using the Tools Your Competition Isn't Using Yet",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Modern Job Market Is an Information Game", "intro": "You're not competing for jobs. You're competing for interviews. The preparation is everything.", "sections": [
            {"heading": "Why Most Applications Fail", "body": ["The average corporate job posting receives 250 applications. Roughly 75% are filtered out by applicant tracking systems before a human sees them. Of the ones humans review, 70% spend under 10 seconds on each resume.", "This means most job searching is inefficient by design — broad, low-personalization applications that don't pass automated filters and don't stop a human's 10-second skim.", "AI changes the economics of personalization. Tailoring your resume and cover letter to each application used to take 45-90 minutes. With AI, it takes 10-15. This means you can apply to quality opportunities at higher volume without sacrificing the personalization that actually converts."]},
        ], "callout": "Volume without personalization is noise. AI makes personalized volume possible."},
        {"title": "Resume Optimization with AI", "intro": "Your resume is a filter. The goal is to pass the right filters and fail the wrong ones.", "sections": [
            {"heading": "ATS-Optimized Resumes", "body": ["Paste the job description and your resume into an AI assistant and ask: 'Identify the keywords and phrases in this job description that don't appear in my resume but should, given my experience. Suggest specific rewrites for each bullet point to incorporate these terms naturally.'", "This process takes 10 minutes and significantly improves ATS performance. You're not fabricating experience — you're ensuring that experience you actually have is described in the language the filter is looking for.", "Ask AI to score your resume against the job description and identify the three biggest gaps between what the job requires and what your resume emphasizes."]},
        ], "callout": "Your experience matters. Describing it in the right language matters just as much."},
        {"title": "Cover Letters That Get Read", "intro": "Most cover letters are ignored because they're generic. AI can help you write specific ones faster than generic ones.", "sections": [
            {"heading": "The Specificity Formula", "body": ["Effective cover letters do three things: establish immediate relevance ('my background in X directly addresses your need for Y'), demonstrate specific knowledge of the company ('I noticed your recent expansion into Z'), and make a clear, confident ask.", "Give AI the job description, your resume, and any research you have on the company. Ask it to draft a cover letter that hits these three elements specifically.", "Edit heavily for voice. The cover letter is where personality comes through — make sure it sounds like you, not like AI. Rewrite the opening and closing paragraphs in your own voice."]},
        ], "callout": "A specific cover letter about their company beats a perfect generic one."},
        {"title": "Interview Preparation at Depth", "intro": "AI can help you prepare for interviews more thoroughly than most candidates bother to.", "sections": [
            {"heading": "The Full Preparation Protocol", "body": ["Company research: 'I'm interviewing at [company] for [role]. Summarize what you know about their business model, recent news, main competitors, and the key challenges in their industry. What questions might they ask that relate to these factors?'", "STAR story preparation: 'Based on this job description, what are the 5 most likely competency interview questions? For each, help me develop a STAR (Situation, Task, Action, Result) format answer using my background.'", "Hard question practice: 'What are the 5 hardest questions I might face in this interview, and what would an excellent answer to each look like?' Then practice answering them out loud — AI can evaluate written responses but genuine preparation requires speaking practice."]},
        ], "callout": "The candidate who prepares the most thoroughly almost always gets the offer."},
        {"title": "Networking and Outreach", "intro": "Most jobs are filled through networks before they're ever posted. AI can help you build and activate yours.", "sections": [
            {"heading": "The Outreach System", "body": ["Identify 20 people at companies you're targeting — hiring managers, potential peers, alumni connections. Use AI to draft personalized outreach messages for each: specific to their role, referencing something genuine about their work or company, with a clear, low-friction ask (a 20-minute call, a specific question, not 'do you have any openings').", "Follow-up: 80% of professional outreach goes unanswered. Send a second message two weeks later. AI can help you draft graceful follow-ups that acknowledge their busy schedule and repeat the value proposition.", "LinkedIn optimization: ask AI to review your LinkedIn headline and summary against the roles you're targeting and suggest specific improvements to increase appearing in recruiter searches."]},
        ], "callout": "Outreach at scale with genuine personalization is how offers come to you."},
        {"title": "Negotiating the Offer", "intro": "Getting the offer is step one. Maximizing it is step two, and most people skip it.", "sections": [
            {"heading": "The AI-Assisted Negotiation", "body": ["Once you have an offer, use AI to: research market rates for the role and location, identify the full compensation package (base, bonus, equity, benefits, PTO, flexibility), and draft the negotiation response.", "'Draft a professional response to this job offer that expresses genuine enthusiasm, requests a few days to consider, and includes a counter on base salary to [X] based on my research and experience.'", "Practice the negotiation conversation aloud. Ask AI to play the role of a firm hiring manager and respond to your counter. This simulation reduces anxiety and improves your actual performance."]},
        ], "callout": "The offer is the beginning of the negotiation, not the end of it."},
    ]
}

# ── Book 8 ────────────────────────────────────────────────────────────────────
b8 = {
    "title": "AI for Educators and Trainers",
    "subtitle": "Save Hours, Engage More, and Teach Better With Modern Tools",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The Education Transformation That's Already Here", "intro": "AI hasn't replaced teachers. It has changed what excellent teaching looks like.", "sections": [
            {"heading": "The New Teaching Leverage Points", "body": ["The most time-consuming parts of teaching — creating materials, differentiating for learning levels, generating assessment questions, giving written feedback — are precisely the tasks where AI provides the most support.", "The irreplaceable parts of teaching — building relationships with students, noticing who is confused before they raise their hand, adjusting in real time, knowing when a student needs more challenge and when they need more scaffolding — are entirely human and become more central when the mechanical tasks are handled.", "Teachers who integrate AI thoughtfully don't teach less rigorously. They teach more humanly."]},
        ], "callout": "AI handles the preparation. You do the teaching."},
        {"title": "Curriculum and Lesson Planning", "intro": "The planning cycle that used to take a full Sunday can now take a Saturday afternoon.", "sections": [
            {"heading": "The Planning Workflow", "body": ["Provide AI with your learning objectives, student level, available time, and any constraints (standards alignment, prerequisite knowledge, available materials). Ask for a lesson plan outline that includes: opening hook, direct instruction component, practice activity, formative assessment, and closure.", "Ask for three variations — one for grade-level, one for students who need more scaffolding, and one for students ready for extension. This differentiation, which can take hours manually, takes 15 minutes with AI.", "Review and refine. AI lesson plans are starting points. Your knowledge of your specific students transforms them into effective instruction."]},
        ], "callout": "Differentiated instruction in 15 minutes instead of 3 hours."},
        {"title": "Assessment and Feedback", "intro": "Meaningful written feedback is one of the most powerful learning tools — and one of the most time-consuming to provide.", "sections": [
            {"heading": "The Feedback Loop Accelerated", "body": ["For written student work: paste the assignment rubric and the student's work into AI and ask for: specific strengths aligned to the rubric, specific areas for improvement with concrete suggestions, and one growth goal for this student's next assignment.", "Review every AI-generated feedback draft. Your professional judgment may adjust the tone, add context you know about the student, or identify something the AI missed. But the draft saves 70% of the time.", "For formative assessment: describe your learning objective and ask AI to generate 5 multiple choice, 3 short answer, and 2 application questions. Edit for level-appropriateness and select the strongest."]},
        ], "callout": "More frequent feedback, not less, is what learning research recommends. AI makes it achievable."},
        {"title": "Engagement and Creative Activities", "intro": "Engaging instructional activities are harder to generate than content lectures. AI can help with both creation and curation.", "sections": [
            {"heading": "Activity Design", "body": ["Describe your topic and learning objective and ask AI to suggest 10 engaging activity formats: 'I'm teaching [topic] to [grade/level]. The learning objective is [objective]. Suggest 10 different activity formats, ranging from individual to collaborative, that would work for this content.'", "AI is particularly good at generating scenario-based learning activities, debate setups, case studies, and project structures — which are often the most engaging formats but also the most time-intensive to design.", "Ask for the 'hook' before any unit: 'What is the most counterintuitive, surprising, or provocative question I could ask at the start of this unit to generate genuine curiosity?'"]},
        ], "callout": "The best lesson design starts with the hook. AI can generate dozens for you to choose from."},
        {"title": "Parent and Administrator Communication", "intro": "Communication outside the classroom is significant time burden that AI can reduce substantially.", "sections": [
            {"heading": "Templates and Personalization", "body": ["Build AI-drafted templates for: newsletter updates, progress concern notifications, positive recognition emails, conference invitation letters, and common parent inquiry responses.", "The personalization that makes these communications effective — specific student names, specific observations, specific context — you add in your edit pass. AI provides the professional structure; you provide the human knowledge.", "Annual documents — course syllabus, classroom policy letters, parent handbook sections — can be drafted by AI from your notes and preferences, then edited into final form."]},
        ], "callout": "Professional communication doesn't require professional writing time with AI assistance."},
        {"title": "Professional Development and Staying Current", "intro": "Teaching is a knowledge profession, and staying current matters. AI is a powerful learning tool for the learner-teacher.", "sections": [
            {"heading": "AI as a Personal Learning Partner", "body": ["Use AI to: summarize research papers in your field before you read the full text, generate discussion questions for professional reading groups, explain unfamiliar pedagogical frameworks in accessible terms, and synthesize connections between new research and your current practice.", "'I'm reading research on retrieval practice in learning. Summarize the key findings, their practical classroom implications, and any important caveats about the research quality.' This is a better professional development session than most hour-long workshops.", "Ask AI to identify the gaps in your pedagogical approach: 'Based on what I've described about my teaching practice, what approaches am I probably not using that current research suggests are effective?'"]},
        ], "callout": "The teacher who uses AI to stay current will teach better than the one who doesn't."},
    ]
}

# ── Book 9 ────────────────────────────────────────────────────────────────────
b9 = {
    "title": "AI Tools Compared",
    "subtitle": "ChatGPT, Claude, Gemini, and More — What to Use When",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "The AI Tool Landscape", "intro": "The number of AI tools is overwhelming. The underlying decision is simpler than it looks.", "sections": [
            {"heading": "What They All Have in Common", "body": ["The major general-purpose AI assistants — ChatGPT (OpenAI), Claude (Anthropic), Gemini (Google), Copilot (Microsoft) — are all large language models trained to predict and generate text. Their core capability is similar: they can read, write, summarize, analyze, code, brainstorm, and converse across virtually any topic.", "The differences are in emphasis, style, specific strengths, integration, and pricing. Understanding these differences helps you choose the right tool for the right task rather than defaulting to one tool for everything.", "Note: AI capabilities evolve rapidly. Specific details about features, pricing, and performance described here may change. Always verify current capabilities before committing to a paid tier."]},
        ], "callout": "The best AI tool is the one you'll actually use consistently for the task at hand."},
        {"title": "ChatGPT: Strengths and Best Uses", "intro": "The tool that introduced the world to conversational AI. Still the most widely used.", "sections": [
            {"heading": "What It Does Well", "body": ["ChatGPT, particularly in its more capable versions, excels at creative tasks, code generation, broad general knowledge, and plugin/tool integrations. The DALL-E integration for image generation adds a multimodal dimension other text-only tools lack.", "The GPT store offers thousands of custom GPTs for specific use cases — legal research, recipe generation, language tutoring, specialized coding — which provides access to purpose-built tools without building them yourself.", "Best use cases: coding assistance, image generation, general creative tasks, broad research, tasks where plugin integrations add value."]},
        ], "callout": "ChatGPT's ecosystem of integrations makes it the Swiss Army knife of AI tools."},
        {"title": "Claude: Strengths and Best Uses", "intro": "Anthropic's Claude takes a different approach, with particular strengths in nuanced writing and extended reasoning.", "sections": [
            {"heading": "What It Does Well", "body": ["Claude is consistently noted for writing quality that sounds more natural, less formulaic, and better calibrated to tone and context than comparable outputs from other tools. For writing-intensive professional work, this distinction is meaningful.", "Claude handles very long documents well — summarizing, analyzing, and reasoning across extended context windows. Pasting a long contract, report, or research paper and asking for analysis tends to work well.", "Anthropic's safety-focused approach means Claude is less likely to produce harmful content but also occasionally more conservative than other tools on ambiguous requests. Best use cases: writing and editing, long document analysis, nuanced professional communication, tasks where voice and tone fidelity matter."]},
        ], "callout": "For writing quality and long-document work, Claude is worth evaluating."},
        {"title": "Gemini and Google Integration", "intro": "Google's AI is most valuable for users already deep in the Google ecosystem.", "sections": [
            {"heading": "The Integration Advantage", "body": ["Gemini's primary advantage is integration with Google Workspace — Gmail, Docs, Sheets, Slides, Drive. For teams and individuals using Google products heavily, Gemini can assist within those applications directly, reducing the friction of moving between tools.", "Gemini Advanced has multimodal capabilities — analyzing images, audio, and video alongside text — which extends its utility beyond pure text workflows.", "Best use cases: Google Workspace users who want in-app AI assistance, tasks requiring multimedia analysis, real-time search integration."]},
        ], "callout": "Gemini's value scales with your investment in the Google ecosystem."},
        {"title": "Specialized Tools for Specific Jobs", "intro": "Beyond the general-purpose assistants, a growing ecosystem of specialized AI tools serves specific professional functions well.", "sections": [
            {"heading": "Category Leaders", "body": ["Coding: GitHub Copilot and Cursor integrate AI directly into code editors, making them more useful for active development than general-purpose AI assistants.", "Image generation: Midjourney remains the quality leader for artistic images; DALL-E 3 integrates directly into ChatGPT; Stable Diffusion offers free open-source alternatives.", "Audio and video: ElevenLabs for voice cloning and text-to-speech; Runway for AI video generation; Descript for AI-assisted audio and video editing.", "Research: Perplexity.ai for research tasks requiring up-to-date web information with citations; Elicit for academic literature review.", "The principle: for any specialized professional task, check whether a purpose-built AI tool exists before trying to use a general-purpose assistant."]},
        ], "callout": "The right specialized tool outperforms a general tool on specific tasks."},
        {"title": "Building Your Personal AI Stack", "intro": "Most professionals don't need every AI tool. They need three or four that cover their main use cases.", "sections": [
            {"heading": "The Decision Framework", "body": ["Start with one general-purpose assistant and use it consistently for 30 days. Master its strengths and learn its limits.", "Identify the two or three tasks in your work where the general-purpose tool underperforms. Look for specialized tools for those specific use cases.", "Test before subscribing. Most AI tools have free tiers that let you evaluate before committing. Run your actual most-important work tasks through any tool before paying for it.", "Your AI stack should serve your actual workflow, not an idealized version of it. Two tools you use daily beat ten tools you evaluate and abandon."]},
        ], "callout": "Depth beats breadth. Master fewer tools rather than sampling many."},
    ]
}

# ── Book 10 ───────────────────────────────────────────────────────────────────
b10 = {
    "title": "Future-Proofing Your Career with AI",
    "subtitle": "The Skills, Mindset, and Strategy for Staying Relevant",
    "series_name": SERIES, "accent_hex": ACCENT, "bg_hex": BG,
    "disclaimer": DISCLAIMER,
    "chapters": [
        {"title": "What AI Can and Cannot Replace", "intro": "The fear about AI replacing jobs is real. The answer is more nuanced than either 'everything will be fine' or 'we're all doomed.'", "sections": [
            {"heading": "The Honest Assessment", "body": ["AI excels at tasks that are: well-defined, pattern-based, high-volume, language-dependent, and separable from broader judgment and relationships. This covers a significant portion of many professional roles.", "AI underperforms in tasks that require: genuine physical presence, trusted human relationship, real-time adaptive judgment in complex social situations, creative work requiring lived experience, ethical accountability, and deep contextual expertise built over years.", "The jobs most at risk are those composed primarily of the first category. The jobs most secure are those composed primarily of the second. Most jobs have elements of both — which means most jobs will transform rather than disappear, at least in the near-to-medium term."]},
        ], "callout": "The question is not whether your job is at risk. It's which parts of it are."},
        {"title": "The Durable Skills", "intro": "Some human capabilities are becoming more valuable, not less, as AI becomes more capable.", "sections": [
            {"heading": "What to Build Now", "body": ["Critical evaluation: the ability to assess whether AI output is correct, appropriate, and complete. As AI generates more of the first draft of professional work, the ability to evaluate it rigorously becomes more valuable.", "Synthesis and judgment: connecting information across domains, weighing competing considerations, making decisions under uncertainty. AI generates options; humans choose among them with judgment built from experience.", "Relationship and communication: trust, empathy, negotiation, difficult conversations, leadership. These are human capabilities that AI can support but not replace.", "Domain expertise: deep knowledge in a specific area remains valuable — both because it enables better AI direction (better prompts, better evaluation of outputs) and because it provides the judgment foundation that AI cannot substitute.", "Creative thinking: genuinely novel ideas, conceptual leaps, creative risk-taking. AI recombines existing patterns; humans still generate new ones."]},
        ], "callout": "The skills most worth building are the ones AI cannot automate."},
        {"title": "Becoming an AI-Augmented Professional", "intro": "The future advantage isn't AI skill alone or human skill alone — it's both together.  ", "sections": [
            {"heading": "The Combination Edge", "body": ["The most competitive professionals in the coming decade will be those who combine deep domain expertise with AI fluency. Not AI experts who lack domain knowledge. Not domain experts who refuse to engage with AI tools. The ones who bring both.", "This combination is genuinely rare right now — most domain experts underinvest in AI skills, and most AI-enthusiastic people underinvest in the domain expertise that would make their AI use powerful.", "Build both deliberately. Protect time for domain learning (reading in your field, building specialized skills, taking on challenging problems) while simultaneously investing in AI fluency (systematic tool use, prompt development, staying current on what the tools can do)."]},
        ], "callout": "Domain expertise + AI fluency = the professional combination most in demand."},
        {"title": "Industries Being Transformed", "intro": "The AI transformation is not uniform across industries. Understanding where your sector is in the transformation helps you plan.", "sections": [
            {"heading": "The Transformation Map", "body": ["Rapidly transforming: legal (document review, contract analysis, research), medicine (diagnostic imaging analysis, clinical note generation, medical literature synthesis), finance (report generation, risk modeling, compliance documentation), and media (content generation, translation, summarization).", "Actively transforming: education, customer service, software development, marketing, human resources, real estate.", "Earlier stage: construction, healthcare delivery (the human-facing parts), skilled trades, and roles requiring physical presence and complex hands-on judgment.", "In every industry, the pattern is similar: routine cognitive tasks automate; judgment, relationship, and creative tasks transform; entirely new roles emerge that didn't exist before AI."]},
        ], "callout": "Every industry is transforming at different speeds. Know where yours is."},
        {"title": "Navigating Career Transition in the AI Age", "intro": "For some professionals, AI disruption will require genuine career navigation. Here's a framework for that.", "sections": [
            {"heading": "The Career Audit", "body": ["Honestly assess your current role: which tasks are high AI-automation-risk, and which are low? What percentage of your current value comes from each category?", "If the automation-risk percentage is high: identify adjacent skills or roles that have lower automation risk and that your current experience helps you reach. Lateral moves toward judgment-intensive roles within your domain are often available without returning to school.", "Reskilling is real and sometimes necessary. The resources are more accessible than ever: university extension programs, professional certifications, online platforms, AI-specific courses. The investment required is significant, but the cost of not investing may be higher."]},
        ], "callout": "The time to navigate is before the disruption, not during it."},
        {"title": "The Professional Opportunity in AI Transition", "intro": "Transitions create opportunities as often as they create disruption. The professionals who see both dimensions are the ones who navigate best.", "sections": [
            {"heading": "Where the New Opportunities Are", "body": ["AI implementation: every organization needs people who can identify where AI should be applied, implement it responsibly, and manage the organizational change that follows. This is a hybrid technical-human role that barely existed five years ago and is now in high demand.", "AI training and education: every professional who has mastered AI-augmented work has an opportunity to teach others. Corporate training, consulting, online courses, internal mentoring.", "Creative AI direction: the people who can give AI direction that produces genuinely excellent outputs — editors, creative directors, content strategists, UX designers — are more valuable, not less, when AI is producing the first draft.", "The transition is real. The opportunity is also real. You need both to navigate well."]},
        ], "callout": "Disruption creates opportunity for people who can see both sides of it."},
    ]
}

books = [b1, b2, b3, b4, b5, b6, b7, b8, b9, b10]
filenames = [
    "01 - AI for the Overwhelmed Professional.pdf",
    "02 - Prompt Engineering for Non-Coders.pdf",
    "03 - AI for Freelancers.pdf",
    "04 - AI Writing for Content Creators.pdf",
    "05 - AI for Small Business Owners.pdf",
    "06 - AI Ethics for Everyday Users.pdf",
    "07 - The AI Job Search.pdf",
    "08 - AI for Educators and Trainers.pdf",
    "09 - AI Tools Compared.pdf",
    "10 - Future-Proofing Your Career with AI.pdf",
]

for book, fname in zip(books, filenames):
    generate_ebook(os.path.join(OUT, fname), book)

print("SERIES 6 DONE")
